### PR TITLE
Reset CI tests when PR tags are set back to 'Ready'

### LINKED ISSUE #1649: CI Experiment not cleared when starting over
**Expected behavior**
When a PR has a CI tag removed and is placed back into the "Ready" state, any pre-existing experiments should be deleted before a fresh set of tests begins.

**Current behavior**
CI attempts to create experiments on top of the existing ones and fails.

**Machines affected**
Orion for sure, but likely all.

**To Reproduce**
1. Mark a PR as CI-Ready
2. Let it run a while, possibly until failure/passage
3. Remove the CI tag and mark it as CI-Ready again

**Context**
Noticed in PR #1644, where it also extended the status report resulting in weird formatting:

image

This PR had CI fail on Orion, then the CI-Orion-Failed tag was removed and CI-Orion-Ready applied again.

**Detailed Description**

**Additional Information**

**Possible Implementation**

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
**Description**

**bug** fix **feature** that adds updates to the CI cron BASH scripts that track an ID based on how many times the label gets updated to Ready.  This ID count is used in the driver script so that it can distinguish a real fail and one caused by removing the current build that is overwritten by a new Ready request.

Fixes #1649

**Type of change**

updates to drive scripts so a CI run can stop and restart midstream.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

I updated the CI label to **Ready** when it was **Building** and it did not create a false fail.

**Checklist**

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

File: ci/scripts/check_ci.sh [hunk 1]
```diff
@@ -57,7 +57,7 @@ pr_list_dbfile="${GFS_CI_ROOT}/open_pr_list.db"
 
 pr_list=""
 if [[ -f "${pr_list_dbfile}" ]]; then
-  pr_list=$("${HOMEgfs}/ci/scripts/pr_list_database.py" --display "${pr_list_dbfile}" | grep -v Failed | grep Running | awk '{print $1}') || true
+  pr_list=$("${HOMEgfs}/ci/scripts/pr_list_database.py" --display --sbfild "${pr_list_dbfile}" | grep -v Failed | grep Running | awk '{print $1}') || true
```
Comment (aerorahul) [inline ci/scripts/check_ci.sh]: Should this be `--sbfile`?  Is this a `typo`?

File: ci/scripts/driver.sh [hunk 2]
```diff
@@ -59,18 +59,38 @@ set -x
...
 
 pr_list=$(${GH} pr list --repo "${REPO_URL}" --label "CI-${MACHINE_ID^}-Ready" --state "open" | awk '{print $1}') || true
 
 for pr in ${pr_list}; do
-  "${HOMEgfs}/ci/scripts/pr_list_database.py" --add_pr "${pr}" "${pr_list_dbfile}"
+  db_list=$("${HOMEgfs}/ci/scripts/pr_list_database.py" --add_pr "${pr}" --sbfile "${pr_list_dbfile}")
+  pr_id=0
+#############################################################
+# Check if a Ready labeled PR has changed back from once set 
+# and in that case remove all previous jobs in slubm and
```
Comment (aerorahul) [inline ci/scripts/driver.sh]:
```suggestion
# and in that case remove all previous jobs in scheduler and
```

File: ci/scripts/driver.sh [hunk 3]
```diff
@@ -59,18 +59,38 @@ set -x
...
+    pr_id=$("${HOMEgfs}/ci/scripts/pr_list_database.py" --display --sbfile "${pr_list_dbfile}" | awk '{print $4}') || true
+    pr_id=$((pr_id+1))
+    "${HOMEgfs}/ci/scripts/pr_list_database.py" --sbfile "${pr_list_dbfile}" --update_pr "${pr}" Open Ready "${pr_id}"
+    pr_dir="${GFS_CI_ROOT}/PR/${pr}"
+    for cases in "${pr_dir}/RUNTESTS/"*; do
+      if [[ -z "${cases+x}" ]]; then
+         break
+      fi   
+      pslot=$(basename "${cases}")
+      sacct --format=jobid,jobname%35,WorkDir%100,stat | grep "${pslot}" | grep "PR\/${pr}\/RUNTESTS" |  awk '{print $1}' | xargs scancel || true
```
Comment (aerorahul) [inline ci/scripts/driver.sh:85]: I see you are hard-wiring `sacct` for `slurm`.  Fine for now, but beware when you try and do this on WCOSS2 which has `PBS`.

File: ci/scripts/pr_list_database.py [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 import sys
 from pathlib import Path
+import argparse
```
Comment (aerorahul) [inline ci/scripts/pr_list_database.py]: Aren't you already importing what you need from `argparse` on line 6?  What is this for?

**Review by aerorahul — COMMENTED** [review]
Looks mostly ok.
A typo was spotted, and a clarification is sought.

File: ci/scripts/check_ci.sh (hunk 1 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/check_ci.sh]: yes it should, updating.

File: ci/scripts/driver.sh (hunk 3 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/driver.sh:85]: Oh yes, good to know!

File: ci/scripts/pr_list_database.py (hunk 4 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: actually, I needed it for `argparse.REMAINDER` on line 126

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
@aerorahul  : updated typo and responded to comments and questions

File: ci/scripts/driver.sh [hunk 5]
```diff
@@ -59,18 +59,38 @@ set -x
...
 
 for pr in ${pr_list}; do
-  "${HOMEgfs}/ci/scripts/pr_list_database.py" --add_pr "${pr}" "${pr_list_dbfile}"
+  db_list=$("${HOMEgfs}/ci/scripts/pr_list_database.py" --add_pr "${pr}" --sbfile "${pr_list_dbfile}")
+  pr_id=0
+#############################################################
+# Check if a Ready labeled PR has changed back from once set 
+# and in that case remove all previous jobs in scheduler and
+# and remove PR from filesystem to start clean
+#############################################################
```
Comment (WalterKolczynski-NOAA) [inline ci/scripts/driver.sh]: Comment indentation should match the block it is contained in.

File: ci/scripts/pr_list_database.py (hunk 4 above)
Comment (WalterKolczynski-NOAA) [reply ci/scripts/pr_list_database.py]: Why not just import that then?

File: ci/scripts/pr_list_database.py [hunk 6]
```diff
@@ -51,14 +52,14 @@ def sql_insert(obj: sqlite3.Cursor, entities: list) -> None:
     obj : sqlite3.Cursor
         Cursor object for Sqlite3
     entities : list
-        The list three string values that go into sqlite table (pr, state, status)
+        The list three string values that go into sqlite table (pr, state, status, reset)
```
Comment (WalterKolczynski-NOAA) [inline ci/scripts/pr_list_database.py]:
```suggestion
        A list of four string values that go into sqlite table (pr, state, status, reset)
            pr: pull request number
            state: The new value for the state (Open, Closed)
            status: The new value for the status (Ready, Running, Failed)
            reset: The value for number of times reset to Ready
```

File: ci/scripts/pr_list_database.py [hunk 7]
```diff
@@ -114,11 +119,12 @@ def input_args():
     parser = ArgumentParser(description=description,
                             formatter_class=ArgumentDefaultsHelpFormatter)
 
-    parser.add_argument('sbfile', help='SQLite3 database file with PR list', type=str)
+    parser.add_argument('--sbfile', help='SQLite3 database file with PR list')
```
Comment (WalterKolczynski-NOAA) [inline ci/scripts/pr_list_database.py]: Why was the type removed?

File: ci/scripts/driver.sh [hunk 8]
```diff
@@ -85,23 +105,35 @@ fi
...
   # call clone-build_ci to clone and build PR
   id=$("${GH}" pr view "${pr}" --repo "${REPO_URL}" --json id --jq '.id')
   set +e
   "${HOMEgfs}/ci/scripts/clone-build_ci.sh" -p "${pr}" -d "${pr_dir}" -o "${pr_dir}/output_${id}"
   ci_status=$?
+##################################################################
+# Checking for special case when Ready label was updated
+# that cause a running driver exit fail because was currently
+# building so we force and exit 0 instead to does not get relabled
+#################################################################
```
Comment (WalterKolczynski-NOAA) [inline ci/scripts/driver.sh]: Add indentation to match surroundings.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: ci/scripts/pr_list_database.py (hunk 4 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: ok

File: ci/scripts/pr_list_database.py (hunk 7 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: "type removed"?? I added this argument as a switch instead it being positional because the update argument list was no longer fixed.

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
spacing - import

File: ci/scripts/pr_list_database.py (hunk 7 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: Oh wait, I missed the wrap around, yes the type was changed because it is being passed as a list now.  You can see the list is applied to the database in a loop depending the number of arguments.  This may need work and we have decided to improve on this interface for another PR.

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
added comment after understanding the question better from Walter on the arg list for the database update script

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
submit review

File: ci/scripts/pr_list_database.py (hunk 7 above)
Comment (WalterKolczynski-NOAA) [reply ci/scripts/pr_list_database.py]: I just went through the PR and I do not see anywhere where `--sbfile` is passed multiple files. Further, I do not see a use case where we would want to use multiple _databases_.

Also, if you wanted to have a list, shouldn't you would use `nargs`?:
```suggestion
    parser.add_argument('--sbfiles', help='SQLite3 database file with PR list', nargs='+', type=str)
```

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: Oh, I misspoke,  `sbfiles` is no longer positional because `update_pr` takes a variable number of arguments and there the type change here was for another reason.

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: BTW, the type was removed, not changed, because it had to take on a path and there was an issue with it being a string, not sure why that matters.

Comment (WalterKolczynski-NOAA) [reply ci/scripts/pr_list_database.py]: I'm not sure why `str` wouldn't work anymore, but I'll take your word for it. Leave this unresolved in case Rahul wants to chime in.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: ci/scripts/pr_list_database.py (hunk 7 above)
Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py:125]: me neither, let me check ...

`(gfs_workflow) mterry (Orion-login-1) scripts (bug_1649_Ready-Restart) $ git diff pr_list_database.py 
diff --git a/ci/scripts/pr_list_database.py b/ci/scripts/pr_list_database.py
index 8f519e0f..a099ff51 100755
--- a/ci/scripts/pr_list_database.py
+++ b/ci/scripts/pr_list_database.py
@@ -122,7 +122,7 @@ def input_args():
     parser = ArgumentParser(description=description,
                             formatter_class=ArgumentDefaultsHelpFormatter)
 
-    parser.add_argument('--sbfile', help='SQLite3 database file with PR list')
+    parser.add_argument('--sbfile', help='SQLite3 database file with PR list', type=str)
     parser.add_argument('--create', help='create sqlite file for pr list status', action='store_true', required=False)
     parser.add_argument('--add_pr', nargs=1, metavar='PR', help='add new pr to list (defults to: Open,Ready)', required=False)
     parser.add_argument('--remove_pr', nargs=1, metavar='PR', help='removes pr from list', required=False)
(gfs_workflow) mterry (Orion-login-1) scripts (bug_1649_Ready-Restart) $ ./pr_list_database.py --display --sbfile /work2/noaa/stmp/GFS_CI_ROOT/open_pr_list.db
1601 Open Built 0`

Yep, no big deal here.

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: Me neither, here let me check ...

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]:
```
(gfs_workflow) mterry (Orion-login-1) scripts (bug_1649_Ready-Restart) $ git diff pr_list_database.py 
diff --git a/ci/scripts/pr_list_database.py b/ci/scripts/pr_list_database.py
index 8f519e0f..a099ff51 100755
--- a/ci/scripts/pr_list_database.py
+++ b/ci/scripts/pr_list_database.py
@@ -122,7 +122,7 @@ def input_args():
     parser = ArgumentParser(description=description,
                             formatter_class=ArgumentDefaultsHelpFormatter)
 
-    parser.add_argument('--sbfile', help='SQLite3 database file with PR list')
+    parser.add_argument('--sbfile', help='SQLite3 database file with PR list', type=str)
     parser.add_argument('--create', help='create sqlite file for pr list status', action='store_true', required=False)
     parser.add_argument('--add_pr', nargs=1, metavar='PR', help='add new pr to list (defults to: Open,Ready)', required=False)
     parser.add_argument('--remove_pr', nargs=1, metavar='PR', help='removes pr from list', required=False)
(gfs_workflow) mterry (Orion-login-1) scripts (bug_1649_Ready-Restart) $ ./pr_list_database.py --display --sbfile /work2/noaa/stmp/GFS_CI_ROOT/open_pr_list.db
1601 Open Built 0
```

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/pr_list_database.py]: Yep, no big deal.

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
re-submit review
