### PR TITLE
Fix bug in gempak walltime calculation

### LINKED ISSUE #3630: Long runtimes and error messages in some gfs_gempak_f jobs on WCOSS2
### What is wrong?

Several `gfs_gempak_f*` jobs in the extended CI test case on WCOSS2 are consistently hitting their 30min walltimes. The automated 2nd attempt will also hit the walltime. A third attempt hours later always completes successfully. First thought was that the issue was a machine issue but other CI testing since the first instance are continuing to have the same issues in the same jobs.

Viewing the logs shows the following message repeated many times for those jobs: `Error in message send = 22`. The resulting job logs are about 15-20GB in size (!) with those error messages printed, whereas the gempak logs are usually MBs and not GBs.

The affected jobs are `gfs_gempak_f123-f144` and `gfs_gempak_f147-f168`. Do not see the error messages in any of the other `gfs_gempak_f*` jobs in the same CI tests.

Snippet from log where the error first appears:
```
+ cpfs[13]cpdstfile=/lfs/h2/emc/ptmp/emc.global/PR/PR_3626/RUNTESTS/COMROOT/C96_atm3DVar_extended_3626/gfs.20211221/06//products/atmos/gempak/35km_pac/gfs_35km_pac_2021122
106f168
Error in message send = 22
itype, ichan, nwords,2,22216705,2
Error in message send = 22
itype, ichan, nwords,2,22216705,2
Error in message send = 22
itype, ichan, nwords,2,22216705,2
...
```

See saved logs on Cactus: `/lfs/h2/emc/global/noscrub/emc.global/ci/SAVE_LOGS_3626`

### What should have happened?

No error message and job completes on time.

### What machines are impacted?

WCOSS2

### What global-workflow hash are you using?

`develop` and recent PR hashes

### Steps to reproduce

Run `develop` extended CI test case on WCOSS2 with `DO_GEMPAK=YES`.

### Additional information

_No response_

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR fixes a bug that inadvertently reset the resource settings for the gempak metatask jobs. A line to obtain job resources was left during work to add metatask functionality back in for post-processing jobs. This lead to the walltime multiplication based on the # of forecast hours to be undone. The gempak walltime is now also reduced from 30mins to 5mins, which is the time needed for gempak to process a single forecast hour. The metatask group multiplication now correctly increases the walltime to 45mins (9 forecast hours x 5mins) and allows gempak the needed time to complete successfully.

Changes:
- Remove line in `gfs_tasks.py` that reset resources (bug)
- Update gempak walltime to be 5mins per forecast hour instead of 30mins, with bug fix the walltime multiplication correctly works for the gempak-per-forecast-hour jobs.
- Move `gpend` up in `exgfs_atmos_nawips.sh` to before the output file is copied to COM. Also add err check for `gpend`, thanks @aerorahul !

Resolves #3630

# Type of change
- [x] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

Ran C96 extended test on WCOSS2.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my code, including function, input, and output descriptions
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] This change is covered by an existing CI test or a new one has been added
- [x] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [x] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

File: scripts/exgfs_atmos_nawips.sh [hunk 1]
```diff
@@ -119,13 +119,14 @@ if [[ ${err} -ne 0 ]]; then
    err_exit
 fi
 
+"${GEMEXE}/gpend"
```
Comment (aerorahul) [inline scripts/exgfs_atmos_nawips.sh:122]:
```suggestion
"${GEMEXE}/gpend"
export err=$?
if [[ ${err} -ne 0 ]]; then
   err_exit "${GEMEXE}/gpend failed!"
fi
```

Comment (KateFriedman-NOAA) [reply scripts/exgfs_atmos_nawips.sh:122]: Thanks @aerorahul!

**Review by aerorahul — APPROVED** [review]
lgtm

File: dev/workflow/rocoto/gfs_tasks.py [hunk 2]
```diff
@@ -1598,7 +1598,6 @@ def gempak(self):
         for key, value in gempak_dict.items():
             gempak_vars.append(rocoto.create_envar(name=key, value=str(value)))
 
-        resources = self.get_resource('gempak')
```
Comment (aerorahul) [inline dev/workflow/rocoto/gfs_tasks.py:1601]: Good catch @KateFriedman-NOAA!

**Review by DavidHuber-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
CI Tests set up to run in /lfs/h2/emc/ptmp/emc.global/PR/PR_3823/RUNTESTS on WCOSS

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA @RussTreadon-NOAA FYI, the `enkfgdas_atmensanlobs` job in the `C96C48_ufs_hybatmDA` CI test for this PR hit it's walltime three times before succeeding within the walltime. Perhaps a little more walltime is needed? You can see the logs here on Dogwood: `/lfs/h2/emc/ptmp/emc.global/PR/PR_3823/RUNTESTS/COMROOT/C96C48_ufs_hybatmDA_3823/logs/2024022406/enkfgdas_atmensanlobs*`

That CI test case is continuing past that point of failure now. All other CI tests for this PR are complete.

**Comment by CoryMartin-NOAA** [comment]
Thanks @KateFriedman-NOAA . @RussTreadon-NOAA  this doesn't seem correct. Looks like it might be CRTM related?

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA and @CoryMartin-NOAA:

I checked `enkfgdas_atmensanlobs.log` from my run of C96C48_ufs_hybatmDA for PR #3760.  `gdas.x` wall times are below 500 seconds
```
2024022400/enkfgdas_atmensanlobs.log:nid003658.dogwood.wcoss2.ncep.noaa.gov 0: OOPS_STATS Run end                                  - Runtime:    497.93 sec,  Memory: total:   669.95 Gb, per task: min =     6.68 Gb, max =     7.99 Gb
2024022406/enkfgdas_atmensanlobs.log:nid002482.dogwood.wcoss2.ncep.noaa.gov 0: OOPS_STATS Run end                                  - Runtime:    489.38 sec,  Memory: total:   653.10 Gb, per task: min =     6.54 Gb, max =     7.61 Gb
```
with a total job run time under 9 minutes
```
2024022400/enkfgdas_atmensanlobs.log:End /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr3760/jobs/JGLOBAL_ATMENS_ANALYSIS_OBS at 12:41:01 with error code 0 (time elapsed: 00:08:41)
2024022406/enkfgdas_atmensanlobs.log:End /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr3760/jobs/JGLOBAL_ATMENS_ANALYSIS_OBS at 13:45:29 with error code 0 (time elapsed: 00:08:33)
```

**Comment by KateFriedman-NOAA** [comment]
CI completed successfully on WCOSS2:
```
Tue Jun 24 15:51:31 UTC 2025
******** C48_ATM_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jun 23 2025 17:20:05    Jun 23 2025 18:21:49

******** C48mx500_3DVarAOWCDA_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Jun 23 2025 17:20:07    Jun 23 2025 17:32:14
202103250000        Done    Jun 23 2025 17:20:07    Jun 23 2025 19:52:00

******** C48mx500_hybAOWCDA_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Jun 23 2025 17:20:09    Jun 23 2025 17:32:22
202103250000        Done    Jun 23 2025 17:20:09    Jun 23 2025 18:37:10

******** C48_S2SW_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jun 23 2025 17:20:11    Jun 23 2025 18:32:07

******** C48_S2SWA_gefs_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jun 23 2025 17:20:14    Jun 23 2025 18:27:32

******** C48_S2SW_extended_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jun 23 2025 17:20:17    Jun 23 2025 20:12:10
202103231800        Done    Jun 23 2025 17:20:17    Jun 23 2025 20:22:21

******** C96_atm3DVar_extended_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Jun 23 2025 17:20:20    Jun 23 2025 17:37:39
202112210000        Done    Jun 23 2025 17:20:20    Jun 23 2025 21:47:24
202112210600        Done    Jun 23 2025 17:20:20    Jun 23 2025 22:47:15
202112211200        Done    Jun 23 2025 17:42:38    Jun 23 2025 23:27:16
202112211800        Done    Jun 23 2025 21:52:37    Jun 24 2025 02:42:15

******** C96C48_hybatmDA_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Jun 23 2025 17:20:22    Jun 23 2025 17:37:46
202112210000        Done    Jun 23 2025 17:20:22    Jun 23 2025 20:27:32
202112210600        Done    Jun 23 2025 17:20:22    Jun 23 2025 20:07:37

******** C96C48_hybatmsnowDA_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Jun 23 2025 17:20:25    Jun 23 2025 17:37:53
202112201800        Done    Jun 23 2025 17:20:25    Jun 23 2025 20:22:44
202112210000        Done    Jun 23 2025 17:20:25    Jun 23 2025 20:07:43

******** C96C48mx500_S2SW_cyc_gfs_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Jun 23 2025 17:20:27    Jun 23 2025 17:38:00
202112201800        Done    Jun 23 2025 17:20:27    Jun 23 2025 20:27:44
202112210000        Done    Jun 23 2025 17:20:27    Jun 23 2025 21:03:08
202112211800        Done    Jun 23 2025 17:43:00    Jun 23 2025 20:57:52

******** C96C48_ufs_hybatmDA_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202402231800        Done    Jun 23 2025 17:20:29    Jun 23 2025 17:38:07
202402240000        Done    Jun 23 2025 17:20:29    Jun 23 2025 20:33:01
202402240600        Done    Jun 23 2025 17:20:29    Jun 24 2025 15:38:09

******** C96_gcafs_cycled_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Jun 23 2025 17:20:31    Jun 23 2025 17:38:14
202112201800        Done    Jun 23 2025 17:20:31    Jun 23 2025 20:18:12
202112210000        Done    Jun 23 2025 17:20:31    Jun 23 2025 20:03:15

******** C96mx100_S2S_3823 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
199405010000        Done    Jun 23 2025 17:20:34    Jun 23 2025 18:53:31
```

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA @RussTreadon-NOAA I will leave the CI output for this PR on Dogwood until the scrubber gets it, so you have it for troubleshooting if needed.

**Comment by RussTreadon-NOAA** [comment]
The  20240224 00Z enkfgdas_atmensanlobs ran long in the EIB run of C96C48_ufs_hybatmDA for PR #3760 
```
2024022400/enkfgdas_atmensanlobs.log:End /lfs/h2/emc/ptmp/emc.global/PR/PR_3760/global-workflow/jobs/JGLOBAL_ATMENS_ANALYSIS_OBS at 15:54:26 with error code 0 (time elapsed: 00:26:58)
2024022406/enkfgdas_atmensanlobs.log:End /lfs/h2/emc/ptmp/emc.global/PR/PR_3760/global-workflow/jobs/JGLOBAL_ATMENS_ANALYSIS_OBS at 16:40:57 with error code 0 (time elapsed: 00:08:31)
```

My run of 20240224 00Z enkfgdas_atmensanlobs took about 9 minutes.  EIB's run of the same job took 27 minutes.  I can't explain a 3x difference for the same job run by different users at different times.

This extreme variability is something to keep an eye on for GFS v18.  

@KateFriedman-NOAA :  Feel free to increase the WCOSS2 enkfgdas_atmensanlobs wall time if you want,

**Comment by KateFriedman-NOAA** [comment]
> Feel free to increase the WCOSS2 enkfgdas_atmensanlobs wall time if you want

Let's see how the job does in the next round of CI on WCOSS2 and see if it hits the walltime again or if perhaps this was a transient issue. Thanks for looking into this @RussTreadon-NOAA !
