### PR TITLE
Fix bugs in forecast-only mode (GFSv16)

### LINKED ISSUE #1177: Fix several bugs in GFSv16 forecast-only cold-start mode
User reported bug in GFSv16 forecast-only cold-start mode.

**Expected behavior**

The f000 output from the forecast job should be produced in forecast-only mode when running with cold-start ICs (a.k.a. lower resolution).

**Current behavior**

When running forecast-only mode with cold-start ICs the f000 files are not produced by the forecast model in cycles after the initial cycle.

**Machines affected**

All.

**To Reproduce**

Run lower resolution / cold-start forecast-only mode for more than one cycle.

**Detailed Description**

Upon investigation it is an issue with the `IAU_OFFSET` variable being mismatched with the `DOIAU` setting. The `DOIAU` variable will be set to no in the forecast job when the forecast script does not see prior cycle warm-start inputs but the `IAU_OFFSET` variable does not get set to 0 to match. With `IAU_OFFSET=3` the forecast model doesn't start producing output until 3hr (or 6hr if using 6hr frequency). This causes a ripple effect in the post, postsnd, and archive jobs. The post f000 files aren't produced and thus the postsnd and archive jobs fail.

**Possible Implementation**

Need to check for forecast-only mode and cold-start earlier in the job so `IAU_OFFSET=0` can be set and passed for the forecast model. The following if-block in `config.base[.emc.dyn]` can be expanded to handle this for now:
```
if [[ "$SDATE" = "$CDATE" && $EXP_WARM_START = ".false." ]] || [[ "$DOIAU" = "NO" ]] ; then # Cold starting or IAU off
```
...should be changed to:
```
if [[ "$SDATE" = "$CDATE" && $EXP_WARM_START = ".false." ]] || [[ "$DOIAU" = "NO" ]] || [[ "$MODE" = "forecast-only" && $EXP_WARM_START = ".false." ]] ; then # Cold starting or IAU off
```
Looking at the system, the `MODE` variable was added to the setup scripts but didn't make it into the config. 

Add `export MODE="@MODE@"` into `config.base.emc.dyn` for use by updated if-block conditions (shown above). Also change "free" to "forecast-only" in `setup_expt_fcstonly.py` to be consistent with `develop` branch implementation. The `develop` branch does not have this issue since it has the expanded check in `config.base`.

Will correct, test, and commit into the `dev/gfs.v16` branch.

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
**Description**

This PR resolves several user-reported bugs in GFSv16 forecast-only dev mode (no bugs/impact related to ops). Some bugs were specific to cold-start mode as well and don't exist in forecast-only warm-start mode.

Fixed issues:

- Inconsistency with IAU settings resulted in f000 (and f003 if running 3hrly or less frequency) outputs not being produced in forecast-only cold-start mode. This issue was already fixed in the `develop` branch and does not exist in cycled or forecast-only warm-start mode. 
  - Updated an if-block in `config.base.emc.dyn` to also check for `MODE=forecast-only` and `EXP_WARM_START=.false` and, if true, adjust IAU variables similar to cycled mode (`IAU_OFFSET=0` and `IAU_FHROT=0`).
  - Also add missing `MODE` settings to `config.base.emc.dyn` for use in updated IAU if-block. Had been added to setup scripts but didn't get added to config.
  - Change "free" to "forecast-only" in `ush/rocoto/setup_expt_fcstonly.py` to be consistent with similar work done in `develop`.
- Add missing `COMINsyn` setting to `config.base.emc.dyn` and setup scripts for use by tracker. Related to this, update `comroot` paths in setup scripts for newer syndat file location on supported platforms.
- Update `jobs/rocoto/arch.sh` and `ush/hpssarch_gen.sh` to only archive certain files in cycled mode (files that won't/don't exist in forecast-only mode). Introduced `MODE=cycled` and `MODE=forecast-only` checks where needed.
- Address some tab/space mixing in `jobs/rocoto/arch.sh`.

Fixes will be available to users in the `dev/gfs.v16` branch and go into future v16.3.6+ ops updates. Will also become available to users when `release/gfs.v16.3.5` gets merged back into `dev/gfs.v16` branch and a `gfs.v16.3.5` tag is cut and released to users.

Resolves #1177 

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

User on Hera kindly tested fixes in on-going forecast-only experiment and confirmed fixes worked to resolve issues.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

File: jobs/rocoto/arch.sh [hunk 1]
```diff
@@ -182,7 +182,11 @@ if [ $CDUMP = "gfs" ]; then
 
     #for targrp in gfs_flux gfs_netcdf/nemsio gfs_pgrb2b; do
     if [ ${SAVEFCSTNEMSIO:-"YES"} = "YES" ]; then
-        for targrp in gfs_flux gfs_${format}a gfs_${format}b gfs_pgrb2b; do
+	targrp_list="gfs_flux gfs_${format}b gfs_pgrb2b"
+	if [ $MODE = "cycled" ] ; then
+	    targrp_list="${targrp_list} gfs_${format}a"
+        fi
+        for targrp in $targrp_list; do
             htar -P -cvf $ATARDIR/$CDATE/${targrp}.tar `cat $ARCH_LIST/${targrp}.txt`
```
Comment (WalterKolczynski-NOAA) [inline jobs/rocoto/arch.sh:190]: Indentation is rendering as incorrect on GitHub. Check for space/tab mixing.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: jobs/rocoto/arch.sh (hunk 1 above)
Comment (KateFriedman-NOAA) [reply jobs/rocoto/arch.sh:190]: Good catch. I addressed mixed tab/space in that section and went through the rest of the script to replace other tabs with spaces.
