### PR TITLE
Enforce decimal math in atmos post

### LINKED ISSUE #1141: Octal forecast hour unintentionally used in logical expression
**Expected behavior**

Forecast hours (`fhr`) should be treated as a decimal, not octal, when executing math expressions.

**Current behavior**

In [exgdas_atmos_post.sh:222](https://github.com/NOAA-EMC/global-workflow/blob/e2c29749ffe4050ce4e0273ef4802b8458bbc59c/scripts/exgdas_atmos_post.sh#L222), `fhr` is treated as an octal, resulting in an error when `fhr=008`, etc.  This results in the `if` evaluating to `false` and `IGEN=${IGEN_ANL}`.  In the end, this makes not difference as `IGEN` is not used in any meaningful way.

**Machines affected**

All

**To Reproduce**

Run a post job for forecast hour 008 or 009.

**Possible Implementation**

Remove all references to `IGEN`, unless there are plans to use this variable in the future.  If so, then replace
`if (( fhr > 0 )); then`
with
```
d_fhr=$((10#$fhr))
if (( d_fhr > 0 )); then
```

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
`fhr` was still being treated as an octal in some places of atmos post. Instances where `fhr` are used for math are now updated to `d_fhr`, which is always a decimal representation of the `fhr` string.

Fixes #1141 

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
Tested in hera:/scratch1/NCEPDEV/global/Lin.Gan/git/PR/issue-1141/scripts/test.sh

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good, thanks @lgannoaa!

File: scripts/exgdas_atmos_post.sh [hunk 1]
```diff
@@ -329,15 +331,15 @@ else   ## not_anl if_stimes
...
+        if [[ "${INLINE_POST}" = ".false." ]]; then
           ${POSTGPSH}
           export err=$?; err_chk
           mv fluxfile "${COMOUT}/${FLUXFL}"
         fi
         ${WGRIB2} -s "${COMOUT}/${FLUXFL}" > "${COMOUT}/${FLUXFLIDX}"
       fi
 
-      if [ "${SENDDBN}" = 'YES' ] && [ "${RUN}" = 'gdas' ] && (( fhr % 3 == 0 )); then
+      if [[ "${SENDDBN}" = 'YES' ]] && [[ "${RUN}" = 'gdas' ]] && (( fhr % 3 == 0 )); then
```
Comment (WalterKolczynski-NOAA) [inline scripts/exgdas_atmos_post.sh]: This one should be decimal too

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

**Review by WalterKolczynski-NOAA — APPROVED** [review]
