### PR TITLE
GFS-UTILS update for build and ush scripts

### LINKED ISSUE #1059: finddate.sh not found
**Expected behavior**
Job `gdasgldas` should run to completion.

**Current behavior**
Job `gdasgldas` fails with the error
```
+ gldas_forcing.sh[25](20211222): sdate=20211222
++ gldas_forcing.sh[26](20211222): sh /work/noaa/da/Russ.Treadon/git/global_workflow/develop/util/ush/finddate.sh 20211225 d-1
sh: /work/noaa/da/Russ.Treadon/git/global_workflow/develop/util/ush/finddate.sh: No such file or directory
+ gldas_forcing.sh[26](20211222): edate=
+ gldas_forcing.sh[1](20211222): postamble gldas_forcing.sh 1665485341 127
+ preamble.sh[68](20211222): set +x
End gldas_forcing.sh at 10:49:01 with error code 127 (time elapsed: 00:00:00)
```
`config.gldas` sets

`export FINDDATE=$HOMEgfs/util/ush/finddate.sh`

`finddate.sh` does not exist at this path.

**Machines affected**
Only tested on Orion

**To Reproduce**
Install the g-w from the current head of develop (e915eb64).   Set up `EXPDIR` to run a parallel.  Populate `ROTDIR` with the files needed to fully execute `gdasgldas`.  Submit `gdasgldas`.

**Additional Information**
Due to this bug we can not run a cycled experiment with gldas.

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
**Description**

This PR updates the gfs-utils version (af933d3) and ush script symlinks/paths. This will resolve issue #1059 until `finddate.sh` can be used via the `prod_util` module.

* New gfs-utils hash: af933d3
* A number of ush scripts were moved into the new gfs-utils repo but not added to `link_workflow.sh`. This PR adds them to `link_workflow.sh`.
* Several workflow scripts are updated to point to the gfs-utils ush symlinks under the top level `/ush` folder instead of the prior `/util/ush` folder.

Fixes #1059 

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

- [x] Clone and build tests on WCOSS2, Hera, Orion
- [x] Cycled tests on WCOSS2, Hera, Orion
  
Addresses #1059

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Looks good. Does this PR bring in the new hash of gfs-utils `develop` or are we still pointing to `feature/consistent`?
Also, just a note for TODO, `finddate.sh` is a part of `prod_util`.  In the future we could just use it from there.
Thanks @KateFriedman-NOAA

**Comment by KateFriedman-NOAA** [comment]
Merged `feature/consistent` into gfs-utils `develop` and updated hash (af933d3) in this PR.

File: sorc/build_gfs_utils.sh [hunk 1]
```diff
@@ -40,6 +40,6 @@ shift $((OPTIND-1))
 
 BUILD_TYPE=${BUILD_TYPE:-"Release"} \
 BUILD_VERBOSE=${BUILD_VERBOSE:-"NO"} \
-${cwd}/gfs_utils.fd/ush/build.sh
+"${cwd}"/gfs_utils.fd/ush/build.sh
```
Comment (WalterKolczynski-NOAA) [inline sorc/build_gfs_utils.sh]: Just quote the whole path.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: sorc/build_gfs_utils.sh (hunk 1 above)
Comment (KateFriedman-NOAA) [reply sorc/build_gfs_utils.sh]: Done.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
