### PR TITLE
Fix analysis post processing's handling of 0-padded negative integers

### LINKED ISSUE #2185: Analysis post products not generated properly
### What is wrong?

The gdasatmanlprod and gfsatmanlprod jobs are failing with the error messages
```
+ atmos_products.sh[16]: jobid=atmos_products.307715
basename: extra operand ‘products.sh’
Try 'basename --help' for more information.
+ [20]: IFS=_
basename: extra operand ‘products.sh’
Try 'basename --help' for more information.
+ [20]: read -ra fhrs
+ atmos_products.sh[24]: for fhr in "${fhrs[@]}"
<path/to/global-workflow>/jobs/rocoto/atmos_products.sh: line 25: 10#: invalid integer constant (error token is "10#")
+ atmos_products.sh[27]: exit 0
+ atmos_products.sh[1]: postamble atmos_products.sh 1703188983 0
+ preamble.sh[68]: set +x
End atmos_products.sh at 20:03:04 with error code 0 (time elapsed: 00:00:01)
```

This traces back to the way `$FHRLST` is defined in gfs_tasks.py:
https://github.com/NOAA-EMC/global-workflow/blob/d1251360325faf75af9df0608557fcd10202a883/workflow/rocoto/gfs_tasks.py#L582

This turns into a silent failure due to the following line in atmos_products.sh:
https://github.com/NOAA-EMC/global-workflow/blob/d1251360325faf75af9df0608557fcd10202a883/jobs/rocoto/atmos_products.sh#L28

### What should have happened?

The analysis products should be generated based off of the analysis master PGB.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run a cycled experiment through the first full cycle then check gdasatmanlprod.log.

### Additional information

Found during cycle testing on Hercules.

### Do you have a proposed solution?

Replace `-f001` with `anl` in gfs_tasks.py, though this does not solve other potential silent `basename` failures in `atmos_products`.
Appended:
This doesn't fix the issue by itself as the `10#` operator causes a failure on `anl`.  Will need to wrap it in an if.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This screens for the analysis 'forecast' hour (-001) and handles the '-' and circumvents octal issues.

Resolves #2185

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Ran an analysis post and a forecast group post for both the gfs and gdas cycles on Hercules.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
       It does generate a new warning, but I am dismissing it for the sake of preserving vim syntax highlighting.
- [ ] New and existing tests pass with my changes

### CODE REVIEW

File: jobs/rocoto/atmos_products.sh [hunk 1]
```diff
@@ -22,7 +22,11 @@
 #---------------------------------------------------------------
 # Execute the JJOB
 for fhr in "${fhrs[@]}"; do
-    export FORECAST_HOUR=$(( 10#${fhr} ))
+    # The analysis fhr is -001.  Performing math on negative, leading 0 integers is tricky.
+    # The negative needs to be in front of "10#", so do some regex magic to make it happen.
+    fhr="10#${fhr}"
+    fhr=$( echo ${fhr} | sed "s/10#-/-10#/" )
```
[the remark this answers is not in the document]
Comment (DavidHuber-NOAA) [reply jobs/rocoto/atmos_products.sh]: I can use this option, but it causes syntax highlighting to kerfuffle because it ends with a `#`.

**Review by aerorahul — APPROVED** [review]
This works.  Thanks!
I am not sure why the previous iteration was not working.  It works on Hera as this little test snippet can demonstrate:
```bash
#!/usr/bin/env bash
for FHRLST in f000_f003 f000 -f001; do

  echo "FHRLST = $FHRLST"

  fhrlst=$(echo "${FHRLST}" | sed -e 's/f//g')
  IFS='_' read -ra fhrs <<< "$fhrlst"

  #---------------------------------------------------------------
  for fhr in ${fhrs[@]}; do
      FORECAST_HOUR=$(( 10#${fhr} ))
      #fhr="10#${fhr}"
      #fhr=$( echo "${fhr}" | sed "s/10#-/-10#/" )
      #FORECAST_HOUR=$(( fhr ))
      echo "FORECAST_HOUR = ${FORECAST_HOUR}"
  done

  echo "==="

done
```

The output is:
```sh
$> ./test.sh
FHRLST = f000_f003
FORECAST_HOUR = 0
FORECAST_HOUR = 3
===
FHRLST = f000
FORECAST_HOUR = 0
===
FHRLST = -f001
FORECAST_HOUR = -1
===
```

**Comment by DavidHuber-NOAA** [comment]
It appears that this is a bash version issue.  Hercules is running a newer version than the other machines:

Hercules: 5.1.8(1)-release
Orion: 4.2.46(2)-release
Hera: 4.2.46(2)-release

File: jobs/rocoto/atmos_products.sh [hunk 2]
```diff
@@ -22,7 +22,11 @@ IFS='_' read -ra fhrs <<< "${FHRLST//f}" # strip off the 'f's and convert to arr
 #---------------------------------------------------------------
 # Execute the JJOB
 for fhr in "${fhrs[@]}"; do
-    export FORECAST_HOUR=$(( 10#${fhr} ))
+    # The analysis fhr is -001.  Performing math on negative, leading 0 integers is tricky.
+    # The negative needs to be in front of "10#", so do some regex magic to make it happen.
+    fhr="10#${fhr}"
+    fhr=$( echo "${fhr}" | sed "s/10#-/-10#/" )
```
Comment (aerorahul) [inline jobs/rocoto/atmos_products.sh]: This will get rid of the shellcheck error
```suggestion
    fhr=${fhr//10#-/-10#}
```

File: jobs/rocoto/atmos_products.sh [hunk 3]
```diff
@@ -22,7 +22,11 @@ IFS='_' read -ra fhrs <<< "${FHRLST//f}" # strip off the 'f's and convert to arr
 #---------------------------------------------------------------
 # Execute the JJOB
 for fhr in "${fhrs[@]}"; do
-    export FORECAST_HOUR=$(( 10#${fhr} ))
+    # The analysis fhr is -001.  Performing math on negative, leading 0 integers is tricky.
+    # The negative needs to be in front of "10#", so do some regex magic to make it happen.
+    fhr="10#${fhr}"
+    fhr=${fhr//10#-/-10#}
```
Comment (DavidHuber-NOAA) [inline jobs/rocoto/atmos_products.sh]: Escape the `#` to preserve vim syntax highlighting:
```suggestion
    fhr=${fhr//10\#-/-10\#}
```
