### PR TITLE
Revert g2tmpl back to 1.10.0

### LINKED ISSUE #772: [BUG] Mismatch between hpc-ips and g2tmpl version on WCOSS-Dell
@RuiyuSun reported failing UPP on WCOSS-Dell via the `develop` branch. @WenMeng-NOAA traced the error down to the `POSTGRB2TBL` variable being unset. Since we're not setting `POSTGRB2TBL` explicitly from the configs it uses the UPP script (`scripts/exgfs_atmos_nceppost.sh`) default which uses `g2tmpl_ROOT` from the `g2tmpl` module:
```
     export POSTGRB2TBL=${POSTGRB2TBL:-${g2tmpl_ROOT}/share/params_grib2_tbl_new}
```
At runtime a module mismatch occurs which results in the `g2tmpl` module not loading, not setting `g2tmpl_ROOT`, and the `POSTGRB2TBL` variable not getting set. The current `g2tmpl` version in `develop` is `1.10.1` and the current `hpc-ips` version in `develop` is `18.0.1.163`. The `g2tmpl/1.10.1` module isn't available under the `hpc-ips/18.0.1.163` module however:

```
[Kate.Friedman@v71a1 upptest]$ module spider g2tmpl/1.10.1

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  g2tmpl: g2tmpl/1.10.1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      g2tmpl library


    You will need to load all module(s) on any one of the lines below before the "g2tmpl/1.10.1" module is available to load.

      hpc/1.1.0  hpc-ips/18.0.5.274
```

...whereas the prior `g2tmpl/1.10.0` is available under both the current hpc-ips and the one that has `1.10.1`:
```
[Kate.Friedman@v71a1 upptest]$ module spider g2tmpl/1.10.0

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  g2tmpl: g2tmpl/1.10.0
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      g2tmpl library


    You will need to load all module(s) on any one of the lines below before the "g2tmpl/1.10.0" module is available to load.

      hpc/1.1.0  hpc-ips/18.0.1.163
      hpc/1.1.0  hpc-ips/18.0.5.274
```

Looks like the `g2tmpl_ver` was inadvertently changed to `1.10.1` and should still be `1.10.0`.

**Expected behavior**
The `g2tmpl` module loads and sets `g2tmpl_ROOT` for use when setting the `POSTGRB2TBL` variable.

**Current behavior**
The `g2tmpl` module isn't loading and therefore the `POSTGRB2TBL` variable isn't being set and is causing the post job to fail.

**Machines affected**
WCOSS-Dell

**To Reproduce**
Set the following in module_base.wcoss_dell_p3.lua:
```
load(pathJoin("hpc-ips", "18.0.1.163"))
load(pathJoin("g2tmpl", "1.10.1"))
```

**Fix**

Roll back the version of the `g2tmpl` version in `module_base.wcoss_dell_p3.lua` to `1.10.0`:
```
load(pathJoin("g2tmpl", "1.10.0"))
```

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
**Description**

This PR resolves a mismatch bug between `hpc-ips` and `g2tmpl` versions on the WCOSS-Dells. The current `g2tmpl` version `1.10.1` is not available under the current `hpc-ips` `18.0.1.163` version. See issue #772 for more details.

Will also change `g2tmpl` back to `1.10.0` in the `module_base` files for Hera and Orion. The Jet `module_base` is still `1.10.0`.

Fixes #772

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

- [x] Forecast-only test on WCOSS-Dell (@RuiyuSun tested)

FYI @RuiyuSun @WenMeng-NOAA

### CODE REVIEW

File: modulefiles/module_base.wcoss_dell_p3.lua [hunk 1]
```diff
@@ -38,7 +38,7 @@ load(pathJoin("fms", "2021.03"))
 
 load(pathJoin("bacio", "2.4.1"))
 load(pathJoin("g2", "3.4.2"))
-load(pathJoin("g2tmpl", "1.10.1"))
+load(pathJoin("g2tmpl", "1.10.0"))
```
Comment (WalterKolczynski-NOAA) [inline modulefiles/module_base.wcoss_dell_p3.lua:41]: This should be changed for all the machines.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: modulefiles/module_base.wcoss_dell_p3.lua (hunk 1 above)
Comment (KateFriedman-NOAA) [reply modulefiles/module_base.wcoss_dell_p3.lua:41]: Done and committed at dac534d.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
