### PR TITLE
Fix post octal bugs

### LINKED ISSUE #1195: Potential octal bugs
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**
Numbers starting with "0" should almost a always be considered decimals.

**Current behavior**
At least one job, [the earc job](https://github.com/NOAA-EMC/global-workflow/blob/8581eacf1a26efba614a1c04715fbc24cb7ae858/scripts/exgdas_enkf_earc.sh#L51), does not specify that a number should be considered a decimal when performing math on it (in this case, dd and mm should be considered decimals when calculating nday, which results in octal errors when mm or dd are 08 or 09).

A similar bug can be found in scripts/exgfs_atmos_post.sh, lines [277, 297, 303, 310, 391, etc](https://github.com/NOAA-EMC/global-workflow/blob/8581eacf1a26efba614a1c04715fbc24cb7ae858/scripts/exgfs_atmos_post.sh#L277).

**Machines affected**
All

**To Reproduce**

Run a gdasearc0[1-8] job for a date in August or September.

**Additional Information**

I went searching through the global workflow scripts for other instances where this may possibly occur.  Places of interest include 

ush/tropcy_relocate_extrkr.sh:424
ush/getges.sh:1342-1350; ghm* and ghp* are set to fhm* and fhp*, which could be 08 or 09.  Thus something like [[ $ghm6 -lt 100 ]] could cause issues.
ush/fv3gfs_downstream_nems.sh:242, 270
scripts/exgfs_pmgr.sh: 28, 32, 34, 47
scripts/exgfs_prdgen_manager.sh: 19, 27, 29, 32, 47 (if reinstated)
scripts/exglobal_atmos_pmgr.sh (as above)
~scripts/exgfs_atmos_postsnd.sh: 81, 88, 111~ Fixed by #1212
scripts/exgdas_atmos_nawips.sh: 72

**Possible Implementation**

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
Yet more base bugs were found in post. To eliminate these once and for all, `fhr` is changed to have no leading zeros, and places where the zero-padded string is needed now use `fhr3`.

Resolves #1195

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Cycled test on Orion

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: scripts/exgfs_atmos_post.sh [hunk 1]
```diff
@@ -396,16 +397,15 @@ else   ## not_anl if_stime
         SPECIALFL="${PREFIX}special.grb2"
         SPECIALFLIDX="${PREFIX}special.grb2i"
       fi
-      fhr3=${fhr}
 
       if [[ "${SENDCOM}" = "YES" ]]; then
         #       echo "$PDY$cyc$pad$fhr" > $COMOUT/${RUN}.t${cyc}z.master.control
```
Comment (DavidHuber-NOAA) [inline scripts/exgfs_atmos_post.sh]: Will there be a need for this line in the future?  If so, then perhaps they should be changed to `${fhr3}` to avoid issues at a later time.  If not, then should these lines just be deleted?

File: ush/gfs_transfer.sh
Comment (DavidHuber-NOAA) [inline ush/gfs_transfer.sh:1]: There are several instances here of commented out code referencing filenames with `${fhr}` in them.  If this code comes back to life, this will need to be changed to `${fhr3}`.  Should these be updated now or the commented code deleted?

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
This looks pretty good.  I just wonder if the commented code should also be treated (or deleted).

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good to me, thanks @WalterKolczynski-NOAA !

**Comment by TerrenceMcGuinness-NOAA** [comment]
Walter needs to merge develop into his hotfix branch for CI to work as this fix was just a tad behind.

**Review by jkhender — APPROVED** [review]

File: scripts/exgfs_atmos_post.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply scripts/exgfs_atmos_post.sh:402]: fhr3 is already the loop variable (the zero-padded one).

Comment (WalterKolczynski-NOAA) [reply scripts/exgfs_atmos_post.sh]: Removed.

File: ush/gfs_transfer.sh
Comment (WalterKolczynski-NOAA) [reply ush/gfs_transfer.sh:1]: I checked the ops branch and these lines are all commented out there as well, so I just removed them.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Looks like you guys should know what to do about this one ...

```
+ forecast_postdet.sh[906]: echo 'Link CICE ICs'
Link CICE ICs
+ forecast_postdet.sh[907]: cice_restart_file=/work2/noaa/stmp/GFS_CI_ROOT/PR/1859/RUNTESTS/COMROT/C48_S2SA_gefs_3f8ebcec/gefs.20210323/06/mem000/model_data/ice/restart/20210323.120000.cice_model.res.nc
+ forecast_postdet.sh[908]: [[ ! -f /work2/noaa/stmp/GFS_CI_ROOT/PR/1859/RUNTESTS/COMROT/C48_S2SA_gefs_3f8ebcec/gefs.20210323/06/mem000/model_data/ice/restart/20210323.120000.cice_model.res.nc ]]
+ forecast_postdet.sh[909]: echo 'FATAL ERROR: CICE restart file not found at '\''/work2/noaa/stmp/GFS_CI_ROOT/PR/1859/RUNTESTS/COMROT/C48_S2SA_gefs_3f8ebcec/gefs.20210323/06/mem000/model_data/ice/restart/20210323.120000.cice_model.res.nc'\'', ABORT!'
FATAL ERROR: CICE restart file not found at '/work2/noaa/stmp/GFS_CI_ROOT/PR/1859/RUNTESTS/COMROT/C48_S2SA_gefs_3f8ebcec/gefs.20210323/06/mem000/model_data/ice/restart/20210323.120000.cice_model.res.nc', ABORT!
+ forecast_postdet.sh[910]: exit 112
+ forecast_postdet.sh[1]: postamble exglobal_forecast.sh 1694719232 112
+ preamble.sh[68]: set +x
End exglobal_forecast.sh at 19:20:37 with error code 112 (time elapsed: 00:00:05)
+ JGLOBAL_FORECAST[1]: postamble JGLOBAL_FORECAST 1694719228 112
+ preamble.sh[68]: set +x
End JGLOBAL_FORECAST at 19:20:37 with error code 112 (time elapsed: 00:00:09)
+ fcst.sh[1]: postamble fcst.sh 1694719226 112
+ preamble.sh[68]: set +x
End fcst.sh at 19:20:37 with error code 112 (time elapsed: 00:00:11)
```

**Review by DavidHuber-NOAA — APPROVED** [review]

**Comment by TerrenceMcGuinness-NOAA** [comment]
```
Begin fcst.sh at Fri Sep 15 18:25:22 UTC 2023
+ fcst.sh[12]: source /work2/noaa/stmp/GFS_CI_ROOT/PR/1862/global-workflow/ush/detect_machine.sh
++ detect_machine.sh[4]: case $(hostname -f) in
+++ detect_machine.sh[4]: hostname -f
++ detect_machine.sh[38]: MACHINE_ID=UNKNOWN
++ detect_machine.sh[41]: [[ UNKNOWN == \U\N\K\N\O\W\N ]]
++ detect_machine.sh[42]: case ${PW_CSP:-} in
++ detect_machine.sh[44]: PW_CSP=UNKNOWN
++ detect_machine.sh[49]: MACHINE_ID=UNKNOWN
++ detect_machine.sh[52]: [[ UNKNOWN != \U\N\K\N\O\W\N ]]
++ detect_machine.sh[57]: [[ -d /lfs/f1 ]]
++ detect_machine.sh[60]: [[ -d /mnt/lfs1 ]]
++ detect_machine.sh[63]: [[ -d /scratch1 ]]
++ detect_machine.sh[66]: [[ -d /work ]]
++ detect_machine.sh[68]: MACHINE_ID=orion
+ fcst.sh[13]: set +x
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.
sh: line 1: 209780 Aborted                 /bin/lua /apps/lmod/lmod/libexec/lmod bash --regexp --no_redirect --spider_timeout 2.0 spider '^prod_util$' 2> /dev/null
sh: line 1: 209783 Aborted                 /bin/lua /apps/lmod/lmod/libexec/lmod bash --regexp --no_redirect --spider_timeout 2.0 spider '^prod_util$' 2> /dev/null
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "prod_util"
   Try: "module spider prod_util" to see how to load the module(s).

End fcst.sh at 18:25:26 with error code 1 (time elapsed: 00:00:04)
```
