### PR TITLE
Fix error log parsing in compute build CI

### LINKED ISSUE #3296: Jenkins pipeline does not fail when build_compute.sh all fails
### What is wrong?

When there is a fail on a compute build job in the pipeline it should flag the CI as a fail and capture any appropriate log files as it did before compute builds.

### What should have happened?

We should get an Fail label on the PR when a CI tests fails build, specifically a compute build as jobs.

### What machines are impacted?

Hera, Orion, Hercules

### What global-workflow hash are you using?

develop

### Steps to reproduce

Already reproduced on build when it timed out 

### Additional information

_No response_

### Do you have a proposed solution?

Update the pipeline code with a try block in just the right place

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This PR adds a new feature to capture and report which compute builds failed when running CI.

Resolves #3296 
# Type of change
- [x] New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?
- [x] CI on Hercules

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my code, including function, input, and output descriptions
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] This change is covered by an existing CI test or a new one has been added

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
Running CI on Hercules to test the new feature.

**Comment by DavidHuber-NOAA** [comment]
Testing on Hercules shows that these changes successfully triggers the creation of a gist with the failed log file.  Marking this PR as ready for review.

**Review by TerrenceMcGuinness-NOAA — APPROVED** [review]
Yes I saw the error logs showed up and got stored in the Jenkins Artifacts, saved of the main log file to the records repo, and created the gist to boot. And now works in concert with the updates that also catch the case where there are no logs.  Looks great!

File: sorc/build_compute.sh [hunk 1]
```diff
@@ -100,13 +100,29 @@ while [[ "${finished}" == "false" ]]; do
...
+         # Skip the first two lines (header)
+         if [[ ${line_number} -lt 3 ]]; then
+            continue
+         fi
+
+         if [[ "${line}" =~ "DEAD" || "${line}" =~ "UNKNOWN" ||
+               "${line}" =~ "UNAVAILABLE" || "${line}" =~ "FAIL" ]]; then
+            job=$(echo "${line}" | awk '{ print $2 }')
+            log_file="logs/${job}.log"
+            echo "${log_file}" >> logs/error.logs
```
Comment (WalterKolczynski-NOAA) [inline sorc/build_compute.sh:121]: Now that we're identifying which build(s) failed, can we upload a gist like we do with other failures?

Comment (DavidHuber-NOAA) [reply sorc/build_compute.sh:121]: Yes, no code changes in the Jenkinsfile were necessary to accomplish this.  This is the message/gist from the test run: https://github.com/NOAA-EMC/global-workflow/pull/3301#issuecomment-2636980839.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
