### PR TITLE
Convert archive jobs to proper j-jobs

### LINKED ISSUE #1051: Merge ecflow workflow archive jobs back to global workflow
There is an architecture redesign for archive jobs running on ecflow workflow used for GFS v16.3 retro and realtime parallel. The solution was developed due to the new WCOSS2 environment. 

The WCOSS2 HPSS transfer jobs environment often have the following conditions:
(1) Network transfer speed slowness.
(2) Developer dev transfer jobs priority turned to low situational.
(3) Transfer jobs become zombies after submit.
(4) Transfer jobs cutoff by HPSS server due to low transfer rate. 

The redesigned archive jobs provide the following benefits to the workflow:
(1) It removed the dependency hold on cycle proceeding. Allow workflow to continue the process into the next cycle.
(2) It only transfers one tarball at a time for each job.
(3) Increase chance of success in transfer.
(4) Allow manageable rerun/recovery when job fails, system issue, HPSS unavailable.
(5) Remove the need to unconditionally retransfer tar balls completed from the prior transfer attempt.
(6) Better error recovery with exception handling.

Architecture and Components
 ${HOMEgfs}/ecf/setup_ecf_links.sh
   This slink script was modified to do slink for earc jobs
 ${HOMEgfs}/ecf/scripts/workflow_manager/cycled/gfs/jgfs_emc_arch.ecf
   A job using dev queue that allow the workflow to proceed due to the event QUEUE_ARCH is unavailable, full or slowness
   Create and execute gfs_${CDATE}_archive_list.sh dynamically to copy job log files for the CDATE to a archive enabled log directory
   Calling J-Job JGLOBAL_OFFLINE_ARCHIVE
 ${HOMEgfs}/ecf/scripts/workflow_manager/cycled/gdas/jgdas_emc_arch.ecf
   A job using dev queue that allow the workflow to proceed due to the event QUEUE_ARCH is unavailable, full or slowness
   Create and execute gfs_${CDATE}_archive_list.sh dynamically to copy job log files for the CDATE to a archive enabled log directory
   Calling J-Job JGLOBAL_OFFLINE_ARCHIVE
 ${HOMEgfs}/ecf/scripts/workflow_manager/cycled/enkfgdas/jenkfgdas_emc_earc_master.ecf
   A job using dev queue that allow the workflow to proceed due to the event QUEUE_ARCH is unavailable, full or slowness
   Create and execute gfs_${CDATE}_archive_list.sh dynamically to copy job log files for the CDATE to a archive enabled log directory
   Calling J-Job JENKFGDAS_OFFLINE_ARCHIVE
   Same job process nine groups of earc
 ${HOMEgfs}/ecf/scripts/workflow_manager/jobs/JGLOBAL_OFFLINE_ARCHIVE
   Process normal archive work for both GDAS and GFS archive jobs
   Calling hpssarch_gen.sh for dynamically generate archive target file list
   Calling hpss_global_archive_driver.sh for dynamically create tarball archive jobs
 ${HOMEgfs}/ecf/scripts/workflow_manager/jobs/JENKFGDAS_OFFLINE_ARCHIVE
   Process normal archive work for both ENKFGDAS earc archive jobs for all groups
   Calling hpssarch_gen.sh for dynamically generate archive target file list
   Calling hpss_global_archive_driver.sh for dynamically create tarball archive jobs
 ${HOMEgfs}/ecf/scripts/workflow_manager/scripts/hpss_global_archive_driver.sh
   Configure jobs dependency
   Calling python utility hpss_global_archive.py to dynamically create archive jobs
 ${HOMEgfs}/ecf/scripts/workflow_manager/scripts/hpss_global_archive.py
   A python program that dynamically creates a transfer job, submit, and  upload file to hpss.

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
This PR is to update the archive jobs using *arc*.sh, j-job, ex-script approach similar style to the package format.
- The rocoto workflow task job script arch.sh earc.sh in $HOMEgfs/jobs/rocoto are updated to adopt workflow style.
- Introduce archive J-Jobs in $HOMEgfs/jobs with J-Job style.
- Introduce archive ex-scripts in $HOMEgfs/scripts to perform task works that is in-line with the rest of the workflow.

Fixes #1051
Refs: #720

**How Has This Been Tested?**
C192C96 cycled run tested on Cactus

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

File: jobs/JENKFGDAS_ARCHIVE [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+export pgmerr=errfile
+
+
+##############################################
+# Set variables used in the script
+##############################################
+export CDATE=${CDATE:-${PDY}${cyc}}
+export CDUMP=${CDUMP:-${RUN:-"gfs"}}
+export COMPONENT=${COMPONENT:-atmos}
+export n=$((ENSGRP))
```
Comment (aerorahul) [inline jobs/JENKFGDAS_ARCHIVE]: In `develop`, this is: 
```suggestion
export n=$((10#${ENSGRP}))
```

Comment (aerorahul) [reply jobs/JENKFGDAS_ARCHIVE]: Please move this line into `exgdas_enkf_earc.sh` and drop the `export`.

File: jobs/JENKFGDAS_ARCHIVE [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+##############################################
+export pgmout="OUTPUT.${pid}"
+export pgmerr=errfile
+
+
+##############################################
+# Set variables used in the script
+##############################################
+export CDATE=${CDATE:-${PDY}${cyc}}
+export CDUMP=${CDUMP:-${RUN:-"gfs"}}
```
Comment (aerorahul) [inline jobs/JENKFGDAS_ARCHIVE]:
```suggestion
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
```

File: jobs/JENKFGDAS_ARCHIVE [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+##############################################
+# Begin JOB SPECIFIC work
+##############################################
+
+# ICS are restarts and always lag INC by $assim_freq hours.
+export EARCINC_CYC=${ARCH_CYC}
+export EARCICS_CYC=$((ARCH_CYC-assim_freq))
+if [ ${EARCICS_CYC} -lt 0 ]; then
+  export EARCICS_CYC=$((EARCICS_CYC+24))
+fi
```
Comment (aerorahul) [inline jobs/JENKFGDAS_ARCHIVE]: Please move these to `exgdas_enkf_earc.sh` and drop the `export`

File: jobs/JENKFGDAS_ARCHIVE [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+
+# EnKF update in GFS, GDAS or both
+export CDUMP_ENKF=$(echo ${EUPD_CYC:-"gdas"} | tr a-z A-Z)
+
+export ARCH_LIST="${ROTDIR}/enkf${CDUMP}.${PDY}/${cyc}/${COMPONENT}/earc${ENSGRP}"
```
Comment (aerorahul) [inline jobs/JENKFGDAS_ARCHIVE]: This belongs to `exgdas_enkf_earc.sh` and is there.

File: scripts/exgdas_enkf_earc.sh [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+## Ensemble archive driver script
+## RUN_ENVIR : runtime environment (emc | nco)
+## HOMEgfs   : /full/path/to/workflow
+## EXPDIR : /full/path/to/config/files
+## CDATE  : current analysis date (YYYYMMDDHH)
+## PDY    : current date (YYYYMMDD)
+## cyc    : current cycle (HH)
+## CDUMP  : cycle name (gdas / gfs)
+## ENSGRP : ensemble sub-group to archive (0, 1, 2, ...)
+###############################################################
```
Comment (aerorahul) [inline scripts/exgdas_enkf_earc.sh]: You may drop these lines.

File: scripts/exgdas_enkf_earc.sh [hunk 6]
```diff
@@ -0,0 +1,202 @@
...
+
+export ARCH_LIST=${ARCH_LIST:-$ROTDIR/enkf${CDUMP}.$PDY/$cyc/$COMPONENT/earc$ENSGRP}
```
Comment (aerorahul) [inline scripts/exgdas_enkf_earc.sh]: See comments in `JENKFGDAS_ARCHIVE`

File: jobs/JENKFGDAS_ARCHIVE [hunk 7]
```diff
@@ -0,0 +1,91 @@
+#! /usr/bin/env bash
+
+source "$HOMEgfs/ush/preamble.sh"
+
+#############################
+# Source relevant config files
+#############################
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
+configs="base earc"
+config_path=${EXPDIR:-${NWROOT}/gfs.${gfs_ver}/parm/config}
```
Comment (aerorahul) [inline jobs/JENKFGDAS_ARCHIVE]:
```suggestion
config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
```

File: jobs/JGLOBAL_ARCHIVE [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+. $HOMEgfs/env/${machine}.env arch
+status=$?
+[[ $status -ne 0 ]] && exit $status
+
+#############################################
+# Source workflow level common utilities
+#############################################
+#### This utility is under development as of 20221020
+####   will not use it at this time
+#### source "${HOMEgfs}/ush/file_utils.sh"
```
Comment (aerorahul) [inline jobs/JGLOBAL_ARCHIVE]: Please delete.
These are being sourced and used in `exglobal_archive.sh`

File: jobs/JGLOBAL_ARCHIVE [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+
+# CURRENT CYCLE
+export APREFIX="${CDUMP}.t${cyc}z."
+export ASUFFIX=${ASUFFIX:-$SUFFIX}
+
+if [ $ASUFFIX = ".nc" ]; then
+   format="netcdf"
+else
+   format="nemsio"
+fi
```
Comment (aerorahul) [inline jobs/JGLOBAL_ARCHIVE]: Please move these to `exglobal_archive.sh` and drop the `export`

File: scripts/exglobal_archive.sh [hunk 10]
```diff
@@ -0,0 +1,379 @@
...
+## Abstract:
+## Archive driver script
+## RUN_ENVIR : runtime environment (emc | nco)
+## HOMEgfs   : /full/path/to/workflow
+## EXPDIR : /full/path/to/config/files
+## CDATE  : current analysis date (YYYYMMDDHH)
+## CDUMP  : cycle name (gdas / gfs)
+## PDY    : current date (YYYYMMDD)
+## cyc    : current cycle (HH)
+###############################################################
```
Comment (aerorahul) [inline scripts/exglobal_archive.sh]: You may drop these lines.

File: scripts/exglobal_archive.sh [hunk 11]
```diff
@@ -0,0 +1,379 @@
...
+
```
Comment (aerorahul) [inline scripts/exglobal_archive.sh:25]: Please see comments in `JGLOBAL_ARCHIVE` about moving lines from there to here.

**Review by aerorahul — COMMENTED** [review]
Overall the changes are what they are supposed to do.  
Pending a few comments to move specific lines from J-Job to exscript, this should be ready for `develop`.

File: jobs/JENKFGDAS_ARCHIVE (hunk 1 above)
Comment (lgannoaa) [reply jobs/JENKFGDAS_ARCHIVE]: This variable is used by hpssarch_gen.sh. Therefore will keep the export.

**Comment by lgannoaa** [comment]
@aerorahul, recommended changes have been made.

**Review by aerorahul — APPROVED** [review]
Changes look good.
Pending fixing the warnings, and a successful test and review from the other reviewers, this can be merged.

File: jobs/JENKFGDAS_ARCHIVE (hunk 1 above)
Comment (aerorahul) [reply jobs/JENKFGDAS_ARCHIVE]: Ok. 
From what I can tell, the variable in `hpssarch_gen.sh` is initializing from `n=1` and not really using this variable.
Anyways, you can leave it for another time.

File: jobs/JENKFGDAS_ARCHIVE [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+
+echo "ENDED NORMALLY."
+
+##########################################
+# Remove the Temporary working directory
+##########################################
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf $DATA
+
+date
```
Comment (WalterKolczynski-NOAA) [inline jobs/JENKFGDAS_ARCHIVE]: There's no need to call `date` at the end of the script. It will automatically be included when the script exits.

File: jobs/JGLOBAL_ARCHIVE [hunk 13]
```diff
@@ -0,0 +1,98 @@
...
+
+echo "ENDED NORMALLY."
+
+##########################################
+# Remove the Temporary working directory
+##########################################
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf $DATA
+
+date
```
Comment (WalterKolczynski-NOAA) [inline jobs/JGLOBAL_ARCHIVE]: Same as before; no need for `date`.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]
I'm assuming the code in the new exscripts is just what was in the rocoto script before, so I'm not going to pick it apart here.

File: jobs/JENKFGDAS_ARCHIVE (hunk 12 above)
Comment (lgannoaa) [reply jobs/JENKFGDAS_ARCHIVE]: Removed

File: jobs/JGLOBAL_ARCHIVE (hunk 13 above)
Comment (lgannoaa) [reply jobs/JGLOBAL_ARCHIVE]: Removed

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending linter fixes and final testing.

**Comment by lgannoaa** [comment]
Tested in Cactus with C192C96 cycled run. Job completed.

**Comment by WalterKolczynski-NOAA** [comment]
> Tested in Cactus with C192C96 cycled run. Job completed.

Please make sure you also test coupled, since it creates a different set of archive files. Coupled isn't fully working on WCOSS2 yet, so you'll have to use an RDHPCS machine.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA Some of the shellcheck suggestions are likely out of scope from this PR e.g. `tr` since we are just moving code around.  Do we need to address those as well?

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA Some of the shellcheck suggestions are likely out of scope from this PR e.g. `tr` since we are just moving code around. Do we need to address those as well?

Since this is shifting code around, just leave them. We'll take care of them later.

**Comment by lgannoaa** [comment]
The C384 ATM fcst only test on Hera completed. The Hera space is too low for ATMW cycled test. Will proceed that test on wcoss.
The COM for C384 ATM fcst only test on Hera will be removed at noon today 11/18/22 to release some space.

**Comment by lgannoaa** [comment]
C768C384 ATMW couple cycled test executed on wcoss2. All jobs completed as expected.
@aerorahul @WalterKolczynski-NOAA let me know if you have any questions.

**Comment by WalterKolczynski-NOAA** [comment]
Still needs a full coupled S2SWA test. It will have to be run on an RDHPCS machine because it won't work on WCOSS2 yet. Workflow will automatically get the (C384) ICs for you. Use 2013040100.

**Comment by lgannoaa** [comment]
Full coupled S2SWA fcst only test on Orion is done with gfsarch job status completed. 
log: /work/noaa/stmp/lgan/comrot/s2swa_arch_orion/logs/2013040100
