### PR TITLE
Stop checking for restarts on non-GFS CDUMPs

### LINKED ISSUE #1140: Unbound variable (RSTDIR_ATM) in forecast_det.sh (minor bug)
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**

FV3_GFS_det should run without error when called during gdasfcst jobs.  `RSTDIR_ATM` is only a required variable for gfsfcst jobs (set in [forecast_predet.sh:212](https://github.com/NOAA-EMC/global-workflow/blob/e2c29749ffe4050ce4e0273ef4802b8458bbc59c/ush/forecast_predet.sh#L212)) and should not be referenced.

**Current behavior**

`RSTDIR_ATM` is referenced during both gdas and gfs fcst steps, resulting in an unbound error at [forecast_det.sh:43](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_det.sh#L43) during gdasfcst.  It appears that this unbound error only affects the `find` command within the command substitution and so flow continues with `filecount=0`, which does not affect on the remainder of the function.  I'm not sure if this is the usual/constant behavior when `set -u` is toggled.

**Machines affected**

Found on Google Cloud.

**To Reproduce**

Run a gdasfcst job and check the resulting log.

**Possible Implementation**

Replace
`filecount=$(find $RSTDIR_ATM -type f | wc -l)`
with
`[[ $CDUMP = "gfs" ]] && filecount=$(find $RSTDIR_ATM -type f | wc -l)`
or
remove `$CDUMP = "gfs"` from the proceeding `if` and move the `filecount` assignment and the proceeding `if` into a new `if [ $CDUMP = "gfs" ]; then` block.

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
The forecast was attempting to check `RSTDIR_ATM` for restart files, but that variable is not defined for gdas, resulting in an unbound variable error. Because the error occurred in a subshell, the error had no impact on the execution, just an unwanted error message in the log. Now that directory is only checked when the `$CDUMP` is 'gfs'.

Also fixes some linter warnings.

Fixes #1140 

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Forecast-only test on Hera
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

### CODE REVIEW

File: ush/forecast_det.sh [hunk 1]
```diff
@@ -19,55 +19,55 @@ FV3_GFS_det(){
   res_latlon_dynamics="''"
 
   # Determine if this is a warm start or cold start
-  if [ -f $gmemdir/RESTART/${sPDY}.${scyc}0000.coupler.res ]; then
+  if [[ -f "${gmemdir}"/RESTART/"${sPDY}"."${scyc}"0000.coupler.res ]]; then
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_det.sh]: Please quote the entire path and not each individual variable.

File: ush/forecast_det.sh [hunk 2]
```diff
@@ -19,55 +19,55 @@ FV3_GFS_det(){
...
+      flag2=${RSTDIR_ATM}/coupler.res
 
       #make sure that the wave restart files also exist if cplwav=true
       waverstok=".true."
-      if [ $cplwav = ".true." ]; then
-        for wavGRD in $waveGRD ; do
-          if [ ! -f ${RSTDIR_WAVE}/${PDYS}.${cycs}0000.restart.${wavGRD} ]; then
+      if [[ "${cplwav}" = ".true." ]]; then
+        for wavGRD in ${waveGRD} ; do
+          if [[ ! -f "${RSTDIR_WAVE}"/"${PDYS}"."${cycs}"0000.restart."${wavGRD}" ]]; then
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_det.sh]: Same here. Please quote the entire path.

File: ush/forecast_det.sh [hunk 3]
```diff
@@ -19,55 +19,55 @@ FV3_GFS_det(){
...
 
-      if [ -s $flag1 -a $waverstok = ".true." ]; then
-        CDATE_RST=$SDATE
-        [[ $RERUN = "YES" ]] && break
-        mv $flag1 ${flag1}.old
-        if [ -s $flag2 ]; then mv $flag2 ${flag2}.old ;fi
+      if [[ -s "${flag1}" ]] && [[ ${waverstok} = ".true." ]]; then
+        CDATE_RST=${SDATE}
+        [[ ${RERUN} = "YES" ]] && break
+        mv "${flag1}" "${flag1}".old
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_det.sh]: And here. Should be `mv "${flag1}" "${flag1}.old"`

File: ush/forecast_det.sh [hunk 4]
```diff
@@ -19,55 +19,55 @@ FV3_GFS_det(){
...
+        if [[ -s "${flag2}" ]]; then mv "${flag2}" "${flag2}".old ;fi
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_det.sh]: And here

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]
I know this is how shellcheck "fixes" missing quote strings automatically, but the results are ugly and more difficult to read. It is suggested you fix these warnings manually by quoting entire strings ("canonical" quoting). Just make sure you don't accidentally include any spaces within the quotes that would unintentionally combine multiple arguments into one. We have a feature request in with shellcheck to provide the option of using canonical quotes, but in the meantime we need to do it manually.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
