### PR TITLE
Hack UPP version

### LINKED ISSUE #2041: UPP fails to build on orion
### What is wrong?

There's an issue with the jasper module when trying to build UPP on orion with develop.  See log: 

/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/logs/build_upp.log
```
+ cd ufs_model.fd/FV3/upp/tests
+ ./compile_upp.sh
Machine:  orion
Building for machine orion, compiler intel
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "jasper/2.0.25"
   Try: "module spider jasper/2.0.25" to see how to load the module(s).

Executing this command requires loading "jasper/2.0.25" which failed while
processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    orion            /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles/orion.lua

```

### What should have happened?

UPP should build successfully in develop on orion.   

Not sure if there's some new module issue as it says build completed on the last PR to g-w: 
https://github.com/NOAA-EMC/global-workflow/pull/1989#issuecomment-1796975381

### What machines are impacted?

Orion

### Steps to reproduce

git clone g-w 
cd g-w 
cd sorc 
sh checkout.sh 
sh build_all.sh 

### Additional information

```
$ module use /work2/noaa/marine/jmeixner/HR3/unstruc/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles
$ module load orion
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as
requested: "jasper/2.0.25"
   Try: "module spider jasper/2.0.25" to see how to load the module(s).

Executing this command requires loading "jasper/2.0.25" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    orion            /work2/noaa/marine/jmeixner/HR3/unstruc/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles/orion.lua


$ module spider jasper/2.0.25

----------------------------------------------------------------------------------------------------------------------
  jasper: jasper/2.0.25
----------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "jasper/2.0.25" module is available to load.

      intel/2022.1.2
```
 

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
The stack UPP was using on Orion was recently deleted, leaving us unable to build the UFS version of UPP there. UPP has an updated version using spack-stack that works, so the checkout script is modified to check out that version of UPP after UFS has been checked out.

This temporary hack can be removed once we move to a UFS version that advances the UPP version to or beyond 78f369b.

Resolves #2041

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Build on Orion

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: sorc/checkout.sh [hunk 1]
```diff
@@ -177,6 +177,13 @@ for checkout_pid in $(jobs -p); do
   wait "${checkout_pid}" || errs=$((errs + $?))
 done
 
+# Temporary hack to check out a UPP verison that works on Orion
+# This can be removed once the UFS UPP version advances to or beyond 78f369b
+cd "${topdir}/ufs_model.fd/FV3/upp" || exit 1
+git checkout 78f369b
+cd "${topdir}" || exit 1
+# End hack
+
```
Comment (aerorahul) [inline sorc/checkout.sh:186]: What happens to the ufs-weather-model build if you use this UPP hash.
A better solution would be to checkout the orion module file for this hash alone
something like:
```
cd "${topdir}/ufs_model.fd/FV3/upp"
git checkout 78f369b modulefile_for_orion
```

Comment (WalterKolczynski-NOAA) [reply sorc/checkout.sh:186]: I built the whole system with this hack and UFS builds fine. I can try a more targeted option but:
- it will be more than one file, because UPP has moved to a machine + common approach like UFS
- I am worried about API mismatches if the module versions have changed (though those should be evident during a build)

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA @JessicaMeixner-NOAA I have the UPP related update combined in Dusan's fv3atm PR NOAA-EMC/fv3atm#713. I have been asking him to upgrade upp submodule to 78f369b.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
@WenMeng-NOAA Thanks for the update. Once that works its way up to UFS, we'll be able to take this hack out.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA - thanks for all of your work towards finding a quick work around for this.   It looks like the PR that @WenMeng-NOAA mentioned is being tested today based on the [commit queue](https://github.com/ufs-community/ufs-weather-model/wiki/Commit-Queue).    If that's true, maybe it's worth waiting a day and then updating all the way to the top of ufs-weather-model?   There will be multiple updates that need to be made, the ones in https://github.com/NOAA-EMC/global-workflow/pull/1987 that have the other model updates for the hash behind where g-w develop is now pointing to, updates for prod-util -> prod_util with the move to spack stack 1.5 in the hash after where g-w is now pointing to and then updates described in https://github.com/NOAA-EMC/global-workflow/issues/1942), but then we'd be able to have cleaned tagged versions for upcoming HR3 (and potentially EP5 - tagging @NeilBarton-NOAA @bingfu-NOAA for awareness).  Thoughts?

**Comment by WalterKolczynski-NOAA** [comment]
I'm inclined to get this fix in, especially if the UFS update is going to take additional work, as it is blocking running on Orion. It is a simple fix to remove again once we have a suitable UFS version.

**Review by DavidHuber-NOAA — APPROVED** [review]
I ran 2 24-hour forecast-only S2SA experiments (develop and this branch) and compared archived grib2 files (`fix_upp_ff` vs `dev_upp_ff` in `/scratch1/NCEPDEV/global/David.Huber/archive`).  All files were bitwise identical.

**Comment by WalterKolczynski-NOAA** [comment]
@DavidHuber-NOAA Thanks for the test. Going to run it through just the build portion of the CI and then get this in.
