### PR TITLE
Link `upp.fd` Before Referencing Its Files in Workflow Setup

### LINKED ISSUE #4396: files linked to sorc/upp.fd before sorc/upp.fd created
### What is wrong?

`sorc/link_workflow.sh` creates links pointing at `sorc/upp.fd` **_before_** the link for `sorc/upp.fd` is created.

```
151:${LINK_OR_COPY} "${HOMEgfs}/sorc/upp.fd/parm/params_grib2_tbl_new" .
152:${LINK_OR_COPY} "${HOMEgfs}/sorc/upp.fd/fix/nam_micro_lookup.dat" .
155:    ${LINK_OR_COPY} "${HOMEgfs}/sorc/upp.fd/parm/${dir}" .
161:    ${LINK_OR_COPY} "${HOMEgfs}/sorc/upp.fd/fix/chem/${file}" .
397:${LINK_OR_COPY} "${HOMEgfs}/sorc/upp.fd/exec/upp.x" .
463:    if [[ -d upp.fd ]]; then
464:        rm -rf upp.fd
466:    ${LINK} ufs_model.fd/UFSATM/upp upp.fd
``` 

This is unsafe.  If `link_workflow.sh` fails before line 466 is executed, the preceding links are invalid.

### What should have happened?

All links created by `sorc/link_workfow.sh` should be valid links.

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

2596d2a

### Steps to reproduce

1. clone g-w `develop`
2. execute `sorc/build_compute.sh` for all components
3. modify `link_workflow.sh` such that it fails before the `sorc/upp.fd` link is created
4. execute `link_workflow.sh`.  It aborts at the failure point you created
5. check the link `$HOMEgfs/parm/post/params_grib2_tbl_new`.  This will be a dead link.

### Additional information

This issue was stumbled upon while testing GDASApp PR [#2025](https://github.com/NOAA-EMC/GDASApp/pull/2025).

### Do you have a proposed solution?

Refactor `link_workflow.sh` such that the `sorc/upp.fd` link is created before links pointing at files in `sorc/upp.fd` are created.

### PR DESCRIPTION
**Pull request by AntonMFernando-NOAA**
# Description

- Moves the creation of the `upp.fd` link earlier in link_workflow.sh to ensure it exists before any files within it are referenced or linked. 
- This prevents missing file errors during workflow setup. Uses a subshell for cleaner directory handling.

  Resolves #4396  

# Type of change
- [ ] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [x] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this change expected to change outputs (e.g. value changes to existing outputs, new files stored in COM, files removed from COM, filename changes, additions/subtractions to archives)? YES/NO (If YES, please indicate to which system(s))
  - [ ] GFS
  - [ ] GEFS
  - [ ] SFS
  - [ ] GCAFS
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?
- Build and link on `hera` successfully  

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

File: sorc/link_workflow.sh [hunk 1]
```diff
@@ -140,6 +140,19 @@ if [[ "${LINK_NEST:-OFF}" == "ON" ]]; then
...
+#---------------------------------------
+(
+    cd "${HOMEgfs}/sorc" || exit 8
+    if [[ -d ufs_model.fd ]]; then
+        if [[ -d upp.fd ]]; then
+            rm -rf upp.fd
+        fi
+        ${LINK} ufs_model.fd/UFSATM/upp upp.fd
+    fi
+)
```
Comment (aerorahul) [inline sorc/link_workflow.sh]: Why the subshell?

Comment (AntonMFernando-NOAA) [reply sorc/link_workflow.sh]: @aerorahul Because the subshell keeps directory changes local?

Comment (aerorahul) [reply sorc/link_workflow.sh]: indeed.  excellent point.

**Review by aerorahul — DISMISSED** [review]
lgtm

**Review by DavidHuber-NOAA — APPROVED** [review]
