### PR TITLE
Restore cycling capability

### LINKED ISSUE #711: Restore cycled capability in develop
The recent update to develop with prototype 8b support broke cycled capability due to changing the default options for some physics options.

**Expected behavior**
Cycled mode should perform as it used to before the 8b merge

**Current behavior**
Cycled mode does not complete correctly

**Machines affected**
All

**To Reproduce**
Try to run the current develop in cycled mode

**Context**
The decision was made to merge the prototype updates so that prototype experiments could begin, knowing it would temporarily disrupt cycled mode.

**Additional Information**
In the short-term, the goal is just to restore cycled capability using the previous physics options. Long-term the DA system would need to be updated to handle the final physics package.

**Possible Implementation**
The implementation of case files (Issue #710) will allow the restoration of cycled capability by allowing for the convenient switching between different sets of physics for different applications.

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
Restores the ability to run in cycled mode. This requires GSI to be built with ncio/1.1.2, so the build script now sets 1.1.2 as the ncio version until either the GSI default version is updated or module version files are added to global-workflow (Issue #671).
    
Two new variables, COMIN_OBS and COMIN_GES_OBS, had to be added to the config file in the wake of GSI updates for WCOSS2 to ensure the correct paths are used instead of trying to use the non-functional compath.py.
    
Note that, for now, in order to use cycling, **the microphysics setting (imp_physics) must be changed** in config.base from Thompson (8) back to GFDL (11), along with a **corresponding CCPP suite** (like FV3_GFS_v16).

Fixes #711

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

**How Has This Been Tested?**
- [x] Cycled test on Hera
- [x] Coupled test on Hera
- [x] Cycled test on Orion
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

File: sorc/build_gsi.sh [hunk 1]
```diff
@@ -30,6 +30,9 @@ fi
 cd gsi.fd/ush/
 export GSI_MODE="GFS"
 export REGRESSION_TESTS="NO"
+# Temporary setting until GSI default is updated or workflow adds versions file
```
Comment (RussTreadon-NOAA) [inline sorc/build_gsi.sh:33]: add @MichaelLueken-NOAA for awareness

Comment (MichaelLueken) [reply sorc/build_gsi.sh:33]: @RussTreadon-NOAA Thanks for letting me know.

@WalterKolczynski-NOAA `ncio/1.1.2` still isn't available on WCOSS2 and the version of `ncio` in `modulefiles/gsi_common.lua` won't be updated until it is.

Comment (aerorahul) [reply sorc/build_gsi.sh:33]: @MichaelLueken-NOAA 
`ncio/1.1.2` is now available on WCOSS2 in the para space.
Here are the instructions to find them:
```
module purge;module reset
export HPC_OPT=/apps/ops/para/libs
module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304/
module use /apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7/
module load intel craype cray-mpich/8.1.7
module show ncio/1.1.2
```

We will need to find a way to ensure development continues without having to depend on updates to libraries to fall in their final place on WCOSS2.   Does that mean test them on Acorn where we have control over building and installing versions of updated libraries?
@arunchawla-NOAA @dtkleist

Comment (MichaelLueken) [reply sorc/build_gsi.sh:33]: @aerorahul
I added:

```
pushenv("HPC_OPT", "/apps/ops/para/libs")
prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304")
prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7/")
```

to `modulefiles/gsi_wcoss2.lua` and attempted to compile.  While `ncio/1.1.2` was found, the code failed to compile with the following:

```
CMake Error at src/gsi/CMakeLists.txt:68 (find_package):
  By not providing "Findnemsio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "nemsio", but
  CMake did not find one.
```

This is strange because `nemsio/2.5.2` was also found.  Also, the following printout shows that the modules were being loaded from para:

```
-- Found bacio: /apps/ops/para/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found sigio: /apps/ops/para/libs/intel/19.1.3.304/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Found sfcio: /apps/ops/para/libs/intel/19.1.3.304/sfcio/1.4.1/lib/libsfcio.a (found version "1.4.0")
```

rather than:

```
-- Found bacio: /apps/ops/prod/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found sigio: /apps/ops/prod/libs/intel/19.1.3.304/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Found sfcio: /apps/ops/prod/libs/intel/19.1.3.304/sfcio/1.4.1/lib/libsfcio.a (found version "1.4.0")
```

So, while `ncio/1.1.2` is available in para, the GSI won't compile when the modulefile has been updated to use modules from para.

While I certainly agree that development continues without needing to depend on updates to libraries to fall in their final place on WCOSS2, at least with respect to `ncio/1.1.2`, it seems that it will need to.

Comment (aerorahul) [reply sorc/build_gsi.sh:33]: @MichaelLueken-NOAA 
This worked for me on Cactus at `/lfs/h2/emc/stmp/rahul.mahajan/gsi`
```
12:53 $ git diff
diff --git i/modulefiles/gsi_wcoss2.lua w/modulefiles/gsi_wcoss2.lua
index 13894625..b97bbba7 100644
--- i/modulefiles/gsi_wcoss2.lua
+++ w/modulefiles/gsi_wcoss2.lua
@@ -19,5 +19,11 @@ load(pathJoin("python", python_ver))
 load(pathJoin("prod_util", prod_util_ver))
 
 load("gsi_common")
+unload("ncio")
+
+pushenv("HPC_OPT", "/apps/ops/para/libs")
+prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304")
+prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7/")
+load("ncio/1.1.2")
 
 whatis("Description: GSI environment on WCOSS2")
```

It built everything as expected.

Comment (WalterKolczynski-NOAA) [reply sorc/build_gsi.sh:33]: I'm not really worried about it right now. I know the GSI update is being held up by WCOSS2, but I have a work-around and develop of GW doesn't run on WCOSS2 right now anyway. Updating GW to run on WCOSS2 will include the introduction of the versions file, so we'll be setting the ncio version number then anyway.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Install `gsi_update_clean` on Orion.  Cold start C96/C48L127 parallel from 2021122018.   Run to 2021122006.  Test does not include gfs cycle at 00Z.   Test does not turn on waves.  Only DA (GSI & EnKF) jobs cycled.   All jobs ran to completion.   Output was not examined for correctness.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve pending acceptable behavior on various machines.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WalterKolczynski-NOAA !

**Comment by WalterKolczynski-NOAA** [comment]
> Approve pending acceptable behavior on various machines.

@RussTreadon-NOAA Are you running more tests, or just waiting for mine to complete (which they have)?

**Comment by RussTreadon-NOAA** [comment]
> > Approve pending acceptable behavior on various machines.
> 
> @RussTreadon-NOAA Are you running more tests, or just waiting for mine to complete (which they have)?

@WalterKolczynski-NOAA .  I am not running any more tests.   Kate and I approved earlier today.  Are you satisfied with the review and results?

**Comment by WalterKolczynski-NOAA** [comment]
> > > Approve pending acceptable behavior on various machines.
> > 
> > 
> > @RussTreadon-NOAA Are you running more tests, or just waiting for mine to complete (which they have)?
> 
> @WalterKolczynski-NOAA . I am not running any more tests. Kate and I approved earlier today. Are you satisfied with the review and results?

Yes, I just wanted to confirm before I merge.

File: sorc/build_gsi.sh (hunk 1 above)
Comment (MichaelLueken) [reply sorc/build_gsi.sh:33]: > @MichaelLueken-NOAA This worked for me on Cactus at `/lfs/h2/emc/stmp/rahul.mahajan/gsi`
> 
> ```
> 12:53 $ git diff
> diff --git i/modulefiles/gsi_wcoss2.lua w/modulefiles/gsi_wcoss2.lua
> index 13894625..b97bbba7 100644
> --- i/modulefiles/gsi_wcoss2.lua
> +++ w/modulefiles/gsi_wcoss2.lua
> @@ -19,5 +19,11 @@ load(pathJoin("python", python_ver))
>  load(pathJoin("prod_util", prod_util_ver))
>  
>  load("gsi_common")
> +unload("ncio")
> +
> +pushenv("HPC_OPT", "/apps/ops/para/libs")
> +prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304")
> +prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7/")
> +load("ncio/1.1.2")
>  
>  whatis("Description: GSI environment on WCOSS2")
> ```
> 
> It built everything as expected.

@aerorahul Thank you for looking into this.  The GSI was able to compile following what you have done.  I'll move forward with updating the GSI modulefiles to use ncio/1.1.2 now.
