### PR TITLE
Remove existing directory if it exists when getic runs

### LINKED ISSUE #1156: Error with getic task if ROTDIR directory not cleaned up
**Expected behavior**
User should not have to clean up $ROTDIR before running getic again after it fails

**Current behavior**
After I ran the getic task and it failed (see issue #1155), the job was resubmitted. The job gave an error when running the following statement.

` mv ${EXTRACT_DIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/* ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}
`

mv: cannot move <EXTRACT_DIR>/gfs.20221115/00/* to <ROT_DIR>/gfs.20221115/00/atmos': Directory not empty

**Machines affected**
All

**To Reproduce**
run getic.sh before fixing it for issue #1155 and then resubmit job

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
If getic is run with an existing `$ROTDIR` (possibly because it failed the first time), it would fail because the directory already exists. Now any existing directory is deleted before attempting to move the ICs.

Fixes #1156

**Type of change**

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
I don't think we want the job to fail if it exists, I think we just want it to overwrite. It already errors now (thanks to `set -e`).

Alternatively, just skip if all the files exists.

@KateFriedman-NOAA thoughts?

**Comment by KateFriedman-NOAA** [comment]
Agreed, don't want this job to fail if the files already exist. I could see either non-failing result though: overwrite or skip. For now, I vote for skip and to have the job exit with success. I believe either or both the init and fcst jobs will fire off when the same files are available (data dependency) anyway.

File: jobs/rocoto/getic.sh [hunk 1]
```diff
@@ -101,7 +101,14 @@ else # Pull chgres cube inputs for cold start IC generation
...
 
 # Move extracted data to ROTDIR
-if [ ! -d ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT} ]; then mkdir -p ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT} ; fi
+if [ ! -d ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT} ]; then
+  mkdir -p ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT}
+else
+  # Exception handling on case if ICS already exist
+  echo "The ICS target directory is not empty. Exiting job"
+  exit 0
+fi
```
Comment (KateFriedman-NOAA) [inline jobs/rocoto/getic.sh]: This is good if we only wanna check that the $COMPONENT folder exists and then exit. Thinking about this a bit more, I'm wondering if we should also check for the various IC files within before exiting. Thoughts @WalterKolczynski-NOAA ?

**Comment by aerorahul** [comment]
Can we please keep the discussion in this PR confined to resolving the issue that was opened as a bug and resolve this ASAP?
If further enhancements are desired, feel free to open a issue and discuss it there.

**Review by KateFriedman-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
Noted @aerorahul . I approve this bug fix. Will discuss further enhancements elsewhere.

File: jobs/rocoto/getic.sh (hunk 1 above)
Comment (aerorahul) [inline jobs/rocoto/getic.sh]: I 
```suggestion
if [ -d ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT} ]; then
    rm -rf ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT}
fi
mkdir -p ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/${COMPONENT}
```

**Review by WalterKolczynski-NOAA — APPROVED** [review]
