### PR TITLE
copy/link abias_int to satbias_in in the eupd run directory

### LINKED ISSUE #4331: exglobal_enkf_update.sh missing satbias_in
### What is wrong?

`dev/scripts/exglobal_enkf_update.sh` does not copy (link) the radiance bias correction file to local file `satbias_in` in the run directory.  As a result only satellite_senors with at least one channel with `iuse_rad = 4` are assimilated by `enkf.x` in the eupd job.  Radiance observations from all other satellite_sensors are put in monitor mode (`iuse_rad = -1`) by [lines 1554-1559](https://github.com/NOAA-EMC/GSI/blob/ea96a3859e26bbfb18874dbac222738ea187cbd8/src/gsi/radinfo.f90#L1154C1-L1159C14) of GSI `src/gsi/radinfo.f90`

### What should have happened?

All radiances which pass quality control in the eobs job should be assimilated in the eupd job.

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

be51ea0

### Steps to reproduce

1. clone, build, and install g-w `develop`
2. set up an experiment with ensemble variational DA
3. cycle up through completion of first eupd job
4. compare the list of assimilated radiance satellite_sensors in `enkfgdas.t${cyc}z.enkstat.txt` with the list in `enkfgdas.t${cyc}z.gsistat_ensmean.txt`.   The `enkfstat` list will only include data from amsua and atms whereas the `gsistat` list will include these and other sensors.

For example, `/lfs/h2/emc/gfstemp/emc.global/comroot/retrov17_01_realtime/enkfgdas.20251215/00/ensstat/analysis/atmos/enkfgdas.t00z.enkfstat.txt` contains
```
nid001274.cactus.wcoss2.ncep.noaa.gov 2:    54         amsua_metop-b  num_obs_tot=     27475
nid001274.cactus.wcoss2.ncep.noaa.gov 2:    59              atms_npp  num_obs_tot=    105455
nid001274.cactus.wcoss2.ncep.noaa.gov 2:    60              atms_n20  num_obs_tot=    181969
nid001274.cactus.wcoss2.ncep.noaa.gov 2:    66         amsua_metop-c  num_obs_tot=    222800
nid001274.cactus.wcoss2.ncep.noaa.gov 2:    78              atms_n21  num_obs_tot=    298575
```
whereas `enkfgdas.t00z.gsistat_ensmean.txt` contains
```
o-g 01 rad   metop-b      amsua           1922730        50248        27475    15345.       15345.      0.55849      0.55849
o-g 01 rad   metop-c      amsua           1899060        58864        41266    24194.       24194.      0.58630      0.58630
o-g 01 rad   metop-b      mhs             2499995        17845         9817    1693.4       1693.4      0.17250      0.17250
o-g 01 rad   metop-c      mhs             2499995        17705         7933    1533.8       1533.8      0.19334      0.19334
o-g 01 rad   metop-b      iasi          330783992      2726216       456932    95326.       95326.      0.20862      0.20862
o-g 01 rad   metop-c      iasi          378167328      2686108       443724    88441.       88441.      0.19932      0.19932
o-g 01 rad   npp          atms            7539422       107418        77980    15375.       15375.      0.19717      0.19717
o-g 01 rad   n20          atms            7678858       105204        76514    13295.       13295.      0.17375      0.17375
o-g 01 rad   n21          atms            7892940       105819        75775    14132.       14132.      0.18650      0.18650
o-g 01 rad   n20          cris-fsr      405650304      2275679       200234    30505.       30505.      0.15235      0.15235
o-g 01 rad   n21          cris-fsr      397519920      2277404       200921    29476.       29476.      0.14670      0.14670
o-g 01 rad   metop-b      avhrr           1758183         7306         4237    794.34       794.34      0.18748      0.18748
o-g 01 rad   metop-c      avhrr            992468         6437         4063    839.45       839.45      0.20661      0.20661
o-g 01 rad   gpm          gmi            25922104        24752        20714    6621.3       6621.3      0.31966      0.31966
o-g 01 rad   himawari9    ahi             3051470        19260         4510    762.63       762.63      0.16910      0.16910
o-g 01 rad   g18          abi            16396420        17660         4204    508.07       508.07      0.12085      0.12085
o-g 01 rad   g19          abi            15855950        18110         3964    573.18       573.18      0.14460      0.14460
o-g 01 rad   metop-c      amsua           1899060        58870        40831    23941.       23941.      0.58634      0.58634
o-g 01 rad   metop-c      mhs             2499995        17705         7945    1532.7       1532.7      0.19291      0.19291
o-g 01 rad   metop-c      iasi          378167328      2686110       443650    88394.       88394.      0.19924      0.19924
```

This is not correct.  The `enkfstat` file should list all the satellite_sensors found in the `o-g 01 rad` section of `gsistat`.

### Additional information

The `eobs` job creates file `enkfgdas.t00z.abias_int.txt` as `ABIASe`
```
dev/jobs/JGLOBAL_ENKF_SELECT_OBS:export ABIASe="${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_int.txt"
scripts/exglobal_atmos_analysis.sh:ABIASe=${ABIASe:-${COMOUT_ATMOS_ANALYSIS}/${APREFIX}abias_int.txt}
scripts/exglobal_atmos_analysis.sh:    cpfs satbias_out.int "${ABIASe}"
scripts/exglobal_atmos_analysis.sh:    cpfs satbias_in "${ABIASe}"
```

The `eupd` expects an `abias_int` file
```
dev/scripts/exglobal_enkf_update.sh:# GBIASe=${GBIASe:-${APREFIX}abias_int.ensmean.txt}  # TODO: remove (see comment and TODO below) Also, this is not a "G"BIAS (See the name, it has APREFIX in its name)
dev/scripts/exglobal_enkf_update.sh:#${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${GBIASe}" "satbias_in"  # This file does not exist when test was run # TODO: remove
```

Two notes:
1. An incorrect suffix is used for the `abias_int` file in `exglobal_enkf_update.sh`.  The `GBIASe` file should be `abias_int.txt`.  The inclusion of `.ensmean` is not consistent with `ABIASe` in eobs.
2. The `GBIASe` lines are commented out in `exglobal_enkf_update.sh`.  This is not correct.

### Do you have a proposed solution?

The following changes to `exglobal_enkf_update.sh` were tested in the real-time GFS v18 GSI and JEDI 3DEnVar parallels running on Cactus
```
--- a/dev/scripts/exglobal_enkf_update.sh
+++ b/dev/scripts/exglobal_enkf_update.sh
@@ -31,7 +31,7 @@ ENKFEXEC=${ENKFEXEC:-${EXECgfs}/enkf.x}
 APREFIX=${APREFIX:-${RUN}.t${cyc}z.}
 GPREFIX=${GPREFIX:-${RUN}.t${GDATE:8:2}z.}
 
-# GBIASe=${GBIASe:-${APREFIX}abias_int.ensmean.txt}  # TODO: remove (see comment and TODO below) Also, this is not a "G"BIAS (See the name, it h
as APREFIX in its name)
+ABIASe=${ABIASe:-${APREFIX}abias_int.txt}
 CNVSTAT="${APREFIX}cnvstat_ensmean.tar"
 OZNSTAT="${APREFIX}oznstat_ensmean.tar"
 RADSTAT="${APREFIX}radstat_ensmean.tar"
@@ -111,7 +111,7 @@ else
 fi
 
 # Bias correction coefficients based on the ensemble mean
-#${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${GBIASe}" "satbias_in"  # This file does not exist when test was run # TODO: remove
+${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${ABIASe}" "satbias_in"
 
 ################################################################################
 # Ensemble guess, observational data and analyses/increments
```

With these changes, the eobs `abias_int` is linked to `satbias_in` in the eupd run directory and `enkf.x` processes all the radiances from eobs except avhrr.  

Data from avhrr is not processed due to an inconsistency in the name of `gsi.x` created avhrr diagnostic files and the names searched for by gdas_analdiag and enkfgdas_ediag when `USE_BUILD_GSINFO=YES`.  See g-w issue [#4330](https://github.com/NOAA-EMC/global-workflow/issues/4330) for details.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
This PR links `abias_int` to `satbias_in` in the eupd run directory.

Resolves #4331 

# Type of change
- [ ] Bug fix (fixes something broken)

# Change characteristics
- Is this change expected to change outputs (e.g. value changes to existing outputs, new files stored in COM, files removed from COM, filename changes, additions/subtractions to archives)? **YES**
  - [x] GFS
  - [ ] GEFS 
  - [ ] SFS
  - [ ] GCAFS

This PR alters ensemble analysis increments generated by the eupd job if radiances from satellites besides amsua and atms are assimilated.  I do not know if GEFS, SFS, or GCAFS cycling runs with eupd.

- Is this a breaking change (a change in existing functionality)? **NO**

- Does this change require an update to any of the following submodules? **NO**

# How has this been tested?
- Clone, build, and install in GFS v17 GSI and JEDI parallels running on WCOSS2 (Cactus)

# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added

### CODE REVIEW

**Review by DavidHuber-NOAA — DISMISSED** [review]

**Comment by DavidHuber-NOAA** [comment]
Launching tests on C6.

File: dev/scripts/exglobal_enkf_update.sh [hunk 1]
```diff
@@ -111,7 +111,7 @@ else
 fi
 
 # Bias correction coefficients based on the ensemble mean
-#${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${GBIASe}" "satbias_in"  # This file does not exist when test was run # TODO: remove
+${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${ABIASe}" "satbias_in"
```
Comment (aerorahul) [inline dev/scripts/exglobal_enkf_update.sh]: Is this a required file?  If so, can we use `cpreq`?

Comment (RussTreadon-NOAA) [reply dev/scripts/exglobal_enkf_update.sh]: Yes, `satbias_in` is required.

**Comment by DavidHuber-NOAA** [comment]
I will incorporate https://github.com/NOAA-EMC/global-workflow/pull/4332/commits/d42c6d64b8f09fbdc83aec6c3d7d7e43983bde6e into the C6 test.

File: dev/scripts/exglobal_enkf_update.sh (hunk 1 above)
Comment (RussTreadon-NOAA) [reply dev/scripts/exglobal_enkf_update.sh]: Replace `${NLN}` with `cpreq` at [d42c6d6](https://github.com/NOAA-EMC/global-workflow/pull/4332/commits/d42c6d64b8f09fbdc83aec6c3d7d7e43983bde6e)

**Comment by RussTreadon-NOAA** [comment]
The GCAFS failures appear to be due to a disconnect between the archive job and changes added by PR [#4147](https://github.com/NOAA-EMC/global-workflow/pull/4147).  

PR [#4147](https://github.com/NOAA-EMC/global-workflow/pull/4147) changed `downset=2` to `downset=1` in dev/parm/config/gcafs/config.atmos_products.  This change appears to turn off generation of `pres_b` files.

`parm/archive/master_gcafs.yaml.j2` contains the following in a `required` section
```
            {% endfor %}
            {% if ARCH_GAUSSIAN %}
            {% for fhr in range(0, FHMAX_GFS + FHOUT_GFS, FHOUT_GFS) %}
            - "{{ COMIN_ATMOS_GRIB_0p25 | relpath(ROTDIR) }}/{{ head }}pres_b.0p25.f{{ '%03d' % fhr }}.grib2"
            - "{{ COMIN_ATMOS_GRIB_0p25 | relpath(ROTDIR) }}/{{ head }}pres_b.0p25.f{{ '%03d' % fhr }}.grib2.idx"
            - "{{ COMIN_ATMOS_GRIB_1p00 | relpath(ROTDIR) }}/{{ head }}pres_b.1p00.f{{ '%03d' % fhr }}.grib2"
            - "{{ COMIN_ATMOS_GRIB_1p00 | relpath(ROTDIR) }}/{{ head }}pres_b.1p00.f{{ '%03d' % fhr }}.grib2.idx"
            {% endfor %}
            {% endif %}
```

`config.arch_tars` for both C96_gcafs_cycled_noDA and 96_gcafs_cycled sets `export ARCH_GAUSSIAN=YES`.  Thus, execution enters the `pres_b` block.   The `pres_b` files were not generated by gcafs_atmos_prod jobs.  Hence the failure.

Thank you @DavidHuber-NOAA for opening issue #4334.  The same disconnect caused the Gaea C6 GCAFS failures.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by DavidHuber-NOAA** [comment]
Marking this PR as passed (cm) on C6 as the only failures were from the known GCAFS archiving issue.  Merging.
