### PR TITLE
Implement fix reorg and remove gfs-utils code

### LINKED ISSUE #356: Move workflow utils into their own directory
Since the workflow utils are now being built as a single package using cmake, it would be nice to move all the directories into a single directory (or maybe their own repo) to clean up sorc a bit.

### LINKED ISSUE #966: Fix file promotion and updated versioned FIX_DIR paths in workflow
**Description**

This issue will document the promotion of `fix_NEW` to `fix` and the associated workflow linking updates to the newly restructured and versioned fix file sets on supported platforms. The initial promotion tasks will happen over a two day period and then the workflow updates will occur.

Checklist

August 10th (promotion day 1)
- [x] rename `fix` to `fix_20210923` (Hera)
- [x] rename `fix` to `fix_20210923` (WCOSS2 Cactus)
- [x] rename `fix` to `fix_20210923` (WCOSS2 Dogwood)
- [x] rename `fix` to `fix_20210923` (Orion)
- [x] rename `fix` to `fix_20210923` (Jet)
- [x] copy new `fix` in to replace `fix` (Hera)
- [x] rsync new `fix` from Hera in to replace `fix` on WCOSS2 Cactus
- [x] rsync new `fix` from Hera in to replace `fix` on WCOSS2 Dogwood
- [x] rsync new `fix` from Hera in to replace `fix` on Orion
- [x] rsync new `fix` from Hera in to replace `fix` on Jet
- [x] copy test version of `fix_NEW` (`fix_NEW_test`) into global space for sanity testing on Hera
- [x] perform sanity tests on `fix_NEW_test` on Hera

August 11th (promotion day 2)
- [x] rename `fix_NEW` to `fix_NEW_20220726` (Hera)
- [x] rename `fix_NEW` to `fix_NEW_20220726` (WCOSS2 Cactus)
- [x] rename `fix_NEW` to `fix_NEW_20220726` (WCOSS2 Dogwood)
- [x] rename `fix_NEW` to `fix_NEW_20220726` (Orion)
- [x] rename `fix_NEW` to `fix_NEW_20220726` (Jet)
- [x] create new `fix_NEW` with symlinks to updated `fix` (Hera)
- [x] create new `fix_NEW` with symlinks to updated `fix` (WCOSS2 Cactus)
- [x] create new `fix_NEW` with symlinks to updated `fix` (WCOSS2 Dogwood)
- [x] create new `fix_NEW` with symlinks to updated `fix` (Orion)
- [x] create new `fix_NEW` with symlinks to updated `fix` (Jet)

August 19th (cleanup)
- [x] delete `fix_NEW_20220726` (Hera)
- [x] delete `fix_NEW_20220726` (WCOSS2 Cactus)
- [x] delete `fix_NEW_20220726` (WCOSS2 Dogwood)
- [x] delete `fix_NEW_20220726` (Orion) 
- [x] delete `fix_NEW_20220726` (Jet)

August 26th (cleanup)
- [x] delete `fix_20210923` (Hera)
- [x] delete `fix_20210923` (WCOSS2 Cactus)
- [x] delete `fix_20210923` (WCOSS2 Dogwood)
- [x] delete `fix_20210923` (Orion) 
- [x] delete `fix_20210923` (Jet)

Workflow updates
- [x] update `link_workflow.sh` `FIX_DIR`s to point to new `fix` (https://github.com/NOAA-EMC/global-workflow/pull/1009)
- [x] introduce fix file versioning for `FIX_DIR` paths in `link_workflow.sh` (https://github.com/NOAA-EMC/global-workflow/pull/1009)
- [x] update scripts based on fix subfolder renaming (https://github.com/NOAA-EMC/global-workflow/pull/1009)
- [x] dependency: update UFS_UTILS version (https://github.com/ufs-community/UFS_UTILS/issues/687)

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
Removes all of the code and scripts that were moved to the new [gfs-utils repo](https://github.com/NOAA-EMC/gfs-utils) and adjusts workflow scripts to build and use them from the new location.

Some of the build scripts had unnecessary calls to machine-setup that are removed because the lower-level script already has the same functionality.

This PR also includes updates to use the new fix organization. This includes the addition of a fix versions file, updates to the link script, and some changes in the fix directories used by scripts to account for files that have been relocated. The versions file sets the version number for each component of fix, so that fix can be more easily maintained and documented. The initial versions are all the same, and correspond to the old fix_NEW directory (other than some directories have been renamed or reorganized). Except gdas, which has already had a new set of fix files added. The fix update also required an update to UFS-Utils.

Finally, the link script has been updated to match the syntax of the rest of the build system ([checkout.sh](sorc/checkout.sh) and [build_all.sh](sorc/build_all.sh)). [link_workflow.sh](sorc/link_workflow.sh) now detects the machine automatically instead of requiring an argument, and dev mode, which used to be set using `emc` as an argument, is now assumed. To run in ops mode (copy instead of link), the `-o` option is used. The full syntax is now simply:
```
./link_workflow.sh [-o]

Fixes #356
Fixes #966
Depends on ufs-community/UFS_UTILS#688

**Type of change**
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**
- [x] 5½-cycle cycling test on Hera
- [x] Coupled test on Hera
- [x] 2½-cycle cycling test on Orion
- [x] Coupled test on Orion

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Currently using a temporary repo for UFS_UTILS until ufs-community/UFS_UTILS#688 is merged.

**Comment by WalterKolczynski-NOAA** [comment]
Going to rerun a test or two over the weekend from a clean install to confirm things still work, but should be able to start reviewing.

**Comment by WalterKolczynski-NOAA** [comment]
Re-tests pass

File: sorc/link_workflow.sh [hunk 1]
```diff
@@ -1,372 +1,421 @@
...
-    exit 1
-fi
-if [ $machine != wcoss2 -a $machine != hera -a $machine != orion -a $machine != jet -a $machine != stampede ]; then
-    echo ' Syntax: link_workflow.sh ( nco | emc ) ( wcoss2 | hera | orion | jet | stampede )'
-    exit 1
-fi
+# shellcheck disable=SC1091
+source gfs_utils.fd/ush/machine-setup.sh > /dev/null 2>&1
+# shellcheck disable=
+machine="${target:?}"
```
Comment (aerorahul) [inline sorc/link_workflow.sh:49]: Why do we need this line.  `machine` was detected from L47.  If it is not supported, this is a hard exit, no?

File: sorc/link_workflow.sh [hunk 2]
```diff
@@ -1,372 +1,421 @@
...
-elif [ $machine = "jet" ]; then
-    FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix_NEW"
-elif [ $machine = "stampede" ]; then
-    FIX_DIR="/work/07738/jkuang/stampede2/tempFixICdir/fix_UFSp6"
-fi
 
-if [ ! -z $FIX_DIR ]; then
- if [ ! -d ${pwd}/../fix ]; then mkdir ${pwd}/../fix; fi
+# Source fix version file
+source "${top_dir}/versions/fix.ver"
```
Comment (aerorahul) [inline sorc/link_workflow.sh]: L51 sources this already. Why do it again?

File: sorc/link_workflow.sh [hunk 3]
```diff
@@ -1,372 +1,421 @@
...
+
+case "${machine}" in
+  "wcoss2")   FIX_DIR="/lfs/h2/emc/global/noscrub/emc.global/FIX/fix" ;;
+  "hera")     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix" ;;
+  "orion")    FIX_DIR="/work/noaa/global/glopara/fix" ;;
+  "jet")      FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix" ;;
+  *)
+    echo "FATAL: Unknown target machine ${machine}, couldn't set FIX_DIR"
+    exit 1
```
Comment (aerorahul) [inline sorc/link_workflow.sh]: This should be check upfront at the earliest possible time available.

File: sorc/link_workflow.sh [hunk 4]
```diff
@@ -1,372 +1,421 @@
...
+  esac
+done
+shift $((OPTIND-1))
 
-if [ $# -lt 2 ]; then
-    echo '***ERROR*** must specify two arguements: (1) RUN_ENVIR, (2) machine'
-    echo ' Syntax: link_workflow.sh ( nco | emc ) ( wcoss2 | hera | orion | jet | stampede )'
-    exit 1
-fi
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
```
Comment (aerorahul) [inline sorc/link_workflow.sh:42]: Isn't this `sorc_dir`?

File: sorc/link_workflow.sh [hunk 5]
```diff
@@ -1,372 +1,421 @@
...
+top_dir=$(cd "$(dirname "${script_dir}")" &> /dev/null && pwd)
```
Comment (aerorahul) [inline sorc/link_workflow.sh:43]: This is `HOMEgfs`, no?

File: sorc/link_workflow.sh [hunk 6]
```diff
@@ -1,372 +1,421 @@
...
 #------------------------------
 #--link source code directories
 #------------------------------
-cd ${pwd}/../sorc   ||   exit 8
+cd "${script_dir}"   ||   exit 8
 
     if [ -d gsi_enkf.fd ]; then
       [[ -d gsi.fd ]] && rm -rf gsi.fd
-      $SLINK gsi_enkf.fd/src/gsi                                                                gsi.fd
+      ${SLINK} gsi_enkf.fd/src/gsi                                                                gsi.fd
```
Comment (aerorahul) [inline sorc/link_workflow.sh:303]: We are overloading `${LINK}` as either copy or link based on NCO or EMC mode.
Can we replace `${SLINK}` and call it `${NLN}`?  There is a chance someone will misunderstand and get confused between the interchangeable `LINK` and `SLINK`.

File: ush/gfs_bufr.sh [hunk 7]
```diff
@@ -19,30 +19,18 @@
 # 2019-10-10  Guang Ping Lou: Read in NetCDF files
 # echo "History: February 2003 - First implementation of this utility script"
 #
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs:-?}/ush/preamble.sh"
```
Comment (KateFriedman-NOAA) [inline ush/gfs_bufr.sh]: Is there a difference between `:-?` and `:?`?

**Review by KateFriedman-NOAA — APPROVED** [review]

File: ush/gfs_bufr.sh (hunk 7 above)
Comment (WalterKolczynski-NOAA) [reply ush/gfs_bufr.sh]: Actually, `:?` is correct. I need to change these.

File: ush/gfs_truncate_enkf.sh [hunk 8]
```diff
@@ -14,7 +14,7 @@ mkdir -p $DATATMP
 cd $DATATMP
 
 export LEVS=${LEVS_LORES:-64}
-export FIXam=${FIXam:-$HOMEgfs/fix/fix_am}
+export FIXam=${FIXam:-$HOMEgfs/fix/am}
```
Comment (aerorahul) [inline ush/gfs_truncate_enkf.sh:17]: I doubt this script is used today.  @yangfanglin do you know?

File: ush/fv3gfs_regrid_nemsio.sh [hunk 9]
```diff
@@ -28,9 +28,9 @@ DATA=${DATA:-$pwd}
 NWPROD=${NWPROD:-$pwd}
 HOMEgfs=${HOMEgfs:-$NWPROD}
 FIX_DIR=${FIX_DIR:-$HOMEgfs/fix}
-FIX_AM=${FIX_AM:-$FIX_DIR/fix_am}
-FIXfv3=${FIXfv3:-$FIX_DIR/fix_fv3_gmted2010}
-REGRID_NEMSIO_EXEC=${REGRID_NEMSIO_EXEC:-$HOMEgfs/exec/regrid_nemsio}
+FIX_AM=${FIX_AM:-$FIX_DIR/am}
```
Comment (aerorahul) [inline ush/fv3gfs_regrid_nemsio.sh:30]: This script can be deleted.  It is no longer in use.

File: ush/fv3gfs_remap.sh [hunk 10]
```diff
@@ -16,7 +16,7 @@ export DATA=${DATA:-$pwd}
 export NWPROD=${NWPROD:-$pwd}
 export HOMEgfs=${HOMEgfs:-$NWPROD}
 export FIX_DIR=${FIX_DIR:-$HOMEgfs/fix}
-export FIXfv3=${FIXfv3:-$FIX_DIR/fix_fv3_gmted2010}
+export FIXfv3=${FIXfv3:-$FIX_DIR/orog}
```
Comment (aerorahul) [inline ush/fv3gfs_remap.sh:18]: This script is not used in the workflow.
If it is necessary, it belongs in ufs-utils.  # TODO

**Review by aerorahul — COMMENTED** [review]
looks good.  Some comments.
This PR would have been much easier to review if it were separate PRs:
1. removing gfs-utils
2. fix reorg
3. updates to build scripts
4. updates to `link_workflow.sh`

File: sorc/link_workflow.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:49]: [machine-setup.sh](https://github.com/NOAA-EMC/gfs-utils/blob/develop/ush/machine-setup.sh) sets `$target`, but this script for some reason uses `$machine`. I didn't want to make yet more changes to change them all in this PR.

File: sorc/link_workflow.sh (hunk 2 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh]: I think this was an error when I cherry-picked Kate's changes over. I'll remove it.

File: sorc/link_workflow.sh (hunk 5 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:43]: Yes, but that isn't a thing here. This isn't a runtime script.

File: sorc/link_workflow.sh (hunk 6 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:303]: I don't know that NLN is all that much clearer, but at any rate I wasn't going to change it for this PR. It has been `LINK` and `SLINK` for a long time.

File: sorc/link_workflow.sh (hunk 4 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:42]: It would be the sorc dir, yes.

File: sorc/link_workflow.sh (hunk 3 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh]: Agree, not sure how it got moved this far away from machine-setup.

File: sorc/link_workflow.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:49]: Actually, it is only used a couple places. I think I can change it.

Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:49]: Though I'd rather machine-setup be setting `$machine` instead of `$target` in the first place.

File: sorc/link_workflow.sh (hunk 2 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh]: Redundant load removed

File: sorc/link_workflow.sh (hunk 3 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh]: Moved to directly after the machine-setup, which is the first thing after option parsing.

File: ush/fv3gfs_regrid_nemsio.sh (hunk 9 above)
Comment (WalterKolczynski-NOAA) [reply ush/fv3gfs_regrid_nemsio.sh:30]: We have a separate issue already open to remove all the nemsio stuff. Someone just needs to go through it all.

File: ush/gfs_bufr.sh (hunk 7 above)
Comment (WalterKolczynski-NOAA) [reply ush/gfs_bufr.sh]: Fixed

File: sorc/link_workflow.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply sorc/link_workflow.sh:49]: Going to leave this for now unless there is an objection. We can switch all scripts to use `$machine` in the future.
