### PR TITLE
Fix OpenMP over-allocation of resources in exglobal_atmos_products.sh…

### LINKED ISSUE #2211: A couple of Global Workflow tasks are failing on S4 due to over-threading by OpenMP
### What is wrong?

A couple of Global Workflow tasks are failing on S4 due to lack of system resources for OpenMP
Affected tasks:
 - gfsatmanlprod
 - gdasatmanlprod
 - gfsatmprod_fxxx-fxxx
 - gdasatmprod_fxxx-fxxx
 
--typical error message--
```
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
```

### What should have happened?

Tasks should complete successfully

### What machines are impacted?

All or N/A

### Steps to reproduce

Run any of the following tasks on resolution 192/96 on S4 and check for OpenMP errors.
 - gfsatmanlprod
 - gdasatmanlprod
 - gfsatmprod_fxxx-fxxx
 - gdasatmprod_fxxx-fxxx

### Additional information

This issue is similar to issue #2206 however, they affect different set of tasks.

### Do you have a proposed solution?

In <GW>/scripts/exglobal_atmos_products.sh,
prefix the call to "${HOMEgfs}/ush/run_mpmd.sh" by OMP_NUM_THREADS=1 as show bellow.

This ensures that OMP_NUM_THREADS is set to 1 only when running MPMD, where multiple instances are being kicked off simultaneously. By only prefixing this call, we are sure that no other run is affected.

<GW>/scripts/exglobal_atmos_products.sh
```
  # Run with MPMD or serial
  if [[ "${USE_CFP:-}" = "YES" ]]; then
    OMP_NUM_THREADS=1 "${HOMEgfs}/ush/run_mpmd.sh" "${DATA}/poescript"
    export err=$?
  else
    chmod 755 "${DATA}/poescript"
    bash +x "${DATA}/poescript" > mpmd.out 2>&1
    export err=$?
  fi
```

### PR DESCRIPTION
**Pull request by souopgui**
Fix OpenMP over-allocation of resources running MPMD tasks

# Description
- Prefix the call to "${HOMEgfs}/ush/run_mpmd.sh" by OMP_NUM_THREADS=1.
- This ensures that OMP_NUM_THREADS is set to 1 only when running MPMD, where multiple instances are being kicked off simultaneously. By only prefixing this call, we are sure that no other run is affected.
- It prevent the overthreading in OpenMP when running MPMD tasks
- This fix is transparent to users.
Resolves #2211

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cloned and tested on S4

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: scripts/exglobal_atmos_products.sh [hunk 1]
```diff
@@ -129,7 +129,7 @@ for (( nset=1 ; nset <= downset ; nset++ )); do
 
   # Run with MPMD or serial
   if [[ "${USE_CFP:-}" = "YES" ]]; then
-    "${HOMEgfs}/ush/run_mpmd.sh" "${DATA}/poescript"
+    OMP_NUM_THREADS=1 "${HOMEgfs}/ush/run_mpmd.sh" "${DATA}/poescript"
```
Comment (DavidHuber-NOAA) [inline scripts/exglobal_atmos_products.sh:132]: I tested this on Orion and it works well with faster runtimes.  I will note that this achieves the same effect as
`WGRIB2="${WGRIB2} -ncpu 1" "${HOMEgfs}/ush/run_mpmd.sh" "${DATA}/poescript"`
But I am satisfied with this option since there is no need to run anything threaded inside of this MPMD job.

**Review by DavidHuber-NOAA — APPROVED** [review]
Approve.

File: scripts/exglobal_atmos_products.sh (hunk 1 above)
Comment (aerorahul) [reply scripts/exglobal_atmos_products.sh:132]: I too am ok with this for the time being.
Note however that in the future, `run_mpmd.sh` could be used for running threaded applications, at which point, one would need to account for the index and the thread count.
We can address that when a use case presents itself.
Thanks for this PR.

**Review by aerorahul — APPROVED** [review]
