### PR TITLE
Save the required CICE history for the sea-ice DA

### LINKED ISSUE #2059: hist_avg should be an array
### What is wrong?

The hist_avg was apparently changed in CICE to be an array. This needs to be reflected in the workflow, thanks to @DeniseWorthen for pointing this out.

### What should have happened?

hist_avg should be set to `F F F F F` in `ice_in`.

### What machines are impacted?

All or N/A

### Steps to reproduce

run with DA "turned on".

### Additional information

...

### Do you have a proposed solution?

set cice_hist_avg to be an array of size 5

### PR DESCRIPTION
**Pull request by guillaumevernieres**
The `hist_avg` setting of CICE was changed to be an array.

Fixes #2059

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? **NO**
- Does this change require a documentation update? **NO**

# How has this been tested?
Cycled marine DA test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]

File: ush/forecast_postdet.sh [hunk 1]
```diff
@@ -883,7 +883,7 @@ CICE_postdet() {
   dumpfreq=${dumpfreq:-"y"} #  "h","d","m" or "y" for restarts at intervals of "hours", "days", "months" or "years"
 
   if [[ "${RUN}" =~ "gdas" ]]; then
-    cice_hist_avg=".false."   # DA needs instantaneous
+    cice_hist_avg=".false., .false., .false., .false., .false."   # DA needs instantaneous
   else
     cice_hist_avg=".true."    # P8 wants averaged over histfreq_n
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_postdet.sh]: Should this be
```suggestion
    cice_hist_avg=".true., .true., .true., .true., .true."    # P8 wants averaged over histfreq_n
```

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: ush/forecast_postdet.sh (hunk 1 above)
Comment (JessicaMeixner-NOAA) [reply ush/forecast_postdet.sh]: It defaults to true, so this isn't strictly necessary.

Comment (guillaumevernieres) [reply ush/forecast_postdet.sh]: Up to you guys @WalterKolczynski-NOAA . The default is .true.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: ush/forecast_postdet.sh (hunk 1 above)
Comment (guillaumevernieres) [reply ush/forecast_postdet.sh]: Too late @JessicaMeixner-NOAA , just committed @WalterKolczynski-NOAA 's suggestion. It's probably clearer that way.

**Review by aerorahul — APPROVED** [review]
looks good to me.

**Comment by aerorahul** [comment]
> Automated global-workflow Testing Results:
> 
> ```
> Machine: Orion
> Start: Wed Nov 15 11:26:55 CST 2023 on Orion-login-1.HPC.MsState.Edu
> ---------------------------------------------------
> Build: Completed at Wed Nov 15 11:27:01 CST 2023
> Link: *** FAILED ***
> Link: Failed at Wed Nov 15 11:27:01 CST 2023
> Checkout: Completed at Wed Nov 15 11:28:04 CST 2023
> Build: Completed at Wed Nov 15 12:20:00 CST 2023
> Case setup: Completed for experiment C48_ATM_9e0c4860
> Case setup: Completed for experiment C48_S2SA_gefs_9e0c4860
> Case setup: Completed for experiment C48_S2SW_9e0c4860
> Case setup: Completed for experiment C96_atm3DVar_9e0c4860
> Case setup: Completed for experiment C96C48_hybatmDA_9e0c4860
> ```

@TerrenceMcGuinness-NOAA 
Here is another one with link failed but the CI continued.  Can we please address this issue ASAP?

**Comment by TerrenceMcGuinness-NOAA** [comment]
@aerorahul On it now ... [197](https://github.com/TerrenceMcGuinness-NOAA/global-workflow/pull/197)

**Comment by TerrenceMcGuinness-NOAA** [comment]
@WalterKolczynski-NOAA  As stated before we can not remove **Running** labels the work around is `rm -Rf /work2/noaa/stmp/GFS_CI_ROOT/PR/2062/RUNTESTS/EXPDIR/*` until we have this capability as a feature.
