### PR TITLE
Move product functions to separate script

### LINKED ISSUE #1890: Update gempak and AWIPS for trim_rh refactor
### What is wrong?

PR #1822 converted some small stand-alone bash scripts (`trim_rh.sh` and `mod_icec.sh`). However, the trim_rh script is also used by the gempak and AWIPS scripts. These scripts now fail because the script cannot be found.

### What should have happened?

AWIPS and gempak scripts should have the trim_rh functionality available.

### What machines are impacted?

All or N/A

### Steps to reproduce

1. Turn on gempak and awips
2. Run workflow
3. Watch jobs fail

### Additional information

None

### Do you have a proposed solution?

Move the new trim_rh function back out to a separate script, and then update all product scripts to use the new function.

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
PR #1822 converted some formerly stand-alone scripts and moved them inside one of the standard product scripts. However, `trim_rh.sh` is also used by gempak and AWIPS, so this change caused those jobs to start failing (they are not yet tested by CI).

Those functions have now been moved into a separate product functions script that can be sourced by all the scripts that need the functions. A third similar script was also eliminated and converted into a function.

Additionally fixes a base bug in AWIPS and updates some scripts to satisfy (or at least mostly satisfy) the linter.

**AWIPS still failing when creating GRIB1 products.** That will be addressed in a future PR (and may need a subject-matter expert).

Resolves #1890

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Cycled test on Orion

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG [hunk 1]
```diff
@@ -47,21 +47,22 @@ export pgmout=OUTPUT.$$
...
+if [[ -e "${pgmout}" ]] ; then
+  cat "${pgmout}"
 fi
 
 ###################################
 # Remove temp directories
 ###################################
-if [ "${KEEPDATA}" != "YES" ] ; then
-  rm -rf ${DATA}
+cd "${DATAROOT}" || pass
```
Comment (aerorahul) [inline jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG:64]: shouldn't this be exit?  I think that is what we have been doing everywhere.

File: scripts/exgfs_atmos_awips_20km_1p0deg.sh [hunk 2]
```diff
@@ -51,6 +54,7 @@ while (( icnt < 1000 )); do
    if (( icnt >= 180 )); then
       msg="FATAL ERROR: No GFS pgrb2 file after 30 min of waiting"
       err_exit "${msg}"
+      exit 5
```
Comment (aerorahul) [inline scripts/exgfs_atmos_awips_20km_1p0deg.sh:57]: doesn't `err_exit` cause this to exit already? `exit 5` will never reach if there is an error.

File: ush/product_functions.sh [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+          -if 'ICEC' -rpn 'rcl_1:0:==:*' -fi \
+          -set_grib_type same \
+          -set_scaling same same \
+          -grib_out "${filename}.new"
+  rc=$?
+  if (( rc == 0 )); then mv "${filename}.new" "${filename}"; fi
+  return "${rc}"
+}
+
+function scale_dec() {
```
Comment (aerorahul) [inline ush/product_functions.sh:29]: Could you please put a one-liner what this function is supposedly doing?

**Review by aerorahul — COMMENTED** [review]
Thanks for catching and fixing this.
Just a couple of requests.
In the exgfs_atmos_awips... scripts, I could not find a reference to where `masterfile` is defined. I couldn't find it in the calling J-job either.  Can someone point out where that is specified, and/or provide a log file for this job.

**Comment by GwenChen-NOAA** [comment]
> In the exgfs_atmos_awips... scripts, I could not find a reference to where `masterfile` is defined. I couldn't find it in the calling J-job either. Can someone point out where that is specified, and/or provide a log file for this job.

The `masterfile` is created using this command in the exgfs_atmos_awips_20km_1p0deg.sh script:

"$WGRIB2 tmpfile${fcsthrs} | grep  -F -f $PARMproduct/gfs_awips_parmlist_g2 | $WGRIB2 -i -grib masterfile  tmpfile${fcsthrs}"

This command generates an inventory of `tmpfile`, extracts the variables listed in gfs_awips_parmlist_g2 from `tmpfile`, and then creates a new grib file called `masterfile`. You can find a log file at /lfs/h1/ops/prod/output/20230926/gfs_atmos_awips_003_00.o100151049.

**Comment by aerorahul** [comment]
> > In the exgfs_atmos_awips... scripts, I could not find a reference to where `masterfile` is defined. I couldn't find it in the calling J-job either. Can someone point out where that is specified, and/or provide a log file for this job.
> 
> The `masterfile` is created using this command in the exgfs_atmos_awips_20km_1p0deg.sh script:
> 
> '$WGRIB2 tmpfile${fcsthrs} | grep -F -f $PARMproduct/gfs_awips_parmlist_g2 | WGRIB2−i−gribmasterfiletmpfile{fcsthrs}'
> 
> This command generates an inventory of `tmpfile`, extracts the variables listed in gfs_awips_parmlist_g2 from `tmpfile`, and then creates a new grib file called `masterfile`. You can find a log file at /lfs/h1/ops/prod/output/20230926/gfs_atmos_awips_003_00.o100151049.



> > In the exgfs_atmos_awips... scripts, I could not find a reference to where `masterfile` is defined. I couldn't find it in the calling J-job either. Can someone point out where that is specified, and/or provide a log file for this job.
> 
> The `masterfile` is created using this command in the exgfs_atmos_awips_20km_1p0deg.sh script:
> 
> '$WGRIB2 tmpfile${fcsthrs} | grep -F -f $PARMproduct/gfs_awips_parmlist_g2 | WGRIB2−i−gribmasterfiletmpfile{fcsthrs}'
> 
> This command generates an inventory of `tmpfile`, extracts the variables listed in gfs_awips_parmlist_g2 from `tmpfile`, and then creates a new grib file called `masterfile`. You can find a log file at /lfs/h1/ops/prod/output/20230926/gfs_atmos_awips_003_00.o100151049.

Aah yes.  Thank you @GwenChen-NOAA

File: jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG:64]: I think this one, while it should never fail, should be non-fatal. The only thing left is cleaning up `${DATA}`, which doesn't really require we move out of the `${DATA}` directory to do it. I only added it because I was getting some messages about being in a non-existent directory until the next script did a `cd`.

File: scripts/exgfs_atmos_awips_20km_1p0deg.sh (hunk 2 above)
Comment (WalterKolczynski-NOAA) [reply scripts/exgfs_atmos_awips_20km_1p0deg.sh:57]: It's _supposed_ to, but given `err_exit` doesn't work on some RDHPCS, I put this in (it was on a never-ending loop last night before I fixed something).

File: ush/product_functions.sh (hunk 3 above)
Comment (WalterKolczynski-NOAA) [reply ush/product_functions.sh:29]: @GwenChen-NOAA Can you help with this? I've looked at the [documentation for -set-scaling](https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/set_scaling.html), but that only gave me a vague idea what is going on.

**Comment by GwenChen-NOAA** [comment]
This function is to mask out land grids for ICEC while keeping the bits for
storing the grib values the same as the original file. The -rpn option
<https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/rpn.html> will reset
the bits to default without '-set_scaling same same'. Hope this answers
your question.

Gwen

**Comment by WalterKolczynski-NOAA** [comment]
@GwenChen-NOAA Think there was a misunderstanding. Question is about the `scale_dec` function, which changes the scaling to `-1 0` for `TMP` and `PWAT` and to `0 0` for `WEASD`

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WalterKolczynski-NOAA !

File: ush/product_functions.sh (hunk 3 above)
Comment (WalterKolczynski-NOAA) [reply ush/product_functions.sh:29]: Added something

**Review by aerorahul — APPROVED** [review]
looks good.
thanks for catching this error on my part.

**Comment by GwenChen-NOAA** [comment]
> @GwenChen-NOAA Think there was a misunderstanding. Question is about the `scale_dec` function, which changes the scaling to `-1 0` for `TMP` and `PWAT` and to `0 0` for `WEASD`

Not sure about what are you asking. The "-set_scaling -1 0" sets the decimal scaling to -1 or 0.1 units. I think the purpose is to reduce the size of the new grib file.

**Comment by GwenChen-NOAA** [comment]
@WalterKolczynski-NOAA, are you able to get GFS downstream package running after this update?
