### PR TITLE
Archive TC tracking logs if produced

### LINKED ISSUE #625: GFS archiving job fails when cyclone tracking isn't performed
**Expected behavior**

The gfsarch job should be able to archive to HPSS on cycles when there are no cyclones to track.  An example cycle is 2020080600.

**Current behavior**

When htar is called on gfsa.txt, the tracking files are not found for 2020080600, resulting in an error.

**To Reproduce**

1. Start a cycled test on 2020080500
2. Run the cycling until 2020080600 and let the gfsarch job submit

**Context**

These files are selected in hpssarch_gen.sh.  There may be other files that are only conditionally created.

**Possible Implementation**

Adding conditionals around these files may be a solution.  However, something more robust that checks to see if there is tracking information in the tcvitals files would be advisable if the intent is to allow the gfsarch job to fail if TC_Tracker failed.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
**Description**

This adds a check for the TC tracking logs in case they are not produced to prevent the gfsarch job from failing on cycles when there were no TCs to track.  Fixes #625.

**Type of change**

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

- [X] Cycled test on Hera for 2020080600
- [ ] Cycled test on WCOSS
  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: ush/hpssarch_gen.sh [hunk 1]
```diff
@@ -106,12 +106,15 @@ if [ $type = "gfs" ]; then
...
-  echo  "${dirname}storms.gfso.atcf_gen.altg.${PDY}${cyc}  " >>gfsa.txt
+  #Only generated if there are cyclones to track
+  if [ -s ${dirname}avno.t${cyc}z.cyclone.trackatcfunix ]; then
+    echo  "${dirname}avno.t${cyc}z.cyclone.trackatcfunix     " >>gfsa.txt
+    echo  "${dirname}avnop.t${cyc}z.cyclone.trackatcfunix    " >>gfsa.txt
+    echo  "${dirname}trak.gfso.atcfunix.${PDY}${cyc}         " >>gfsa.txt
+    echo  "${dirname}trak.gfso.atcfunix.altg.${PDY}${cyc}    " >>gfsa.txt
+    echo  "${dirname}storms.gfso.atcf_gen.${PDY}${cyc}       " >>gfsa.txt
+    echo  "${dirname}storms.gfso.atcf_gen.altg.${PDY}${cyc}  " >>gfsa.txt
+  fi
```
Comment (aerorahul) [inline ush/hpssarch_gen.sh]: Might I suggest the following:
```suggestion
cyclone_files=(avno.t${cyc}z.cyclone.trackatcfunix
               avnop.t${cyc}z.cyclone.trackatcfunix
               trak.gfso.atcfunix.${PDY}${cyc}
               trak.gfso.atcfunix.altg.${PDY}${cyc}
               storms.gfso.atcf_gen.${PDY}${cyc}
               storms.gfso.atcf_gen.altg.${PDY}${cyc})
for file in ${cyclone_files[@]}; do
  [[ -s ${$dirname}${file} ]] && echo "${dirname}$file" >> gfsa.txt
done
```
This will ensure that each file is checked for existence before being added to be archived.

Comment (DavidHuber-NOAA) [reply ush/hpssarch_gen.sh]: This is a much better solution.  I've implemented and tested it on Hera, which archived two of the six files.  Thanks @aerorahul!

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by aerorahul — APPROVED** [review]
