### PR TITLE
Use default stochastic physics

### LINKED ISSUE #3901: use default spptint, skebint and shumint for stochastic physics
### What is wrong?

We have been using default spptint/skebint/shumint value (=0) previously when these parameters are not explicitly included in the namelist, the defaule values (skebint=1800, shumint=3600, spptint=1800) set in the namelist are not consistent with the default value in model code. 

ocean stochastic physics setting should be removed from nam_stochy in enkfgdas as they are not used. 
only 1 sppt seed should be included as only 1 scale is used in enkfgdas.

This is a sample setting from retro12.
&nam_stochy
  STOCHINI=.false.,
  skeb = 0.3
  iseed_skeb = 20241229065001
  skeb_tau = 21600.
  skeb_lscale = 250000.
  skebnorm = 0
  skeb_npass = 30
  skeb_vdof = 5
  skebint = 1800
  shum = 0.005
  iseed_shum = 20241229065002
  shum_tau = 21600.
  shum_lscale = 500000.
  shumint = 3600
  sppt = 0.5
  iseed_sppt = 20241229065003,20241229065004,20241229065005,20241229065006,20241229065007
  sppt_tau = 21600.
  sppt_lscale = 500000.
  sppt_logit = .true.
  sppt_sfclimit = .true.
  use_zmtnblck = .true.
  spptint = 1800
  pbl_taper = 0,0,0,0.125,0.25,0.5,0.75
  OCNSPPT = 0.8,0.4,0.2,0.08,0.04
  OCNSPPT_LSCALE = 500.E3,1000.E3,2000.E3,2000.E3,2000.E3
  OCNSPPT_TAU = 2.16E4,2.592E5,2.592E6,7.776E6,3.1536E7
  ISEED_OCNSPPT =0
  EPBL = 0.8,0.4,0.2,0.08,0.04
  EPBL_LSCALE = 500.E3,1000.E3,2000.E3,2000.E3,2000.E3
  EPBL_TAU = 2.16E4,2.592E5,2.592E6,7.776E6,3.1536E7
  ISEED_EPBL = 0
/

### What should have happened?

this is the sample setting we should have. 
&nam_stochy
  STOCHINI=.false.,
  skeb = 0.3
  iseed_skeb = 20241229065001
  skeb_tau = 21600.
  skeb_lscale = 250000.
  skebnorm = 0
  skeb_npass = 30
  skeb_vdof = 5
  skebint = 0
  shum = 0.005
  iseed_shum = 20241229065002
  shum_tau = 21600.
  shum_lscale = 500000.
  shumint = 0
  sppt = 0.5
  iseed_sppt = 20241229065003
  sppt_tau = 21600.
  sppt_lscale = 500000.
  sppt_logit = .true.
  sppt_sfclimit = .true.
  use_zmtnblck = .true.
  spptint =0
  pbl_taper = 0,0,0,0.125,0.25,0.5,0.75
/

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

retro12

### Steps to reproduce

check retro12

### Additional information

_No response_

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
# Description

This PR modifies `spptint`, `skebint` and `shumint` to the default values of those used in production GFSv16. 

Resolves #3901 

# Type of change
- [ ] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [x] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO
- Does this change require an update to any of the following submodules? NO

  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?

All offline CI tests passed on WCOSS2. 

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

File: ush/parsing_namelists_FV3.sh [hunk 1]
```diff
@@ -443,25 +443,21 @@ local SKEB_LSCALE=${SKEB_LSCALE:-"-999."}
...
 local ISEED_SPPT=${ISEED_SPPT:-${ISEED}}
 local SPPT_TAU=${SPPT_TAU:-"-999."}
 local SPPT_LSCALE=${SPPT_LSCALE:-"-999."}
 local SPPT_LOGIT=${SPPT_LOGIT:-".true."}
 local SPPT_SFCLIMIT=${SPPT_SFCLIMIT:-".true."}
 local USE_ZMTNBLCK=${use_zmtnblck:-".true."}
-local SPPTINT=${SPPTINT:-"1800"}
+local SPPTINT=${SPPTINT:-"0"}
 local PBL_TAPER=${pbl_taper:-"0,0,0,0.125,0.25,0.5,0.75"}
-local OCNSPPT=${OCNSPPT:-"0.8,0.4,0.2,0.08,0.04"}
```
Comment (JessicaMeixner-NOAA) [inline ush/parsing_namelists_FV3.sh:461]: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/global_control.nml.IN#L432-L43 

While I haven't tested - I'm pretty sure removing these will make things crash: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/global_control.nml.IN#L432-L43

Comment (EricSinsky-NOAA) [reply ush/parsing_namelists_FV3.sh:461]: You are right, @JessicaMeixner-NOAA. These changes have been reverted.

Comment (bingfu-NOAA) [reply ush/parsing_namelists_FV3.sh:461]: Jessica, if you want to have some tests, you only need to manually change the default values to 0 for spptint, shumint and skebint. These are the only updates that will change the results.

**Comment by JessicaMeixner-NOAA** [comment]
@EricSinsky-NOAA  - I see that this PR is still a draft.  Is this just because we need testing or something else? 

We've pulled this change into the testing we're preparing to do for the next update of experiments, so just wanted to check in on this PR and see why it was still a draft.

**Comment by EricSinsky-NOAA** [comment]
> @EricSinsky-NOAA - I see that this PR is still a draft. Is this just because we need testing or something else?
> 
> We've pulled this change into the testing we're preparing to do for the next update of experiments, so just wanted to check in on this PR and see why it was still a draft.

Preliminary testing has finished. Marking this PR as ready for review.

**Review by aerorahul — APPROVED** [review]
lgtm.  did not test or validate if these are acceptable to the GFS, GEFS, SFS project requirements.

**Comment by aerorahul** [comment]
@dpsarmie Can you also review please?

**Review by bingfu-NOAA — APPROVED** [review]

**Comment by dpsarmie** [comment]
These changes look fine to me and shouldn't cause any issues. These changes are also being adopted in https://github.com/ufs-community/ufs-weather-model/pull/2889/ but that will not change the GW setup when that UFS hash is brought in.

File: ush/parsing_namelists_FV3.sh (hunk 1 above)
Comment (JessicaMeixner-NOAA) [reply ush/parsing_namelists_FV3.sh:461]: @bingfu-NOAA  - we've made the decision to use this change for GFS and have already done testing.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by NeilBarton-NOAA — APPROVED** [review]

**Review by CatherineThomas-NOAA — APPROVED** [review]

**Comment by DavidHuber-NOAA** [comment]
@EricSinsky-NOAA Have your tests completed on WCOSS2?

**Comment by EricSinsky-NOAA** [comment]
@DavidHuber-NOAA All jobs passed on WCOSS2 except for the prepoceanobs tasks. I do not believe the prepoceanobs failures are related to the changes made in this PR though. I have merged the latest EMC/develop and am relaunching the tests. 

```
******** C48ATM ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48_ATM
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 23 2025 13:10:29    Sep 23 2025 14:20:45
******** C48mx5003DVarAOWCDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48mx500_3DVarAOWCDA
202103250000        gfs_prepoceanobs                   219201808                DEAD                 271         2          44.0
202103250000       gdas_prepoceanobs                   219201811                DEAD                 271         2          72.0
******** C48mx500hybAOWCDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48mx500_hybAOWCDA
202103250000       gdas_prepoceanobs                   219201773                DEAD                 271         2          44.0
******** C48S2SW ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48_S2SW
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 23 2025 13:10:49    Sep 23 2025 14:20:51
******** C48S2SWAgefs ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48_S2SWA_gefs
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 23 2025 13:10:33    Sep 23 2025 14:31:01
******** C48S2SWextended ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C48_S2SW_extended
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 23 2025 13:10:30    Sep 23 2025 15:35:38
202103231800        Done    Sep 23 2025 13:10:30    Sep 23 2025 15:40:48
******** C96atm3DVarextended ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96_atm3DVar_extended
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Sep 23 2025 13:11:03    Sep 23 2025 13:30:40
202112210000        Done    Sep 23 2025 13:11:03    Sep 23 2025 17:55:38
202112210600        Done    Sep 23 2025 13:11:03    Sep 23 2025 18:45:47
202112211200        Done    Sep 23 2025 13:35:19    Sep 23 2025 19:35:39
202112211800        Done    Sep 23 2025 18:01:03    Sep 23 2025 23:05:46
******** C96C48hybatmDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96C48_hybatmDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Sep 23 2025 13:15:24    Sep 23 2025 13:35:34
202112210000        Done    Sep 23 2025 13:15:24    Sep 23 2025 15:46:10
202112210600        Done    Sep 23 2025 13:15:24    Sep 23 2025 15:35:37
******** C96C48hybatmsnowDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96C48_hybatmsnowDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Sep 23 2025 13:10:39    Sep 23 2025 13:30:49
202112201800        Done    Sep 23 2025 13:10:39    Sep 23 2025 15:35:38
202112210000        Done    Sep 23 2025 13:10:39    Sep 23 2025 15:25:41
******** C96C48hybatmsoilDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96C48_hybatmsoilDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202205150600        Done    Sep 23 2025 13:10:18    Sep 23 2025 13:30:44
202205151200        Done    Sep 23 2025 13:10:18    Sep 23 2025 15:45:49
202205151800        Done    Sep 23 2025 13:10:18    Sep 23 2025 15:35:42
******** C96C48mx500S2SWcycgfs ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96C48mx500_S2SW_cyc_gfs
202112201800        gfs_prepoceanobs                   219202210                DEAD                 271         2          61.0
202112201800       gdas_prepoceanobs                   219202227                DEAD                 271         2          60.0
******** C96C48ufshybatmDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96C48_ufs_hybatmDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202402231800        Done    Sep 23 2025 13:10:21    Sep 23 2025 13:30:13
202402240000        Done    Sep 23 2025 13:10:21    Sep 23 2025 16:05:35
202402240600        Done    Sep 23 2025 13:10:21    Sep 23 2025 16:00:46
******** C96mx100S2S ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR//C96mx100_S2S
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
199405010000        Done    Sep 23 2025 13:10:26    Sep 23 2025 15:00:49
```

**Comment by DavidHuber-NOAA** [comment]
Thanks @EricSinsky-NOAA.  I will launch a parallel test of develop on WCOSS2 for a `C48mx500_3DVarAOWCDA` case.

**Comment by EricSinsky-NOAA** [comment]
@DavidHuber-NOAA The `gdas_prepoceanobs` task in the `C48mx500_hybAOWCDA` test has just passed after the relaunch. In my original tests, I believe I forgot to update the submodules after merging EMC/develop, which might have caused the original failures in those specific tasks. I'll keep the CI running on WCOSS2 and provide a status update when finished.

**Comment by EricSinsky-NOAA** [comment]
All tests on WCOSS2 passed. 

```
******** C48ATM ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48_ATM
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 25 2025 16:35:53    Sep 25 2025 17:45:49
******** C48mx5003DVarAOWCDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48mx500_3DVarAOWCDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Sep 25 2025 16:35:40    Sep 25 2025 16:55:43
202103250000        Done    Sep 25 2025 16:35:40    Sep 25 2025 18:25:38
******** C48mx500hybAOWCDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48mx500_hybAOWCDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Sep 25 2025 16:35:38    Sep 25 2025 16:55:43
202103250000        Done    Sep 25 2025 16:35:38    Sep 25 2025 18:10:56
******** C48S2SW ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48_S2SW
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 25 2025 16:35:34    Sep 25 2025 17:40:51
******** C48S2SWAgefs ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48_S2SWA_gefs
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 25 2025 16:35:39    Sep 25 2025 17:50:29
******** C48S2SWextended ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C48_S2SW_extended
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Sep 25 2025 16:35:35    Sep 25 2025 19:05:33
202103231800        Done    Sep 25 2025 16:35:35    Sep 25 2025 19:10:45
******** C96atm3DVarextended ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96_atm3DVar_extended
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Sep 25 2025 16:35:41    Sep 25 2025 16:55:37
202112210000        Done    Sep 25 2025 16:35:41    Sep 25 2025 21:30:52
202112210600        Done    Sep 25 2025 16:35:42    Sep 25 2025 22:25:44
202112211200        Done    Sep 25 2025 17:00:50    Sep 25 2025 23:45:52
202112211800        Done    Sep 25 2025 21:35:42    Sep 26 2025 02:30:47
******** C96C48hybatmDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96C48_hybatmDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Sep 25 2025 16:35:46    Sep 25 2025 16:55:50
202112210000        Done    Sep 25 2025 16:35:46    Sep 25 2025 19:15:54
202112210600        Done    Sep 25 2025 16:35:46    Sep 25 2025 19:15:54
******** C96C48hybatmsnowDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96C48_hybatmsnowDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Sep 25 2025 16:40:51    Sep 25 2025 17:00:58
202112201800        Done    Sep 25 2025 16:40:51    Sep 25 2025 19:25:33
202112210000        Done    Sep 25 2025 16:40:51    Sep 25 2025 19:15:42
******** C96C48hybatmsoilDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96C48_hybatmsoilDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202205150600        Done    Sep 25 2025 16:40:58    Sep 25 2025 17:10:56
202205151200        Done    Sep 25 2025 16:40:58    Sep 25 2025 19:25:47
202205151800        Done    Sep 25 2025 16:40:58    Sep 25 2025 19:35:52
******** C96C48mx500S2SWcycgfs ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96C48mx500_S2SW_cyc_gfs
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Sep 25 2025 16:41:06    Sep 25 2025 17:05:41
202112201800        Done    Sep 25 2025 16:41:06    Sep 25 2025 19:55:09
202112210000        Done    Sep 25 2025 16:41:06    Sep 25 2025 20:35:46
202112211800        Done    Sep 25 2025 17:10:43    Sep 25 2025 20:35:46
******** C96C48ufshybatmDA ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96C48_ufs_hybatmDA
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202402231800        Done    Sep 25 2025 16:40:45    Sep 25 2025 17:05:36
202402240000        Done    Sep 25 2025 16:40:45    Sep 25 2025 19:40:46
202402240600        Done    Sep 25 2025 16:40:45    Sep 25 2025 19:35:36
******** C96mx100S2S ********
/lfs/h2/emc/ens/noscrub/eric.sinsky/GEFS/expdir/issue3901/EXPDIR/C96mx100_S2S
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
199405010000        Done    Sep 25 2025 16:40:43    Sep 25 2025 18:30:50
```

**Comment by DavidHuber-NOAA** [comment]
Thanks for running the tests on WCOSS2 @EricSinsky-NOAA!  Merging.
