### PR TITLE
Fix separate threading for GFS and GDAS forecasts.

### LINKED ISSUE #610: Separate threading options for gdasfcst and gfsfcst
**Expected behavior**

When `nth_fv3` is different from `nth_fv3_gfs` in config.fv3, config.resources should reference those options when calculating forecast GFS and GDAS forecasts.

**Current behavior**

Only the `nth_fv3` variable is referenced on [line 211](https://github.com/NOAA-EMC/global-workflow/blob/d3028b9d8268028226f9c27800fcd6655e9e4bb8/parm/config/config.resources#L211), resulting in the same threading option for both GDAS and GFS forecasts.

**Machines affected**

S4, which will use different threading options for GDAS and GFS forecasts.

**To Reproduce**

Manually set `nth_fv3` to 2, `nth_fv3_gfs` to 1, then run `setup_expt.py` and `setup_workflow.py`.  The resulting .xml will use 2 threads for both the GFS and GDAS forecasts.

**Context**

This should only immediately affect users on S4.

**Detailed Description**

Moving the `nth_fcst` assignment into the `if` block [starting on line 192 of config.resources](https://github.com/NOAA-EMC/global-workflow/blob/d3028b9d8268028226f9c27800fcd6655e9e4bb8/parm/config/config.resources#L192) and adding an `else` will allow users to specify different threading options.

**Additional Information**

**Possible Implementation**

I will add the suggested fix momentarily.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
**Description**
This PR fixes separate threading options for GDAS and GFS forecasts (#610).  This is performed by keeping `nth_fcst_gfs` separate from `nth_fcst` and declaring the new variable `npe_node_fcst_gfs`.

**Type of change**

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

- [X] Cycled test on S4 using different threading options in config.fv3
- [X] Created XML workflows on Orion and Hera using different threading options in config.fv3

I have not tested this on WCOSS as I do not have access.
  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

File: ush/forecast_predet.sh [hunk 1]
```diff
@@ -122,7 +122,12 @@ FV3_GFS_predet(){
   #file and the value of npe_node_fcst is not correctly defined when using more than
   #one thread and sets NTHREADS_FV3=1 even when the number of threads is appropraitely >1
   #NTHREADS_FV3=${NTHREADS_FV3:-${NTHREADS_FCST:-${nth_fv3:-1}}}
-  NTHREADS_FV3=${nth_fv3:-1}
+  #Threading can be different for GFS and GDAS forecasts
```
Comment (WalterKolczynski-NOAA) [inline ush/forecast_predet.sh]: This should be set in the env file with the others. This whole block can go, as NTHREADS_FV3 is already set there too. I don't know why someone added it back in here, contrary to the comment directly above.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]
The WCOSS env file needs to be updated the same way as the others, even if you can't test it yourself.

File: ush/forecast_predet.sh (hunk 1 above)
Comment (DavidHuber-NOAA) [reply ush/forecast_predet.sh]: OK, I've deleted the block and retested on S4.

**Comment by DavidHuber-NOAA** [comment]
> The WCOSS env file needs to be updated the same way as the others, even if you can't test it yourself.

I have added the threading information to WCOSS_C.env and WCOSS_DELL_P3.env.

File: ush/forecast_predet.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply ush/forecast_predet.sh]: You need to add a new entry to the block in the env files you moved up to set nth_fv3=nth_fv3_gfs as well.

Comment (DavidHuber-NOAA) [reply ush/forecast_predet.sh]: I've added the nth_fv3_gfs assignment to all of the env files.  Thanks for the catch.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Confirmed this works on WCOSS-Dell
