### PR TITLE
[gfs.v17] Eliminate Wave Postprocessing Warnings and Suppress Creation of Empty Output Directories

### LINKED ISSUE #4641: Remove empty model/[ocean/ice]/input folders
### What is wrong?

The model/[ocean/ice]/input folders are empty and should be removed. 

### What should have happened?

No empty directories in COM 

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

develop & dev/gfsv17

### Steps to reproduce

Look at COM in any CI test. 

### Additional information

_No response_

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by AntonMFernando-NOAA**
# Description

- The wave postprocessing step should complete without warnings. This PR addresses issues that caused warnings during wave postprocessing, specifically impacting WCOSS2.

  Refs #4136 

- This PR also updates the workflow to avoid creating empty output directories such as `model`, `atmos`, `ocean`, `ice`, `wave`, `med`, `input` and `products`. This reduces clutter and ensures only directories with content are created. 

  Refs #4642  
  Resolves #4641 

- Note: Empty `bump` and `cyclone track` directories are still created. These will be addressed in a separate PR, which will require updates to the GDAS App and TC_Tracker files.
- These issues have been addressed in the develop branch by #[4752](https://github.com/NOAA-EMC/global-workflow/pull/4752).
# Type of change
- [ ] Bug fix (fixes something broken)
- [x] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this change expected to change outputs (e.g. value changes to existing outputs, new files stored in COM, files removed from COM, filename changes, additions/subtractions to archives)? NO (If YES, please indicate to which system(s))
  - [ ] GFS
  - [ ] GEFS
  - [ ] SFS
  - [ ] GCAFS
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?
- Run the global workflow with the C48_S2SW configuration and review the gfs_wavepostsbs_f*.log files on WCOSS2 to confirm that wavepostsbs job warnings are resolved.
- Test this branch on WCOSS2 and compare the results with the develop branch to confirm that the only difference is the absence of empty directories.

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Comment by AntonMFernando-NOAA** [comment]
Tests on WCOSS2 all passed.
`/lfs/h2/emc/stmp/anton.fernando/RUNTESTS/COMROOT`

```
  commit: e2d7d374   branch: feature/gfsv17-feature-empty_com
  forked from: dev/gfs.v17  (+4 commits)
  build: up to date
  submodules: up to date
Tue Apr 21 12:52:29 UTC 2026
******** C48_ATM_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Apr 20 2026 16:40:11    Apr 20 2026 17:30:50

******** C48mx500_3DVarAOWCDA_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Apr 20 2026 16:40:13    Apr 20 2026 16:55:31
202103250000        Done    Apr 20 2026 16:40:13    Apr 20 2026 18:15:11

******** C48mx500_hybAOWCDA_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241800        Done    Apr 20 2026 16:40:11    Apr 20 2026 16:55:16
202103250000        Done    Apr 20 2026 16:40:11    Apr 20 2026 18:00:12

******** C48_S2SW_extended_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Apr 20 2026 16:44:13    Apr 20 2026 20:40:18
202103231800        Done    Apr 20 2026 16:44:13    Apr 20 2026 20:15:15

******** C96_atm3DVar_extended_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Apr 20 2026 16:44:16    Apr 20 2026 17:00:11
202112210000        Done    Apr 20 2026 16:44:16    Apr 20 2026 21:30:15
202112210600        Done    Apr 20 2026 16:44:16    Apr 20 2026 22:20:45
202112211200        Done    Apr 20 2026 17:05:15    Apr 20 2026 23:50:17
202112211800        Done    Apr 20 2026 21:35:12    Apr 21 2026 02:25:16

******** C96C48_hybatmDA_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Apr 20 2026 16:40:10    Apr 20 2026 16:55:14
202112210000        Done    Apr 20 2026 16:40:10    Apr 20 2026 20:10:20
202112210600        Done    Apr 20 2026 16:40:10    Apr 20 2026 20:00:20

******** C96C48_hybatmsnowDA_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Apr 20 2026 16:44:00    Apr 20 2026 17:00:12
202112201800        Done    Apr 20 2026 16:44:00    Apr 20 2026 20:10:18
202112210000        Done    Apr 20 2026 16:44:00    Apr 20 2026 20:00:12

******** C96C48_hybatmsoilDA_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202205150600        Done    Apr 20 2026 16:44:02    Apr 20 2026 17:00:22
202205151200        Done    Apr 20 2026 16:44:02    Apr 20 2026 20:10:20
202205151800        Done    Apr 20 2026 16:44:02    Apr 20 2026 20:05:15

******** C96C48mx500_S2SW_cyc_gfs_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201200        Done    Apr 20 2026 16:44:04    Apr 20 2026 17:00:19
202112201800        Done    Apr 20 2026 16:44:04    Apr 20 2026 20:10:27
202112210000        Done    Apr 20 2026 16:44:04    Apr 20 2026 20:25:39
202112211800        Done    Apr 20 2026 17:05:12    Apr 20 2026 20:35:16

******** C96mx100_S2S_t ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
199405010000        Done    Apr 20 2026 16:44:11    Apr 20 2026 18:15:15
```

**Comment by AntonMFernando-NOAA** [comment]
However, the `Warning: g2lib/g2clib complex encode/decode` still shows up. Investigating..
see: `/lfs/h2/emc/stmp/anton.fernando/RUNTESTS/COMROOT/C48_S2SW_extended_t/logs/2021032312/gfs_wavepostsbs_f000-f008.log`
```
+ wave_grib2_sbs.sh[113]wgrib2 gfs.t12z.epacif.0p16.f000.grib2.tmp -set_grib_type c2 -grib gfs.t12z.epacif.0p16.f000.grib2
Warning: g2lib/g2clib complex encode/decode may differ from WMO standard, use -g2clib 0 for WMO standard
Warning: g2lib/g2clib complex encode/decode may differ from WMO standard, use -g2clib 0 for WMO standard
Warning: g2lib/g2clib complex encode/decode may differ from WMO standard, use -g2clib 0 for WMO standard

**Comment by JessicaMeixner-NOAA** [comment]
I need to test one thing and possibly make a change for the grib2 output for waves, so I vote we merge this for now and circle back next week.

**Comment by AntonMFernando-NOAA** [comment]
> I need to test one thing and possibly make a change for the grib2 output for waves, so I vote we merge this for now and circle back next week.

Great! I will open this for full reviews now. Thank you!

**Review by JessicaMeixner-NOAA — APPROVED** [review]

File: ush/forecast_postdet.sh [hunk 1]
```diff
@@ -340,6 +340,7 @@ EOF
         FV3_RESTART_FH="$(seq -s ' ' "${restart_interval_start}" "${restart_interval}" "${restart_interval_end}")"
     fi
     export FV3_RESTART_FH
+    if [[ -n "${FV3_RESTART_FH}" ]]; then mkdir -p "${DATArestart}/FV3_RESTART"; fi
```
Comment (DavidHuber-NOAA) [inline ush/forecast_postdet.sh]: Prefer this on multiple lines


```suggestion
    if [[ -n "${FV3_RESTART_FH}" ]];
        then mkdir -p "${DATArestart}/FV3_RESTART"
    fi
```

File: dev/scripts/exglobal_enkf_sfc_gcycle.sh [hunk 2]
```diff
@@ -174,7 +174,7 @@ if [[ "${DOIAU}" == "YES" ]]; then
             fi
 
             if [[ ${TILE_NUM} -eq 1 ]]; then
-                mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"
+                if [[ ! -d "${COMOUT_ATMOS_RESTART_MEM}" ]]; then mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"; fi
```
Comment (DavidHuber-NOAA) [inline dev/scripts/exglobal_enkf_sfc_gcycle.sh]:
```suggestion
                if [[ ! -d "${COMOUT_ATMOS_RESTART_MEM}" ]]; then
                    mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"
                fi
```

File: dev/scripts/exglobal_enkf_sfc_gcycle.sh [hunk 3]
```diff
@@ -207,7 +207,7 @@ if [[ "${DOIAU}" == "YES" ]]; then
             declare -x COMOUT_ATMOS_RESTART_MEM=${ROTDIR}/${RUN}.${PDY}/${cyc}/${memchar}/model/atmos/restart
 
             if [[ ${TILE_NUM} -eq 1 ]]; then
-                mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"
+                if [[ ! -d "${COMOUT_ATMOS_RESTART_MEM}" ]]; then mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"; fi
```
Comment (DavidHuber-NOAA) [inline dev/scripts/exglobal_enkf_sfc_gcycle.sh]:
```suggestion
                if [[ ! -d "${COMOUT_ATMOS_RESTART_MEM}" ]]; then
                    mkdir -p "${COMOUT_ATMOS_RESTART_MEM}"
                fi
```

File: ush/forecast_postdet.sh [hunk 4]
```diff
@@ -1076,6 +1103,7 @@ CMEPS_out() {
     esac
 
     if [[ -s "${cmdfile}" ]]; then
+        if [[ ! -d "${COMOUT_MED_RESTART}" ]]; then mkdir -p "${COMOUT_MED_RESTART}"; fi
```
Comment (DavidHuber-NOAA) [inline ush/forecast_postdet.sh]:
```suggestion
        if [[ ! -d "${COMOUT_MED_RESTART}" ]]; then
            mkdir -p "${COMOUT_MED_RESTART}"
        fi
```

File: ush/wave_grib2_sbs.sh [hunk 5]
```diff
@@ -98,14 +98,22 @@ if [[ ! -s gribfile ]]; then
...
+    err=$?
+    [[ ${err} -eq 0 ]] && ${WGRIB2} "${outfiletmp}" -set_grib_type c2 -grib "${outfile}"
     err=$?
 else
     ${WGRIB2} gribfile -set_date "${PDY}${cyc}" -set_ftime "${fhr} hour fcst" \
-        -set table_1.4 1 -set table_1.2 1 -grib "${outfile}"
+        -set table_1.4 1 -set table_1.2 1 \
+        -set_grib_type simple -g2clib 0 -grib "${outfiletmp}"
+    err=$?
+    [[ ${err} -eq 0 ]] && ${WGRIB2} "${outfiletmp}" -set_grib_type c2 -grib "${outfile}"
```
Comment (DavidHuber-NOAA) [inline ush/wave_grib2_sbs.sh]: Should this exit if it fails? Please use if blocks instead of `&& ||` chains

```suggestion
    if [[ ${err} -eq 0 ]]; then
        ${WGRIB2} "${outfiletmp}" -set_grib_type c2 -grib "${outfile}"
    else
        echo "wgrib2 failed to create the intermediate file ${outfiletmp}"
        exit "${err}"
    fi
```

File: dev/scripts/exglobal_atmos_sfcanl_gcycle.sh [hunk 6]
```diff
@@ -160,7 +160,10 @@ for hr in "${!gcycle_dates[@]}"; do
 
     # Copy outputs from DATA to COMOUT
     for ((nn = 1; nn <= ntiles; nn++)); do
-        cpfs "${DATA}/sfc_data_cycle.00${nn}" "${COMOUT_ATMOS_RESTART}/${datestr}.sfcanl_data.tile${nn}.nc"
+        if [[ -f "${DATA}/sfc_data_cycle.00${nn}" ]]; then
+            [[ -d "${COMOUT_ATMOS_RESTART}" ]] || mkdir -p "${COMOUT_ATMOS_RESTART}"
```
Comment (DavidHuber-NOAA) [inline dev/scripts/exglobal_atmos_sfcanl_gcycle.sh]:
```suggestion
            if [[ ! -d "${COMOUT_ATMOS_RESTART}" ]]; then
                mkdir -p "${COMOUT_ATMOS_RESTART}"
            fi
```

**Comment by DavidHuber-NOAA** [comment]
Launching tests on WCOSS2.

File: ush/wave_grib2_sbs.sh [hunk 7]
```diff
@@ -98,14 +98,27 @@ if [[ ! -s gribfile ]]; then
     exit 2
 fi
 
+outfiletmp="${outfile}.tmp"
 if [[ ${fhr} -gt 0 ]]; then
-    ${WGRIB2} gribfile -set_date "${PDY}${cyc}" -set_ftime "${fhr} hour fcst" -grib "${outfile}"
+    ${WGRIB2} gribfile -set_date "${PDY}${cyc}" -set_ftime "${fhr} hour fcst" \
+        -set_grib_type simple -g2clib 0 -grib "${outfiletmp}"
+    err=$?
+    [[ ${err} -eq 0 ]] && ${WGRIB2} "${outfiletmp}" -set_grib_type c2 -grib "${outfile}"
```
Comment (DavidHuber-NOAA) [inline ush/wave_grib2_sbs.sh]: One last location:


```suggestion
    if [[ ${err} -eq 0 ]]; then
        ${WGRIB2} "${outfiletmp}" -set_grib_type c2 -grib "${outfile}"
    else
        echo "wgrib2 failed to create the file ${outfile}"
        exit "${err}"
    fi
```

**Review by DavidHuber-NOAA — APPROVED** [review]

**Comment by DavidHuber-NOAA** [comment]
All tests passed on WCOSS2.

**Comment by DavidHuber-NOAA** [comment]
Merging.

**Comment by JessicaMeixner-NOAA** [comment]
Quick question @AntonMFernando-NOAA  - - Where are the wave post processing warnings?  I'm looking in: /lfs/h2/emc/gfstemp/emc.global/comroot/retrov17_01_realtime/logs which does not yet include your PR, and I'm not finding them like @mingchen-NOAA  and I saw earlier and reported in https://github.com/NOAA-EMC/global-workflow/issues/4136 -- but maybe I'm just overlooking them?

**Comment by AntonMFernando-NOAA** [comment]
> Quick question @AntonMFernando-NOAA - - Where are the wave post processing warnings? I'm looking in: /lfs/h2/emc/gfstemp/emc.global/comroot/retrov17_01_realtime/logs which does not yet include your PR, and I'm not finding them like @mingchen-NOAA and I saw earlier and reported in #4136 -- but maybe I'm just overlooking them?

@JessicaMeixner-NOAA I don't see it either. Just checked. Kind of confused now.

**Comment by JessicaMeixner-NOAA** [comment]
Okay - thank you for confirming!
