### PR TITLE
Remove need for a ice_prod dependency check script 

### LINKED ISSUE #2721: Update dependency check for ice netcdf file for GEFS
### What is wrong?

#2561 introduced a dependency check for ice netcdf file for GEFS via the use of [this](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/check_ice_netcdf.sh) script.  Rocoto provides an option for checking if the file exists together with the age of the file and should be utilized instead of this script.

### What should have happened?

Use Rocoto `<datadep age=120>` to check if the file exists and is older than 2 mins, instead of calling a script via `<sh>` command.

### What machines are impacted?

All or N/A

### Steps to reproduce

Create the xml and look at the gefs ice product dependency section.

### Additional information

None

### Do you have a proposed solution?

Use Rocoto's `datadep` tag to check for dependencies.

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
# Description

The main purpose of this PR is to remove the need for an ice_prod dependency check script `ush/check_ice_netcdf.sh`. The original purpose of the ice_prod dependency check script is to check for special case dependencies where `( cyc + FHMIN ) % FHOUT_ICE )) =! 0` (more details on this issue can be found in issue #2674 ). A bugfix for these special cases is expected to come from a PR in the ufs-weather-model. 

Resolves #2721 
Refs #2721, #2674  

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

- Clone, built and tested on WCOSS2. 
- In the WCOSS2 test, `FHOUT_OCN` and `FHOUT_ICE` was set to `24` and the GEFS CI case was successfully tested (202103232 12Z). 
- TODO: Perform test cases with `FHOUT_OCN` and `FHOUT_ICE` set to `6`.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: ush/forecast_postdet.sh [hunk 1]
```diff
@@ -628,6 +628,36 @@ CICE_out() {
 
 }
 
+CICE_avg() {
+  if (( CICE_cdoavg == 0 )); then
+    echo "SUB ${FUNCNAME[0]}: No further averaging needed for CICE"
+  else
+    echo "SUB ${FUNCNAME[0]}: Averaging output data for CICE"
+    CDO=/apps/prod/hpc-stack/intel-19.1.3.304/cdo/1.9.8/bin/cdo
```
Comment (EricSinsky-NOAA) [inline ush/forecast_postdet.sh]: If we choose to use the cdo utility for this, it may need to be added somewhere in `jobs/JGLOBAL_FORECAST`. This line is just a temporary workaround for the cdo utility being undefined in the forecast task environment.

Comment (WalterKolczynski-NOAA) [reply ush/forecast_postdet.sh]: The cdo binary directory is already added to the path by the cdo module. You should be able to just call it with `cdo` without this.

Comment (WalterKolczynski-NOAA) [reply ush/forecast_postdet.sh]: NB: We have it in the base modulefile used for most jobs, but the model modulefile isn't loading cdo, so it would need to be added to [load_ufswm_modules.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/load_ufswm_modules.sh).

Comment (EricSinsky-NOAA) [reply ush/forecast_postdet.sh]: Thanks, @WalterKolczynski-NOAA. Will module load cdo in [load_ufswm_modules.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/load_ufswm_modules.sh).

**Comment by EricSinsky-NOAA** [comment]
Bugfix has been removed for special cases where  `( cyc + FHMIN ) % FHOUT_ICE )) =! 0` in commit fcb9003f44892656a05ab7b82f58c1e0107f0753. This bug is expected to be fixed in ufs_weather_model [PR #2437](https://github.com/ufs-community/ufs-weather-model/pull/2437). 
The primary purpose of this PR is to remove ice_prod dependency check script and any temporary bugfixes associated with special cases where  `( cyc + FHMIN ) % FHOUT_ICE )) =! 0`. 
Testing GEFS replay and non-replay cases. This PR will be marked ready for review when these tests pass.

**Comment by EricSinsky-NOAA** [comment]
Marking this PR as ready for review. GEFS replay (`FHOUT_GFS_ICE=24`, `cyc=00`) and non-replay test cases (`FHOUT_GFS_ICE=6`, `cyc=12`) have passed.

File: workflow/rocoto/gefs_tasks.py [hunk 2]
```diff
@@ -219,11 +219,6 @@ def _atmosoceaniceprod(self, component: str):
             dep_dict = {'type': 'metatask', 'name': 'fcst_mem#member#'}
             deps.append(rocoto.add_dependency(dep_dict))
             dependencies = rocoto.create_dependency(dep=deps, dep_condition='or')
-        elif component in ['ice']:
-            command = f"{self.HOMEgfs}/ush/check_ice_netcdf.sh @Y @m @d @H #fhr# &ROTDIR; #member# {fhout_ice_gfs}"
-            dep_dict = {'type': 'sh', 'command': command}
-            deps.append(rocoto.add_dependency(dep_dict))
-            dependencies = rocoto.create_dependency(dep=deps)
```
Comment (WalterKolczynski-NOAA) [inline workflow/rocoto/gefs_tasks.py:226]: Should ice be added to the `if` rather than the `else`so it doesn't begin pre-maturely?

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: workflow/rocoto/gefs_tasks.py (hunk 2 above)
Comment (EricSinsky-NOAA) [reply workflow/rocoto/gefs_tasks.py:226]: You are right. After looking at this further, it looks like there is no need for an if-statement, since the atmos_prod, ocean_prod and ice_prod dependencies are structured the same way (all checking for the existence of a history file or the completion of a fcst metatask). I set this up similar to how the ocn/ice/atmos prod dependencies are set up in `workflow/rocoto/gfs_tasks.py`. These changes have been pushed.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by aerorahul — APPROVED** [review]
looks good to me.
thanks for taking out the shell script dependency checker.
It was causing significant delays executing rocoto-stuff for long forecasts (SFS).

**Comment by WalterKolczynski-NOAA** [comment]
Ignore the Orion failure. We already know what that is.
