### PR TITLE
Fix a few bugs reported by devs

### LINKED ISSUE #1796: Task gdafcst failed on C384 snow DA cycling run
I'm running the C384 snow DA cycling tests, and the run starts at t18z 2011-10-30. When running to the t00z 2011-11-07, the task `gdasfcst` failed with the following error messages:

```
++ forecast_predet.sh[71]: date -d '20211107 00 + 6 hours' +%Y%m%d%H
+ forecast_predet.sh[71]: next_cycle=2021110705
++ forecast_predet.sh[72]: date -d '20211107 00 + 9 hours' +%Y%m%d%H
+ forecast_predet.sh[72]: forecast_end_cycle=2021110708
```
```
++ forecast_postdet.sh[508]: date -d '20211107 00 + 6 hours' +%Y%m%d%H
+ forecast_postdet.sh[508]: local idate=2021110705
```
It should produce the `local idate=2021110706`. All previous `gdasfcst` tasks work successfully. The log file is  at `/scratch1/NCEPDEV/ctb/Jiarui.Dong/ptmp/landid9/logs/2021110700/gdasfcst.log` on hera.

### PR DESCRIPTION
**Pull request by aerorahul**
# Description

This PR fixes a few bugs that were reported by developers:
- a namelist section is unclosed in `parsing_namelists_FV3.sh`
- resolution is not being properly cut from `CASE`
- date should be in UTC to properly go back and forth around DST dates. 
 
Resolves #1796 

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Except for the `date` change, CI should be able to validate the other changes.
The date change needs to be tested around a DST date that was encountered by @jiaruidong2017.  @jiaruidong2017 would you be able to test the updates against the date you reported the bug?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending successful CI.

**Comment by jiaruidong2017** [comment]
Thanks @aerorahul for the fix. I will test it, but it will need some time.

**Comment by aerorahul** [comment]
> Thanks @aerorahul for the fix. I will test it, but it will need some time.
That is fine.  Let us know if you want us to hold this PR until you can test and report status.

**Comment by jiaruidong2017** [comment]
> > Thanks @aerorahul for the fix. I will test it, but it will need some time.
> > That is fine.  Let us know if you want us to hold this PR until you can test and report status.

@aerorahul Go ahead to merge it, and I can test it from develop branch. If I find any issue, I will report it to you. Thanks.

**Review by jiaruidong2017 — APPROVED** [review]
It worked across the DST on 11/07/2021.

File: ush/forecast_postdet.sh [hunk 1]
```diff
@@ -809,7 +809,7 @@ MOM6_postdet() {
   esac
 
   # Loop over restart_interval frequency and link restarts from DATA to COM
-  local idate=$(date -d "${current_cycle:0:8} ${current_cycle:8:2} + ${restart_interval} hours" +%Y%m%d%H)
+  local idate=$(date --utc -d "${current_cycle:0:8} ${current_cycle:8:2} + ${restart_interval} hours" +%Y%m%d%H)
   while [[ ${idate} -lt ${forecast_end_cycle} ]]; do
     local idatestr=$(date +%Y-%m-%d-%H -d "${idate:0:8} ${idate:8:2}")
```
Comment (DavidHuber-NOAA) [inline ush/forecast_postdet.sh:814]: Should this also have --utc?

File: ush/forecast_predet.sh
Comment (DavidHuber-NOAA) [inline ush/forecast_predet.sh:1]: Line 32 should probably also have --utc:

`local mid_date=$(date -d --utc "${date1:0:8} ${date1:8:2} + ${dtsecsby2} seconds" +%Y%m%d%H%M%S)`

**Comment by jiaruidong2017** [comment]
@aerorahul Please add `--utc` to all `GDATE` under the `jobs/` directory to this PR. An example for snow DA is as below: 

At: `jobs/JGLOBAL_LAND_ANALYSIS`
Change: 
GDATE=$(date +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
To: 
GDATE=$(date +%Y%m%d%H `--utc` -d "${PDY} ${cyc} - ${assim_freq} hours")

File: ush/nems_configure.sh [hunk 2]
```diff
@@ -56,7 +56,7 @@ if [[ "${cplflx}" = ".true." ]]; then
   local CPLMODE="${cplmode}"
   local coupling_interval_fast_sec="${CPL_FAST}"
   local RESTART_N="${restart_interval}"
-  local ATMTILESIZE="${CASE:2:}"
+  local ATMTILESIZE="${CASE:1}"
```
Comment (DavidHuber-NOAA) [inline ush/nems_configure.sh:59]: Is there an issue open for this bug that should be added to the PR?

File: ush/parsing_namelists_FV3.sh [hunk 3]
```diff
@@ -422,6 +422,11 @@ if [[ ${DO_LAND_PERT:-"NO"} = "YES" ]]; then
 EOF
 fi
 
+# Close &gfs_physics_nml section
```
Comment (DavidHuber-NOAA) [inline ush/parsing_namelists_FV3.sh:425]: Is there an issue open for this bug that should be added to the PR?

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
It looks like there are a couple places where `--utc` may need to be added.  Also wondering if the bugs in nems_configure.sh and parsing_namelists_FV3.sh have their own issues that should be added to the PR description.

File: ush/forecast_postdet.sh (hunk 1 above)
Comment (aerorahul) [reply ush/forecast_postdet.sh:814]: This is a simple format change and so does not need the `--utc` option.
When datetime is being advanced forward/backward, we should use the `--utc` option.

File: ush/forecast_predet.sh
Comment (aerorahul) [reply ush/forecast_predet.sh:1]: yes it should.  thanks for catching this.

File: ush/nems_configure.sh (hunk 2 above)
Comment (aerorahul) [reply ush/nems_configure.sh:59]: No issue.  It was identified in the PR #1865 opened by @rmontuoro 
Since that PR will not be merged, I just pulled the fix out from that PR.
Same with the bug in `parsing_namelists_FV3.sh`

File: ush/parsing_namelists_FV3.sh (hunk 3 above)
Comment (aerorahul) [reply ush/parsing_namelists_FV3.sh:425]: No issue exists for this bug.  It is being pulled from PR #1865

**Comment by aerorahul** [comment]
> @aerorahul Please add `--utc` to all `GDATE` under the `jobs/` directory to this PR. An example for snow DA is as below:
> 
> At: `jobs/JGLOBAL_LAND_ANALYSIS` Change: GDATE=$(date +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours") To: GDATE=$(date +%Y%m%d%H `--utc` -d "${PDY} ${cyc} - ${assim_freq} hours")

Good catch @jiaruidong2017 
I have updated all the j-jobs where `date` is being used to compute `GDATE`.

File: ush/forecast_postdet.sh (hunk 1 above)
Comment (DavidHuber-NOAA) [reply ush/forecast_postdet.sh:814]: OK, that makes sense given this is solving a DST issue.

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
I found just one additional location in [scripts/exglobal_stage_ic.sh:7](https://github.com/aerorahul/global-workflow/blob/63bc50fcdda3df9b4e624d197d4291b70fc8441c/scripts/exglobal_stage_ic.sh#L7):
`GDATE=$(date -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)`

**Comment by aerorahul** [comment]
> I found just one additional location in [scripts/exglobal_stage_ic.sh:7](https://github.com/aerorahul/global-workflow/blob/63bc50fcdda3df9b4e624d197d4291b70fc8441c/scripts/exglobal_stage_ic.sh#L7): `GDATE=$(date -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)`

got it.  thanks!
That should be all I think.  I did a grep across the global-workflow.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good, thanks!

**Review by jiaruidong2017 — APPROVED** [review]
