### PR TITLE
Fix incorrect usage of CFP on WCOSS2

### LINKED ISSUE #1948: GFS Post  PGRB Process on WCOSS2 Takes a longer time
### What is wrong?

The GFS Post PGRB process take more than 5 minutes on WCOSS2. It seems the CFP (MPMD) wasn't launched. 

### What should have happened?

The normal GFS PGRB process is expected within 2 minutes.

### What machines are impacted?

WCOSS2

### Steps to reproduce

checkout the develop branch and run the experiment including gfs post process for generating pgrb2/pgrb2b datasets.  

### Additional information

Check runtime log gfs_post*

### Do you have a proposed solution?

Add a line "launcher=$APRUN_DWN" before "chmod 755 ""${mpmd_cmdfile}" in ush/run_mpmd.sh

APRUN_DWN="mpiexec -np 24 -cpu-bind verbose,core cfp"

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
This PR:
- fixes the use of CFP on WCOSS2.  This was seen by @WenMeng-NOAA and documented in #1948 

Fixes #1948 

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Hera and Orion are not impacted by this change.
This change is not tested on WCOSS2 in the CI, so a test of the gfs/gdas post job on WCOSS2 should suffice for this PR to be accepted.

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: ush/run_mpmd.sh [hunk 1]
```diff
@@ -42,7 +44,8 @@ elif [[ "${launcher:-}" =~ ^mpiexec.* ]]; then  # mpiexec
   done < "${cmdfile}"
 
   chmod 755 "${mpmd_cmdfile}"
-  ${launcher:-} "${mpmd_cmdfile}"
+  # shellcheck disable=SC2086
+  ${launcher:-} -np ${nprocs} ${mpmd_out:-} "${mpmd_cmdfile}"
```
Comment (aerorahul) [inline ush/run_mpmd.sh]:
```suggestion
  ${launcher:-} -np ${nprocs} ${mpmd_opt:-} "${mpmd_cmdfile}"
```
Fix typo.

**Comment by KateFriedman-NOAA** [comment]
Edit (with typo fixed) appears to work. I tested it in a rerun post job in an ongoing test on WCOSS2. I am now letting my test with the edit run another cycle to further confirm the change to `ush/run_mpmd.sh` is good-to-go on the first attempt of each post job. Will report back.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
Change looks good:
```
kate.friedman@dlogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testmonitor2> grep cfp logs/2021122106/gfspost_f006.log | grep mpiexec | grep -v APRUN_DWN                    
+ run_mpmd.sh[48](/lfs/h2/emc/stmp/kate.friedman/RUNDIRS/testmonitor2/post.63952/poescript): mpiexec -l -np 24 --cpu-bind verbose,core cfp /lfs/h2/emc/stmp/kate.friedman/RUNDIRS/testmonitor2/post.63952/mpmd_cmdfile
+ run_mpmd.sh[48](/lfs/h2/emc/stmp/kate.friedman/RUNDIRS/testmonitor2/post.63952/poescript): mpiexec -l -np 24 --cpu-bind verbose,core cfp /lfs/h2/emc/stmp/kate.friedman/RUNDIRS/testmonitor2/post.63952/mpmd_cmdfile
```

The post jobs are running much faster now with cfp working correctly on WCOSS2 (e.g. 79s with fix vs 472s before fix):
```
kate.friedman@dlogin07:/lfs/h2/emc/global/noscrub/kate.friedman/expdir/testmonitor2> rocotostat -d testmonitor2.db -w testmonitor2.xml | grep gfspost_f006                
202112210000            gfspost_f006                   107292233           SUCCEEDED                   0         1         472.0
202112210600            gfspost_f006                   107312491           SUCCEEDED                   0         1          79.0
```

@aerorahul @WenMeng-NOAA here is one of the logs on Dogwood in case you'd like to take a look: `/lfs/h2/emc/ptmp/kate.friedman/comrot/testmonitor2/logs/2021122106/gfspost_f006.log`

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good. Approving now that successful testing on WCOSS2 has occurred. Thanks @aerorahul !
