### PR TITLE
Additional fixes for downstream jobs

### LINKED ISSUE #3019: Post processing errors resulting from GFS HR4 test run
### What is wrong?

From a test run of GFS HR4 performed by @RuiyuSun, execution of the post processing package is included, and the following log files indicated the following errors:

```
gfsarch.log:  FATAL ERROR: Required file, directory, or glob gfs.20201030/00/products/atmos/wmo/gfs_collective1.postsnd_00 not found!
gfsawips_20km_1p0deg_f###-f###.log:  End exgfs_atmos_awips_20km_1p0deg.sh ... with error code 30
gfswaveawipsbulls.log:  FATAL ERROR: Job waveawipsbulls.95602 failed RETURN CODE 4
gfswaveawipsgridded.log: End exgfs_wave_prdgen_gridded.sh ... with error code 1
```

### What should have happened?

The post processing scripts should all have run to completion without error or interruption.

### What machines are impacted?

WCOSS2

### What global-workflow hash are you using?

https://github.com/NOAA-EMC/global-workflow/commit/4ad96952f0bccaedad3e9c558341fe5e28d813aa

### Steps to reproduce

Clone and build the workflow code from the indicated hash on WCOSS, then execute a single cycle (2020103000) that points to datasets available from the HR4 test case.  Please consult @RuiyuSun for more specifications.

### Additional information

Errors from _gfswaveawipsbulls_ and _gfswaveawipsgridded_ appear to result from a misread of Alaska buoy station information, and these scripts within the workflow may require reference to an updated table that links stations to expected data bulletins.  @AminIlia-NOAA is added here for reference to the issue and the attached log files.
[gfswaveawipsbulls.log](https://github.com/user-attachments/files/17441162/gfswaveawipsbulls.log)
[gfswaveawipsgridded.log](https://github.com/user-attachments/files/17441163/gfswaveawipsgridded.log)

Errors resulting from _gfsfbwind_ and _gfsgempakncdcupagif_ are being assessed for potential inclusion with this issue.

### Do you have a proposed solution?

The GETGB2P errors generated from _gfsawips_20km_1p0deg_ - as seen in [OUTPUT70005.txt](https://github.com/user-attachments/files/17441207/OUTPUT70005.txt) - result from the absence of GRIB variable 5WAVH from the GFS control file, and appear related to those resolved through https://github.com/NOAA-EMC/global-workflow/pull/2652; the relevant parameter tables will be modified in a similar manner.  Resolution of errors from _gfsawips_20km_1p0deg_ may subsequently resolve the absence of files causing the _gfsarch_ error.

Once developed, the modifications resolving all errors described here will be bundled into one or two pull requests.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This fixes a number of issues with the `postsnd` and `arch` jobs discovered during testing of HR4.

Resolves #3019

# Type of change
- [x] Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES
  - [x] GFS-utils NOAA-EMC/gfs-utils#90

# How has this been tested?
- [x] Extended test on Hera
- [x] Extended test on WCOSS2

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
   - Portions of this change are covered by existing CI, but others are not (e.g. archiving, which is disabled on WCOSS2)
   - Updates will need to be made to run the `AWIPS` jobs in the existing `C96_atm3DVar_extended` test

### CODE REVIEW

File: ush/gfs_bufr.sh [hunk 1]
```diff
@@ -21,11 +21,12 @@
 # 2024-08-08 Bo Cui: Update to handle one forecast at a time
 # echo "History: February 2003 - First implementation of this utility script"
 #
-fhr="$1"
-fhr_p="$2"
-FINT="$3"
-F00FLAG="$4"
-workdir="$5"
+set -x
```
Comment (WalterKolczynski-NOAA) [inline ush/gfs_bufr.sh]: source preamble instead

**Comment by DavidHuber-NOAA** [comment]
All post jobs now run for the `C96_atm3dvar_extended` test when `DO_AWIPS=YES` on WCOSS2.  I have thus enabled AWIPS for this test to ensure the AWIPS jobs and linked downstream jobs are always run to avoid lapses in support.

The AWIPS jobs still cannot be enabled on other machines due to the fbwinds executable which currently only runs on WCOSS2.  That will be an issue for another time.

Also, during this testing, I found that the MOS jobs, when enabled, do not run on WCOSS2.  I opened issue #3196 to look into this, but I believe the MOS package will need an overhaul to work with the new COM structure.

Marking this PR ready for review.

File: workflow/applications/gfs_cycled.py [hunk 2]
```diff
@@ -119,7 +119,7 @@ def _get_app_configs(self, run):
             configs += ['postsnd']
 
         if options['do_awips']:
-            configs += ['awips']
+            configs += ['awips', 'fbwind']
```
Comment (aerorahul) [inline workflow/applications/gfs_cycled.py:122]: Should `workflow/applications/gfs_forecast_only.py` [line 64](https://github.com/DavidHuber-NOAA/global-workflow/blob/28e77758a3fec00b650577952f8e63307b1245fa/workflow/applications/gfs_forecast_only.py#L64) also add `fbwind` when `do_awips` is `True`?

**Review by aerorahul — COMMENTED** [review]
Looks good to me.  Just one observation.  Approve.

File: workflow/applications/gfs_cycled.py (hunk 2 above)
Comment (DavidHuber-NOAA) [reply workflow/applications/gfs_cycled.py:122]: Hmm, good question.  I'll give it a test run.

Comment (aerorahul) [reply workflow/applications/gfs_cycled.py:122]: i am good without this change, was just checking

Comment (DavidHuber-NOAA) [reply workflow/applications/gfs_cycled.py:122]: Sorry, this slipped through the cracks.  `fbwind` should indeed be sourced when generating a forecast-only experiment and `DO_AWIPS=YES`.

**Review by WalterKolczynski-NOAA — DISMISSED** [review]

**Review by aerorahul — APPROVED** [review]
lgtm.

**Review by aerorahul — DISMISSED** [review]

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
Can you please run the ci on wcoss2?

**Comment by DavidHuber-NOAA** [comment]
Running CI in `/lfs/h2/emc/global/noscrub/David.Huber/RT/3187`.

**Comment by DavidHuber-NOAA** [comment]
All CI tests completed successfully.  However, I ran a `C48_S2SW` test case with `DO_AWIPS`, `DO_GEMPAK`, `DO_GOES`, `DO_BUFRSND`, and `DO_NPOESS` all set to `YES`, and discovered a number of failures in gempak and awips jobs.  Converting back to draft while I resolve these issues.

**Comment by DavidHuber-NOAA** [comment]
@ChristopherHill-NOAA @RuiyuSun I have made several fixes and performed limited testing for the `gfs_gempakncdcupapgif` job.  Could you please try running this branch for your HR4 test?  Note that this requires an update to and rebuild of the gfs_utils submodule.

**Comment by ChristopherHill-NOAA** [comment]
> @ChristopherHill-NOAA @RuiyuSun I have made several fixes and performed limited testing for the `gfs_gempakncdcupapgif` job. Could you please try running this branch for your HR4 test? Note that this requires an update to and rebuild of the gfs_utils submodule.

In addition to fixes pertaining to `gfs_gempakncdcupapgif`, it is noted that `parm/config/gfs/config.resources` was revised to include `tasks_per_node=1` for the fbwind case module, which should allow `gfs_fbwind` to run without error.  @RuiyuSun From your next test of the GFSv17 workflow - based on fixes from this PR - it is anticipated that the remaining post-processing errors may lie with `gfs_waveawipsbulls` and `gfs_waveawipsgridded`.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA @ChristopherHill-NOAA @RuiyuSun It appears that the `gfs_waveawipsbulls` job is failing because the `gfs_wavepostpnt` job does not produce all of the bulletins expected by the former.  The bulletins expected by the AWIPS job are included in `parm/wave/bull_awips_gfswave` and those that should be produced by the `gfs_wavepostpnt` job, I believe, are included in `parm/wave/wave_gfs.buoys`.  For example, buoy number 46001 is included in both files, but the resulting `cbull_tar` file from `gfs_wavepostpnt` does not include a bulletin for this buoy.

It's not perfectly clear to me if all of the buoys in `parm/wave/wave_gfs.buoys` end up in `cbull_tar`.  If not, then should `parm/wave/bull_awips_gfswave` be updated accordingly?  If so, is there another parm file I could reference to do so?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA @ChristopherHill-NOAA @RuiyuSun It appears that the `gfs_waveawipsbulls` job is failing because the `gfs_wavepostpnt` job does not produce all of the bulletins expected by the former. The bulletins expected by the AWIPS job are included in `parm/wave/bull_awips_gfswave` and those that should be produced by the `gfs_wavepostpnt` job, I believe, are included in `parm/wave/wave_gfs.buoys`. For example, buoy number 46001 is included in both files, but the resulting `cbull_tar` file from `gfs_wavepostpnt` does not include a bulletin for this buoy.
> 
> It's not perfectly clear to me if all of the buoys in `parm/wave/wave_gfs.buoys` end up in `cbull_tar`. If not, then should `parm/wave/bull_awips_gfswave` be updated accordingly? If so, is there another parm file I could reference to do so?

@DavidHuber-NOAA  apologies that you are running into this. I had shared with Amin about this.  I have a fix for this issue in WW3, but it will take a while for it to migrate to ufs-weather-model and the global-workflow.  I have made a run for Amin to use (I'm a few weeks behind in handing this over), and have finally made the run, but haven't checked things on my end yet.  That can be used as the up-stream input for further testing for this.

**Comment by RuiyuSun** [comment]
> @JessicaMeixner-NOAA @ChristopherHill-NOAA @RuiyuSun It appears that the `gfs_waveawipsbulls` job is failing because the `gfs_wavepostpnt` job does not produce all of the bulletins expected by the former. The bulletins expected by the AWIPS job are included in `parm/wave/bull_awips_gfswave` and those that should be produced by the `gfs_wavepostpnt` job, I believe, are included in `parm/wave/wave_gfs.buoys`. For example, buoy number 46001 is included in both files, but the resulting `cbull_tar` file from `gfs_wavepostpnt` does not include a bulletin for this buoy.
> 
> It's not perfectly clear to me if all of the buoys in `parm/wave/wave_gfs.buoys` end up in `cbull_tar`. If not, then should `parm/wave/bull_awips_gfswave` be updated accordingly? If so, is there another parm file I could reference to do so?

I will this code to set up a HRv4 like experiment.

**Comment by RuiyuSun** [comment]
I started a HR4 like experiment by using this code and fix/awips branch. I used build_all.sh to build the system. 

The experiment directory is at /lfs/h2/emc/physics/noscrub/ruiyu.sun/para_gfs/HRv4prodDH.
The GW is at /lfs/h2/emc/physics/noscrub/ruiyu.sun/git/global-workflow.git.dhuber.awips. 

@DavidHuber-NOAA @ChristopherHill-NOAA Please take a look at the G-W and configurations and let me know if you find anything wrong. Thanks!

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Thanks for the heads up!  I will be happy to jump back on this when the test case is available.

**Comment by DavidHuber-NOAA** [comment]
@RuiyuSun Looking closer at the `gfs_gempakncdcupapgif` job, it is still failing.  It has a data dependency on the `adpupa` upper air ~Fit2Obs~ obsproc output.  Thus, I don't think this job should be enabled in forecast-only mode ~and should only be triggered after a successful Fit2Obs run~.  I am going to make some changes to the Rocoto XML generation scripts to disable this job and retest my C48_S2SW case.  I'll let you know when this is ready to test again.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Thanks for the heads up! I will be happy to jump back on this when the test case is available.

@DavidHuber-NOAA @AminIlia-NOAA  This has the point output: 

/lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/station 
That should contain the info that you need for the wave product jobs.  This doesn't have the boundary pionts, which was an oversight on my part, but I don't think those are needed for any downstream jobs so that should be okay. 

This: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/gridded also should have the global.0p50 which is needed for the downstream scripts/exgfs_wave_prdgen_gridded.sh
as well.

**Comment by RuiyuSun** [comment]
> > @JessicaMeixner-NOAA Thanks for the heads up! I will be happy to jump back on this when the test case is available.
> 
> @DavidHuber-NOAA @AminIlia-NOAA This has the point output:
> 
> /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/station That should contain the info that you need for the wave product jobs. This doesn't have the boundary pionts, which was an oversight on my part, but I don't think those are needed for any downstream jobs so that should be okay.
> 
> This: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/gridded also should have the global.0p50 which is needed for the downstream scripts/exgfs_wave_prdgen_gridded.sh as well.

Thanks @DavidHuber-NOAA. Please let me know when it is ready.

**Comment by AminIlia-NOAA** [comment]
@JessicaMeixner-NOAA Thank you for tagging me on this issue. Following our conversation you mentioned you will add those points to the file. Am I missing anything?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Thank you for tagging me on this issue. Following our conversation you mentioned you will add those points to the file. Am I missing anything?

@AminIlia-NOAA  - This is unrelated to the point list changing.  This is fixing a bug so that the expected output points are produced when using an unstructured grid. The output here: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/station uses a WW3 with the bug fix so the upstream issue is resolved and the downstream point jobs should succeed.

**Comment by AminIlia-NOAA** [comment]
@JessicaMeixner-NOAA Thank you for the clarification. I'm a little behind on the wave side, however, please let me know if I can help with anything.

**Comment by DavidHuber-NOAA** [comment]
@RuiyuSun I've finished fixing the `wavegempak` and `waveawipsgridded` jobs and removed the a couple of jobs from the forecast-only configuration.  I believe all jobs should now run with the one exception of `waveawipsbulls` job.  I will continue on with this job based on Jessica's input directory, but it will take some time before the job will run correctly in the workflow as we will need a new UFS hash.  Thus, I am marking this PR ready for review.

**Comment by RuiyuSun** [comment]
Thanks @DavidHuber-NOAA.  I will make a HRv4 like experiment to test this.

**Comment by JessicaMeixner-NOAA** [comment]
> Thanks @DavidHuber-NOAA. I will make a HRv4 like experiment to test this.

@RuiyuSun  if you need the wave post jobs to work - you'll need a branch of ufs - I can give that to you if you'dlike

**Comment by RuiyuSun** [comment]
> > Thanks @DavidHuber-NOAA. I will make a HRv4 like experiment to test this.
> 
> @RuiyuSun if you need the wave post jobs to work - you'll need a branch of ufs - I can give that to you if you'dlike

Sure. Thanks @JessicaMeixner-NOAA

File: parm/archive/gfs_downstream.yaml.j2 [hunk 3]
```diff
@@ -3,8 +3,10 @@ gfs_downstream:
     name: "GFS_DOWNSTREAM"
     target: "{{ ATARDIR }}/{{ cycle_YMDH }}/gfs_downstream.tar"
     required:
+        {% if DO_GEMPAK %}
         - "{{ COMIN_ATMOS_GEMPAK | relpath(ROTDIR) }}/gfs_{{ cycle_YMDH }}.sfc"
         - "{{ COMIN_ATMOS_GEMPAK | relpath(ROTDIR) }}/gfs_{{ cycle_YMDH }}.snd"
+        {% endif %}
         {% for i in range(1, NUM_SND_COLLECTIVES) %}
         - "{{ COMIN_ATMOS_BUFR | relpath(ROTDIR) }}/gfs_collective{{ i }}.fil"
         {% endfor %}
```
Comment (KateFriedman-NOAA) [inline parm/archive/gfs_downstream.yaml.j2:12]: Wrap this in a `DO_BUFRSND` check as well?

File: scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh [hunk 4]
```diff
@@ -68,11 +68,11 @@ export filesize=$( ls -l rdbfmsua.out | awk '{print $5}' )
 ################################################################
 
 if (( filesize > 40 )); then
-    cp rdbfmsua.out "${COM_ATMOS_GEMPAK_UPPER_AIR}/${RUN}.${cycle}.msupperair"
-    cp sonde.idsms.tbl "${COM_ATMOS_GEMPAK_UPPER_AIR}/${RUN}.${cycle}.msupperairtble"
+    cp rdbfmsua.out "${COMOUT_ATMOS_GEMPAK_UPPER_AIR}/${RUN}.${cycle}.msupperair"
+    cp sonde.idsms.tbl "${COMOUT_ATMOS_GEMPAK_UPPER_AIR}/${RUN}.${cycle}.msupperairtble"
```
Comment (KateFriedman-NOAA) [inline scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh:72]: Where does `COMOUT_ATMOS_GEMPAK_UPPER_AIR` get declared?

**Review by KateFriedman-NOAA — CHANGES_REQUESTED** [review]

File: parm/archive/gfs_downstream.yaml.j2 (hunk 3 above)
Comment (DavidHuber-NOAA) [reply parm/archive/gfs_downstream.yaml.j2:12]: `gfs_downstream.yaml.j2` is wrapped in a `DO_BUFRSND` within `master_gfs.yaml.j2`, so I think it's OK not adding it here.

Comment (KateFriedman-NOAA) [reply parm/archive/gfs_downstream.yaml.j2:12]: Ah, ok good, thanks!

File: scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh (hunk 4 above)
Comment (DavidHuber-NOAA) [reply scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh:72]: It's set in `jobs/JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF`:

https://github.com/NOAA-EMC/global-workflow/blob/5789de3caa51fa4d38715e3742fb19f1954dbf93/jobs/JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF#L35-L42

This could probably be made a bit more intuitive, though.  I will make that change.

Comment (KateFriedman-NOAA) [reply scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh:72]: Ah, yeah I searched for uppercase `UPPER_AIR` and didn't see it. Thanks!

Comment (DavidHuber-NOAA) [reply scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh:72]: Done.  And on second look, the COMIN directories are not used, so I remove those declarations.

File: ush/make_NTC_file.pl
Comment (DavidHuber-NOAA) [inline ush/make_NTC_file.pl:1]: @aerorahul Who should I make codeowner(s) of these new Perl/bash scripts moved from gfs-utils?

Comment (aerorahul) [reply ush/make_NTC_file.pl:1]: I have no idea. @yangfanglin Do you know where these came from:
```
ush/make_NTC_file.pl
ush/make_ntc_bull.pl
ush/make_tif.sh
ush/month_name.sh
```

File: scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh (hunk 4 above)
Comment (KateFriedman-NOAA) [reply scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh:72]: Great, thanks @DavidHuber-NOAA !

**Comment by DavidHuber-NOAA** [comment]
> > @JessicaMeixner-NOAA Thanks for the heads up! I will be happy to jump back on this when the test case is available.
> 
> @DavidHuber-NOAA @AminIlia-NOAA This has the point output:
> 
> /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/station That should contain the info that you need for the wave product jobs. This doesn't have the boundary pionts, which was an oversight on my part, but I don't think those are needed for any downstream jobs so that should be okay.
> 
> This: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/gridded also should have the global.0p50 which is needed for the downstream scripts/exgfs_wave_prdgen_gridded.sh as well.

@JessicaMeixner-NOAA The file `/lfs/h2/emc/couple/noscrub/jessica.meixner/GWPR3190upwav/WaveProdTest01/COMROOT/WaveProdTest01/gfs.20200913/00/products/wave/station/gfswave.t00z.cbull_tar` appears to also not have some of the buoy data in it that the `gfs_waveawipsbulls` job is looking for.  Running `tar -tvf` on the file shows, for example, no file for buoy number 46001.

**Comment by RuiyuSun** [comment]
> All CI tests completed successfully. However, I ran a `C48_S2SW` test case with `DO_AWIPS`, `DO_GEMPAK`, `DO_GOES`, `DO_BUFRSND`, and `DO_NPOESS` all set to `YES`, and discovered a number of failures in gempak and awips jobs. Converting back to draft while I resolve these issues.

@ChristopherHill-NOAA @DavidHuber-NOAA Do we still need DO_GOES? Synthetic GOES should be removed if it haven't been removed upon successful PNS process.

**Review by aerorahul — DISMISSED** [review]
code changes look good to me.
Thank you for taking care of downstream product generation jobs.

**Comment by aerorahul** [comment]
> > All CI tests completed successfully. However, I ran a `C48_S2SW` test case with `DO_AWIPS`, `DO_GEMPAK`, `DO_GOES`, `DO_BUFRSND`, and `DO_NPOESS` all set to `YES`, and discovered a number of failures in gempak and awips jobs. Converting back to draft while I resolve these issues.
> 
> @ChristopherHill-NOAA @DavidHuber-NOAA Do we still need DO_GOES? Synthetic GOES should be removed if it haven't been removed upon successful PNS process.

@RuiyuSun 
I don't think there has been a final decision on synthetic GOES products.  There hasn't been a PNS for it that I know of. 
 @WenMeng-NOAA has there been further discussions on discontinuing synthetic GOES product generation?

**Comment by ChristopherHill-NOAA** [comment]
> > > All CI tests completed successfully. However, I ran a `C48_S2SW` test case with `DO_AWIPS`, `DO_GEMPAK`, `DO_GOES`, `DO_BUFRSND`, and `DO_NPOESS` all set to `YES`, and discovered a number of failures in gempak and awips jobs. Converting back to draft while I resolve these issues.
> > 
> > 
> > @ChristopherHill-NOAA @DavidHuber-NOAA Do we still need DO_GOES? Synthetic GOES should be removed if it haven't been removed upon successful PNS process.
> 
> @RuiyuSun I don't think there has been a final decision on synthetic GOES products. There hasn't been a PNS for it that I know of. @WenMeng-NOAA has there been further discussions on discontinuing synthetic GOES product generation?

@RuiyuSun @aerorahul  According to notes I received from Gwen in July 2024, the options of `DO_GOES=YES` and `DO_NPOESS=YES` options are intended to be retained with GFSv17.  Otherwise, I am not presently aware of the status of synthetic satellite products for GFSv17.

**Comment by WenMeng-NOAA** [comment]
> > > > All CI tests completed successfully. However, I ran a `C48_S2SW` test case with `DO_AWIPS`, `DO_GEMPAK`, `DO_GOES`, `DO_BUFRSND`, and `DO_NPOESS` all set to `YES`, and discovered a number of failures in gempak and awips jobs. Converting back to draft while I resolve these issues.
> > > 
> > > 
> > > @ChristopherHill-NOAA @DavidHuber-NOAA Do we still need DO_GOES? Synthetic GOES should be removed if it haven't been removed upon successful PNS process.
> > 
> > 
> > @RuiyuSun I don't think there has been a final decision on synthetic GOES products. There hasn't been a PNS for it that I know of. @WenMeng-NOAA has there been further discussions on discontinuing synthetic GOES product generation?
> 
> @RuiyuSun @aerorahul According to notes I received from Gwen in July 2024, the options of `DO_GOES=YES` and `DO_NPOESS=YES` options are intended to be retained with GFSv17. Otherwise, I am not presently aware of the status of synthetic satellite products for GFSv17.

@aerorahul @DavidHuber-NOAA @ChristopherHill-NOAA  I discussed with Jason last December that we would continue generating Synthetic GOES products in GFS v17.

**Review by KateFriedman-NOAA — DISMISSED** [review]
Looks good, thanks @DavidHuber-NOAA !

**Comment by DavidHuber-NOAA** [comment]
Adding `WCOSS2-ready` label.  This won't test the S2SW downstream jobs, but will at least run the `C96_atm3dvar_extended` test.

**Comment by KateFriedman-NOAA** [comment]
CI on WCOSS2 initiated @DavidHuber-NOAA

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Checkout failed on WCOSS2. See the end of the cloning output below:
```
WCOSS2 (BACKUPSYS-C) ci> setup_pr 3187
Cloning into 'global-workflow'...
remote: Enumerating objects: 64320, done.
remote: Counting objects: 100% (370/370), done.
remote: Compressing objects: 100% (294/294), done.
remote: Total 64320 (delta 229), reused 76 (delta 76), pack-reused 63950 (from 3)
Receiving objects: 100% (64320/64320), 131.42 MiB | 19.84 MiB/s, done.
Resolving deltas: 100% (46378/46378), done.
Updating files: 100% (1796/1796), done.
https://github.com/NOAA-EMC/global-workflow/pull/3187
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 202 (delta 96), reused 53 (delta 53), pack-reused 72 (from 2)
Receiving objects: 100% (202/202), 91.14 KiB | 691.00 KiB/s, done.
Resolving deltas: 100% (106/106), completed with 9 local objects.
From https://github.com/NOAA-EMC/global-workflow
 * [new ref]           refs/pull/3187/head -> fix/awips
Switched to branch 'fix/awips'
Submodule 'sorc/gdas.cd' (https://github.com/NOAA-EMC/GDASApp.git) registered for path 'sorc/gdas.cd'
Submodule 'sorc/gfs_utils.fd' (https://github.com/NOAA-EMC/gfs-utils) registered for path 'sorc/gfs_utils.fd'
Submodule 'sorc/gsi_enkf.fd' (https://github.com/NOAA-EMC/GSI.git) registered for path 'sorc/gsi_enkf.fd'
Submodule 'sorc/gsi_monitor.fd' (https://github.com/NOAA-EMC/GSI-Monitor.git) registered for path 'sorc/gsi_monitor.fd'
Submodule 'sorc/gsi_utils.fd' (https://github.com/NOAA-EMC/GSI-Utils.git) registered for path 'sorc/gsi_utils.fd'
Submodule 'sorc/ufs_model.fd' (https://github.com/ufs-community/ufs-weather-model) registered for path 'sorc/ufs_model.fd'
Submodule 'sorc/ufs_utils.fd' (https://github.com/ufs-community/UFS_UTILS.git) registered for path 'sorc/ufs_utils.fd'
Submodule 'sorc/verif-global.fd' (https://github.com/NOAA-EMC/EMC_verif-global.git) registered for path 'sorc/verif-global.fd'
Submodule 'sorc/wxflow' (https://github.com/NOAA-EMC/wxflow) registered for path 'sorc/wxflow'
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gfs_utils.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gsi_monitor.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gsi_utils.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gsi_enkf.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/wxflow'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/verif-global.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/ufs_model.fd'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/ufs_utils.fd'...
Submodule path 'sorc/gdas.cd': checked out 'd6097afdd435fe73cc99d8ddb594c3143b72820a'
Submodule 'parm/jcb-algorithms' (https://github.com/noaa-emc/jcb-algorithms) registered for path 'sorc/gdas.cd/parm/jcb-algorithms'
Submodule 'parm/jcb-gdas' (https://github.com/noaa-emc/jcb-gdas) registered for path 'sorc/gdas.cd/parm/jcb-gdas'
Submodule 'sorc/bufr-query' (https://github.com/noaa-emc/bufr-query.git) registered for path 'sorc/gdas.cd/sorc/bufr-query'
Submodule 'sorc/crtm' (https://github.com/jcsda/crtm.git) registered for path 'sorc/gdas.cd/sorc/crtm'
Submodule 'sorc/da-utils' (https://github.com/noaa-emc/da-utils.git) registered for path 'sorc/gdas.cd/sorc/da-utils'
Submodule 'sorc/femps' (https://github.com/jcsda/femps.git) registered for path 'sorc/gdas.cd/sorc/femps'
Submodule 'sorc/fv3' (https://github.com/jcsda/GFDL_atmos_cubed_sphere.git) registered for path 'sorc/gdas.cd/sorc/fv3'
Submodule 'sorc/fv3-jedi' (https://github.com/jcsda/fv3-jedi.git) registered for path 'sorc/gdas.cd/sorc/fv3-jedi'
Submodule 'sorc/fv3-jedi-lm' (https://github.com/jcsda/fv3-jedi-linearmodel.git) registered for path 'sorc/gdas.cd/sorc/fv3-jedi-lm'
Submodule 'sorc/gsibec' (https://github.com/GEOS-ESM/GSIbec.git) registered for path 'sorc/gdas.cd/sorc/gsibec'
Submodule 'sorc/gsw' (https://github.com/jcsda-internal/GSW-Fortran.git) registered for path 'sorc/gdas.cd/sorc/gsw'
Submodule 'sorc/icepack' (https://github.com/JCSDA-internal/Icepack.git) registered for path 'sorc/gdas.cd/sorc/icepack'
Submodule 'sorc/ioda' (https://github.com/jcsda/ioda.git) registered for path 'sorc/gdas.cd/sorc/ioda'
Submodule 'sorc/iodaconv' (https://github.com/JCSDA-internal/ioda-converters.git) registered for path 'sorc/gdas.cd/sorc/iodaconv'
Submodule 'sorc/jcb' (https://github.com/noaa-emc/jcb.git) registered for path 'sorc/gdas.cd/sorc/jcb'
Submodule 'sorc/jedicmake' (https://github.com/jcsda/jedi-cmake.git) registered for path 'sorc/gdas.cd/sorc/jedicmake'
Submodule 'sorc/land-imsproc' (https://github.com/NOAA-PSL/land-IMS_proc.git) registered for path 'sorc/gdas.cd/sorc/land-imsproc'
Submodule 'sorc/land-jediincr' (https://github.com/NOAA-PSL/land-apply_jedi_incr.git) registered for path 'sorc/gdas.cd/sorc/land-jediincr'
Submodule 'sorc/oops' (https://github.com/jcsda/oops.git) registered for path 'sorc/gdas.cd/sorc/oops'
Submodule 'sorc/saber' (https://github.com/jcsda/saber.git) registered for path 'sorc/gdas.cd/sorc/saber'
Submodule 'sorc/soca' (https://github.com/jcsda-internal/soca.git) registered for path 'sorc/gdas.cd/sorc/soca'
Submodule 'sorc/ufo' (https://github.com/jcsda/ufo.git) registered for path 'sorc/gdas.cd/sorc/ufo'
Submodule 'sorc/vader' (https://github.com/jcsda/vader.git) registered for path 'sorc/gdas.cd/sorc/vader'
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/parm/jcb-algorithms'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/parm/jcb-gdas'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/da-utils'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/femps'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/bufr-query'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/crtm'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/fv3-jedi'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/fv3-jedi-lm'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/gsibec'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/fv3'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/gsw'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/ioda'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/icepack'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/land-imsproc'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/land-jediincr'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/jedicmake'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/oops'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/iodaconv'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/jcb'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/soca'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/saber'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/vader'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/ufo'...
Submodule path 'sorc/gdas.cd/parm/jcb-algorithms': checked out '0f4423943e1c2bdd4b9d0a4218e30df83c5e2c66'
Submodule path 'sorc/gdas.cd/parm/jcb-gdas': checked out 'accd7a5bf96524430d8d03a4b2d707eca4c48c13'
Submodule path 'sorc/gdas.cd/sorc/bufr-query': checked out '97367fcd59adf4863aba1a52189e20f9f66451af'
Submodule path 'sorc/gdas.cd/sorc/crtm': checked out 'bb7adbfc4f3deadedac98743bcb4e18a2bca11f9'
Submodule path 'sorc/gdas.cd/sorc/da-utils': checked out '5c6080c3f52e300ebba70075ca094ef5785df93a'
Submodule path 'sorc/gdas.cd/sorc/femps': checked out '4f12677d345e683bf910b5f76f0df120ad27482d'
Submodule path 'sorc/gdas.cd/sorc/fv3': checked out 'ab25dc09d955271f34ca6a3fa83af1093c85d9f7'
Submodule path 'sorc/gdas.cd/sorc/fv3-jedi': checked out '136dfb9c2f8541584e62fa74c616d686602bcdad'
Submodule path 'sorc/gdas.cd/sorc/fv3-jedi-lm': checked out 'a6e97d76ed7c0b2a27cf97512893a93d7e2b44bc'
Submodule path 'sorc/gdas.cd/sorc/gsibec': checked out 'c8ac58d9b43eb8f890e565d12c88f1b0579c9ccd'
Submodule path 'sorc/gdas.cd/sorc/gsw': checked out '697cbeb7605d70ed3857664c5f54a5c05346e31f'
Submodule path 'sorc/gdas.cd/sorc/icepack': checked out '73136ee8dcdbe378821e540488a5980a03d8abe6'
Submodule path 'sorc/gdas.cd/sorc/ioda': checked out '22cd20eae0685914a5b967e13f95779b57bb448c'
Submodule path 'sorc/gdas.cd/sorc/iodaconv': checked out '6f87a0f279e836fd604e5b313a25bd1e54bff80e'
Submodule path 'sorc/gdas.cd/sorc/jcb': checked out '8269ce474fe864fdd6dc51913ccce9daca630ac2'
Submodule path 'sorc/gdas.cd/sorc/jedicmake': checked out '36fc99bdff5d3d8835480b37a3dcc75e5f8da256'
Submodule 'CMakeModules' (https://github.com/NOAA-EMC/CMakeModules) registered for path 'sorc/gdas.cd/sorc/jedicmake/CMakeModules'
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/jedicmake/CMakeModules'...
Submodule path 'sorc/gdas.cd/sorc/jedicmake/CMakeModules': checked out 'cabd7753ae17f7bfcc6dad56daf10868aa51c3f4'
Submodule path 'sorc/gdas.cd/sorc/land-imsproc': checked out '7ca1c7441042558cf41a0753f80191a0026a1126'
Submodule path 'sorc/gdas.cd/sorc/land-jediincr': checked out '7c1f6a3f8f949e376786eef7dba55a9e10e9778d'
Submodule path 'sorc/gdas.cd/sorc/oops': checked out '1ba321ff912c6338d7362667eff37ddbf569cb18'
Submodule path 'sorc/gdas.cd/sorc/saber': checked out 'de5015c8328f5b3d64acc99739fbaa64ef571172'
Submodule path 'sorc/gdas.cd/sorc/soca': checked out '44c4d6e53efa774bbaa038b0ecc4c34e3a33c9df'
Submodule 'mom6/MOM6' (https://github.com/NOAA-EMC/MOM6) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6'
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/soca/mom6/MOM6'...
Submodule path 'sorc/gdas.cd/sorc/soca/mom6/MOM6': checked out '10521a921d2f442de19a0cda240d912fd918c40c'
Submodule 'pkg/CVMix-src' (https://github.com/mom-ocean/CVMix-src.git) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/CVMix-src'
Submodule 'pkg/GSW-Fortran' (https://github.com/mom-ocean/GSW-Fortran.git) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/GSW-Fortran'
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/CVMix-src'...
Cloning into '/lfs/h2/emc/ptmp/emc.global/PR/PR_3187/global-workflow/sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/GSW-Fortran'...
Submodule path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/CVMix-src': checked out '9423197f894112edfcb1502245f7d7b873d551f9'
Submodule path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/GSW-Fortran': checked out '29e64d652786e1d076a05128c920f394202bfe10'
Submodule path 'sorc/gdas.cd/sorc/ufo': checked out '85ef98cb99f3eae1ed15e39f0cb05046af36fef1'
Submodule path 'sorc/gdas.cd/sorc/vader': checked out '3049658d185c8095caf0e506795d0e5995fa92cf'
fatal: remote error: upload-pack: not our ref a8022c2dde6eabd78f93d4467c1d3e2283b92416
fatal: Fetched in submodule path 'sorc/gfs_utils.fd', but it did not contain a8022c2dde6eabd78f93d4467c1d3e2283b92416. Direct fetching of that commit failed.
fatal: 
https://github.com/NOAA-EMC/global-workflow/pull/3187
WCOSS2 (BACKUPSYS-C) global-workflow>
```

**Comment by DavidHuber-NOAA** [comment]
Ah, right, I have a gfs-utils PR to open...  Opened https://github.com/NOAA-EMC/gfs-utils/pull/90.

**Comment by DavidHuber-NOAA** [comment]
It looks like the `gdas_gempakmetancdc` job failed on WCOSS2.  I'm investigating.

**Comment by KateFriedman-NOAA** [comment]
Manually pulled in fixes to CI clone on WCOSS2 and reran failed jobs. Failing CI test completed successfully on WCOSS2, as did others.
```
Tue Jan 14 16:46:41 UTC 2025
******** C48_ATM_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jan 13 2025 19:55:31    Jan 13 2025 21:05:25
202103231800        Done    Jan 13 2025 19:55:31    Jan 13 2025 21:15:34

******** C48_S2SW_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jan 13 2025 19:55:34    Jan 13 2025 21:40:34
202103231800        Done    Jan 13 2025 19:55:34    Jan 13 2025 21:50:29

******** C48_S2SWA_gefs_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103231200        Done    Jan 13 2025 19:55:39    Jan 13 2025 22:50:36

******** C96_atm3DVar_extended_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Jan 13 2025 19:55:43    Jan 13 2025 20:15:47
202112210000        Done    Jan 13 2025 19:55:43    Jan 14 2025 16:30:40
202112210600        Done    Jan 13 2025 19:55:43    Jan 14 2025 01:10:39
202112211200        Done    Jan 13 2025 20:20:54    Jan 14 2025 16:35:34
202112211800        Done    Jan 14 2025 01:15:37    Jan 14 2025 06:05:49

******** C96C48_hybatmDA_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202112201800        Done    Jan 13 2025 19:55:46    Jan 13 2025 20:15:51
202112210000        Done    Jan 13 2025 19:55:46    Jan 13 2025 22:25:49
202112210600        Done    Jan 13 2025 19:55:46    Jan 13 2025 22:15:52

******** C96_S2SWA_gefs_replay_ics_3187 ********
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202011010000        Done    Jan 13 2025 19:55:49    Jan 13 2025 20:35:54
```

**Comment by DavidHuber-NOAA** [comment]
I added some fixes for the `gfs_waveawipsbulls` job, but I was unable to test the job completely due to missing buoy data that should be generated by the `gfs_wavepostpnt` job.  This is documented in #3226.  Once this issue is resolved in a future PR, the new `C48_S2SW_extended` test can be enabled on WCOSS2.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
