### PR TITLE
Fix 06z gfs_sfcanl jobs failing due to a bug in CCPP

### LINKED ISSUE #4364: global_cycle reports a fatal error on 06Z gfs cycles
### What is wrong?

Running the C96_atm3DVar_extended case on Dogwood returns the following fatal error during `gfs_sfcanl` on cycle `2021122106`:

```bash
nid002045.dogwood.wcoss2.ncep.noaa.gov 0:   first grib record.
  kpds( 1-10)=           7         120         255         192          91
         102           0          20           1           1
  kpds(11-20)=           0           0           1           0           0
          10          31           1           2           0
  kpds(21-  )=          21           2
nid002045.dogwood.wcoss2.ncep.noaa.gov 5:  FATAL ERROR: ice concentration
 analysis read error.
----- contents of errfile -----
nid002045.dogwood.wcoss2.ncep.noaa.gov 5: abort: 
nid002045.dogwood.wcoss2.ncep.noaa.gov: rank 5 exited with code 134
nid002045.dogwood.wcoss2.ncep.noaa.gov 0: forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
libpnetcdf.so.4.0  000014A99A27B2EC  for__signal_handl     Unknown  Unknown
libpthread-2.31.s  000014A9A3B95910  Unknown               Unknown  Unknown
global_cycle       0000000000495788  fi635_                   3155  w3fi63.f
global_cycle       0000000000490F20  w3fi63_                   325  w3fi63.f
global_cycle       000000000048F7B0  getgb1r_                   45  getgb1r.f
global_cycle       000000000048C5BC  getgbm_                   236  getgbm.f
global_cycle       000000000048C19C  getgb_                    186  getgb.f
global_cycle       00000000004478B9  fixrdc_                  8502  sfcsub.F
global_cycle       000000000043C4D7  clima_                   7728  sfcsub.F
global_cycle       000000000041FC00  sfccycle_                1137  sfcsub.F
global_cycle       0000000000412C71  sfcdrv_                   658  cycle.F90
global_cycle       00000000004096B7  MAIN__                    184  cycle.F90
global_cycle       0000000000408B12  Unknown               Unknown  Unknown
libc-2.31.so       000014A99843E24D  __libc_start_main     Unknown  Unknown
global_cycle       0000000000408A2A  Unknown               Unknown  Unknown
```

### What should have happened?

The test should have passed without issue.

### What machines are impacted?

WCOSS2

### What global-workflow hash are you using?

https://github.com/NOAA-EMC/global-workflow/commit/8c7d6e6f36319b65b35c78601b0d12e36a085748

### Steps to reproduce

Run a C96_atm3DVar test case through the 06z cycle gfs_sfcanl job.  I will work on a reproducer.

### Additional information

_No response_

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This fixes a bug in CCPP that prevented the 06Z `gfs_sfcanl` job from running global_cycle on the 03Z IAU time.  The code change now allows the input hour to be any integer between 0 and 23.
Resolves #4364 
Refs #4408 (partially resolves but a full investigation is needed)

# Type of change
- [x] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this change expected to change outputs YES: the CCPP code change itself is non-answer-changing, but it requires a model hash update
  - [x] GFS
  - [ ] GEFS
  - [ ] SFS
  - [ ] GCAFS
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES
  - [x] UFS-utils https://github.com/ufs-community/UFS_UTILS/pull/1122 (depends on https://github.com/ufs-community/ccpp-physics/pull/336)
  - [x] UFS-weather-model https://github.com/ufs-community/ufs-weather-model/pull/3036#issuecomment-3696779087 (depends on https://github.com/ufs-community/ccpp-physics/pull/336)

# How has this been tested?
- [x] C96_atm3DVar_extended test on WCOSS2
- [x] UFS_Utils regression tests on Ursa (no change to baseline)
- [x] UFS regression tests
- [ ] Full suite of GW tests on all platforms (when the UFS model hash is ready)

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my code, including function, input, and output descriptions
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [x] This change is covered by an existing CI test or a new one has been added

### CODE REVIEW

File: ush/parsing_ufs_configure.sh [hunk 1]
```diff
@@ -69,6 +69,8 @@ UFS_configure() {
         local MED_history_n=1000000
 
         local histaux_enabled=".false."
+        local MOM6_OUTPUT_DIR="${MOM6_OUTPUT_DIR:-./MOM6_OUTPUT}"
+        local MOM6_RESTART_DIR="${MOM6_RESTART_DIR:-./MOM6_RESTART}"
```
Comment (aerorahul) [inline ush/parsing_ufs_configure.sh]:
```suggestion
        local MOM6_OUTPUT_DIR="./MOM6_OUTPUT"
        local MOM6_RESTART_DIR="./MOM6_RESTART"
```
This isn't an option.  The workflow will always write to this space.  The other instances where this variable is set in this manner is `ush/parsing_namelists_FV3.sh`

**Review by aerorahul — DISMISSED** [review]
just one suggestion, looks good.

File: ush/parsing_ufs_configure.sh (hunk 1 above)
Comment (JessicaMeixner-NOAA) [reply ush/parsing_ufs_configure.sh]: I agree, I don't think this should be configurable.  This is assumed other places. 

I also see that https://github.com/ufs-community/ufs-weather-model/compare/6f22f57403db693dee3b6979a4e6f58ade633e86...f8b0802e7e402022925a032929ce1f8d93871c60 we have a MOM6_OUTPUT_FH defined, which is defined in forecast_predet.   

I'm assuming those are consistent definitions?

**Review by JessicaMeixner-NOAA — COMMENTED** [review]
We should run a S2S test of some sort to make sure ocean output looks okay given the changes.  I didn't follow exactly when those changes went in.  @jiandewang or @dpsarmie might know more about that the MOM6_OUTPUT_FH to make sure that is as expected here now.

**Comment by dpsarmie** [comment]
`FHOUT_OCN_GFS` / `FHOUT_OCN` is the variable that controls the MOM6 output frequency in GW and `MOM6_OUTPUT_FH` is just used to store an array of output times (in GW), correct? If so, then there might be an issue.

**Comment by JessicaMeixner-NOAA** [comment]
> `FHOUT_OCN_GFS` / `FHOUT_OCN` is the variable that controls the MOM6 output frequency in GW and `MOM6_OUTPUT_FH` is just used to store an array of output times (in GW), correct? If so, then there might be an issue.

Yes.  And looking a bit further, this variable should be "FHOUT_OCN" and not MOM6_OUTPUT_FH.

**Review by ClaraDraper-NOAA — DISMISSED** [review]
I haven't tested it, but can confirm that this PR brings the needed update to CCPP/physics into UFS_UTILS to fix the gfs_sfcanl issue. It also updates the CCPP/physics used by the model to the same hash.  

Note that updating the ufs_model and ufs_utils brings in many additional changes in addition to the gfs_sfcnl issue.

**Comment by DavidHuber-NOAA** [comment]
All tests passed on Ursa. I will run a develop C96C48mx500 case to verify the MOM6 output, then launch CI on all platforms.

**Comment by DavidHuber-NOAA** [comment]
I verified the 6-hour MOM6 forecast for the `C96C48mx025_S2SW_gfs_cyc` case was identical to last night's nightly run of the same case and also verified that MOM6 output was written every 6 hours as expected:

```console
>cmp /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc
> echo $?
0
```

Proceeding with CI testing.

**Comment by dpsarmie** [comment]
> All tests passed on Ursa. I will run a develop C96C48mx500 case to verify the MOM6 output, then launch CI on all platforms.

Did the `MOM6_OUTPUT_FH` issue get resolved? I would have thought that there would be a conflict since GW's definition of `MOM6_OUTPUT_FH` isn't what MOM6 is expecting.

**Comment by DavidHuber-NOAA** [comment]
@dpsarmie I did not have to change anything related to `MOM6_OUTPUT_FH`. As a further check, I also verified that the `gdas` instantaneous outputs were identical:

```console
> cmp /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gdas.20211220/18/model/ocean/history/gdas.t18z.inst.f003.nc /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gdas.20211220/18/model/ocean/history/gdas.t18z.inst.f003.nc
> echo $?
0
> cmp /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gdas.20211220/18/model/ocean/history/gdas.t18z.inst.f009.nc /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gdas.20211220/18/model/ocean/history/gdas.t18z.inst.f009.nc
> echo $?
0
```

Is there anything else I should check to verify this is running as it should?

**Review by aerorahul — DISMISSED** [review]
changes look good to me.

**Comment by dpsarmie** [comment]
@DavidHuber-NOAA `ufs.configure` should have added 

```
mom6_output_dir = @[MOM6_OUTPUT_DIR]
mom6_output_fh = @[MOM6_OUTPUT_FH]
mom6_restart_dir = @[MOM6_RESTART_DIR]
```

If the mom6_output_fh line is an integer and the expected value, then it should be fine. My worry is what Jessica brought up, that in your scripts, the output hours are controlled by `FHOUT_OCN` and `MOM6_OUTPUT_FH` is another variable. Just making sure that it isn't just a coincidence that they work for these tests.
  
If there's a test that doesn't have a 6-hour output interval that's easy to run, then that would be my suggestion as a double/triple-check.

**Comment by DavidHuber-NOAA** [comment]
@dpsarmie the `C96C48mx500_S2SW_gfs_cyc` test runs the `gfs` cycle with 6-hourly averaged outputs up to FH 120 while the `gdas` cycle outputs instantaneous outputs every 3 hours to FH 9. I have verified that all of the instantaneous outputs are identical between this PR and last night's CI test.

**Comment by JessicaMeixner-NOAA** [comment]
I think the possible issue here is that this is what you are getting in for example: 

/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211221/00/conf/ufs.ufs.configure

```
  mom6_output_dir = ./MOM6_OUTPUT
  mom6_output_fh = 0 6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120
  mom6_restart_dir = ./MOM6_RESTART
```

My understanding - which might be wrong is this should be `mom6_output_fh = 6 `

And is this working for the right reasons?   I would want to check SFS or GFS output versus GDAS output for MOM6 as well because GDAS is instantaneous output whearas SFS, GFS and others are averaged output.

**Comment by DavidHuber-NOAA** [comment]
To verify outputs are identical, inventory both the `gfs` and `sfs` ocean history files:

```console
> ls /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/* /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/*
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f024.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f048.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f072.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f096.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f120.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f144.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f024.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f048.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f072.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f096.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f120.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f144.nc
>
>
> ls /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/* /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/*
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f006.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f012.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f018.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f024.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f030.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f036.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f042.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f048.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f054.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f060.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f066.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f072.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f078.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f084.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f090.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f096.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f102.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f108.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f114.nc
/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f006.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f012.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f018.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f024.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f030.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f036.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f042.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f048.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f054.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f060.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f066.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f072.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f078.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f084.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f090.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f096.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f102.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f108.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f114.nc
/scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc
```

Next, verifying contents:

```console
> cmp /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96C48mx500_S2SW_cyc_gfs_4389/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96C48mx500_S2SW_cyc_gfs_6ada5183-6840/gfs.20211220/18/model/ocean/history/gfs.t18z.6hr_avg.f120.nc
> cmp /scratch3/NCEPDEV/stmp/David.Huber/rt_4389/COMROOT/C96mx100_S2S_4389/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f048.nc /scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/URSA/BUILDS/GITLAB/nightly_6ada5183_010726/RUNTESTS/COMROOT/C96mx100_S2S_6ada5183-6840/sfs.19940501/00/mem001/model/ocean/history/sfs.t00z.24hr_avg.f048.nc
```

Contents are identical for GFS cycle 2021122018 and SFS cycle `1994050100`.

However, it is noted that the quantities in the `C96C48mx500_S2SW_cyc_gfs` test differ for the `2021122100` cycle, though the output times are identical. It is not clear to me if this is due to changes in the GDASApp that were in last night's nightly runs and not mine or changes to the weather model that are in mine but not last night's run.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for checking contents @DavidHuber-NOAA . 

Maybe @dpsarmie can confirm if 
`  mom6_output_fh = 0 6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120
`
in ufs.configure is as expected/acceptable, or if it should be just mom6_output_fh = 6 ?

**Comment by DeniseWorthen** [comment]
Where is this array of output frequencies being used? It can't be in the diag_table, which expects a number like "6". 

The number in the ufs_configure should be a single frequency and it should match the freqency contained in the diag_table.

EDIT: I guess actually this isn't an array of freqs, it is an array of output hours. The ufs_configure needs to contain the frequency, and that needs to match the frequency in the diag_table.

**Comment by JessicaMeixner-NOAA** [comment]
Okay - so we need changes in the workflow.   Even thought it "works" it's perhaps working for the wrong reason.

**Comment by DavidHuber-NOAA** [comment]
The confusion here is coming from the already-existent `MOM6_OUTPUT_FH` in the global workflow before it was defined in the UFS. The global workflow's definition of this variable differs from the UFS and specifies the MOM6 history writing frequency and is only intended to be used in the `forecast_predet.sh` and `forecast_postdet.sh` scripts. In the UFS, it is used for defining the MOM6 logging frequency. After discussion with @dpsarmie and @JessicaMeixner-NOAA, it was decided to update this variable name in the UFS.

Marking this PR as `needs submodule update` while waiting for the UFS update. If there are any issues with the UFS update, then I will change the name of the `MOM6_OUTPUT_FH` in the global workflow in `forecast_predet.sh` and `forecast_postdet.sh`.

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA - Have we had confirmation from @dpsarmie  that it's okay to change the definition in ufs?  Because if not, we'll need to change the variable name in global-workflow.

**Comment by dpsarmie** [comment]
Yes, I'm going to change the variable MOM6_OUTPUT_FH --> MOM6_HISTFREQ_N in UFS because that'll add consistency with the CICE variable name (which is CICE_HISTFREQ_N); then the only GW requirement would be adding local MOM6_HISTFREQ_N=${FHOUT_OCN:6} (or something similar) to the parsing_vars script.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @dpsarmie !

**Comment by dpsarmie** [comment]
Just going to link the dependency PR for visibility: https://github.com/ufs-community/ufs-weather-model/pull/3044

**Comment by dpsarmie** [comment]
@DavidHuber-NOAA https://github.com/ufs-community/ufs-weather-model/commit/7b637a8b7d8e96c503b1719affaa647dea7b2631 was merged into develop so this PR can be opened again. `MOM6_HISTFREQ_N` should be set to the GW equivalent `FHOUT_OCN` (?) and that should resolve the conflict.

**Comment by DavidHuber-NOAA** [comment]
Thank you @dpsarmie! I will get the new hash in, update the namelist variable, and get this tested today.

**Review by ClaraDraper-NOAA — DISMISSED** [review]
Can't comment on the MOM6 details, but the updated submodules look good. Thanks @DavidHuber-NOAA !

File: ush/parsing_ufs_configure.sh [hunk 2]
```diff
@@ -69,6 +69,8 @@ UFS_configure() {
         local MED_history_n=1000000
 
         local histaux_enabled=".false."
+        local MOM6_OUTPUT_DIR="./MOM6_OUTPUT"
```
Comment (JessicaMeixner-NOAA) [inline ush/parsing_ufs_configure.sh:72]: MOM6_HISTFREQ needs to be defined here, not in parsing_namelists_MOM6 as it is a variable in ufs.configure file.

Comment (DavidHuber-NOAA) [reply ush/parsing_ufs_configure.sh:72]: Thanks @JessicaMeixner-NOAA. I've fixed this now.

**Review by aerorahul — DISMISSED** [review]
lgtm.

**Comment by DavidHuber-NOAA** [comment]
I ran a test `C96C48mx500_S2SW_cyc_gfs` on Ursa using this branch, which ran to completion. I will now launch a full suite on all platforms.

**Review by JessicaMeixner-NOAA — DISMISSED** [review]

**Comment by DavidHuber-NOAA** [comment]
The gaea c6 failure was caused by a build stalling on a known-bad head node. I will relaunch tests there now that CI is running there again smoothly.

The SFS test failure on Ursa is known and that test has since been removed from the CI matrix.

The Hera failure is the only concerning issue.  `/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/HERA/BUILDS/GITLAB/pr_cases_4389_f6105b9e_7163/RUNTESTS/COMROOT/C48mx500_3DVarAOWCDA_f6105b9e-7163/logs/2021032500/gfs_arch_tar_gfswave.log` reports a failure on line 1231:
```
FileNotFoundError: FATAL ERROR: Required file, directory, or glob gfs.20210325/00/products/wave/gridded/global.0p50/gfs.t00z.*.*.f017.grib2 not found!
```

The `global.0p50` directory does not exist. Instead, it is `global.0p16`. This is likely a change in grids that came in with the latest UFS model upgrade, which includes a WW3 update. There is likely a namelist variable change required.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA @dpsarmie is there a required WW3 update needed with this update? It appears that the wave grid changed unexpectedly from 0p50 to 0p16.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA @dpsarmie actually, this does not seem to be related to the model update. Last night's nightly also ran WW3 at 0p16 and archived correctly. I will continue investigating.

**Comment by DavidHuber-NOAA** [comment]
I see now what happened. The `gfs_arch_tar_gfswave` job launched before the `gfs_wavepostsbs_f015-f017` job completed. This reflects another archiving dependency that is missing (#4408). I will add this dependency as well as the `gfs_waveawipsgridded` dependency (also documented in #4408) and relaunch tests on Hera, C6, Ursa, and WCOSS2.

**Comment by DavidHuber-NOAA** [comment]
I am still wrong. The `wavepostsbs` metatask is already a dependency of the archiving jobs. Instead, we have a silent failure. This is in `/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/HERA/BUILDS/GITLAB/pr_cases_4389_f6105b9e_7163/RUNTESTS/COMROOT/C48mx500_3DVarAOWCDA_f6105b9e-7163/logs/2021032500/gfs_wavepostsbs_f015-f017.log` during an MPMD section of the job at line 11403:

```
3: + wave_grib2_sbs.sh[88]/scratch3/NCEPDEV/global/role.glopara/GFS_CI_CD/HERA/BUILDS/GITLAB/pr_cases_4389_f6105b9e_7163/global-workflow/exec/gfs_ww3_grib.x
3: + wave_grib2_sbs.sh[89]export err=126
3: + wave_grib2_sbs.sh[89]err=126
3: + wave_grib2_sbs.sh[90][[ 126 -ne 0 ]]
3: + wave_grib2_sbs.sh[91]echo 'FATAL ERROR: gfs_ww3_grib.x returned non-zero status: 126; exiting!'
3: FATAL ERROR: gfs_ww3_grib.x returned non-zero status: 126; exiting!
3: + wave_grib2_sbs.sh[92]exit 126
```

Going to the end of the MPMD job at line 9891:

```
+ run_mpmd.sh[66]IFS=
+ run_mpmd.sh[66]read -r line
+ run_mpmd.sh[71]unset_strict
+ preamble.sh[45]set +eu
+ preamble.sh[46]set +o pipefail
+ run_mpmd.sh[73]srun -l --export=ALL --hint=nomultithread --multi-prog --output=mpmd.%j.%t.out -n 7 /scratch3/NCEPDEV/stmp/role.glopara/RUNDIRS/C48mx500_3DVarAOWCDA_f6105b9e-7163/gfs.2021032500/wavepostsbs_f017.82108/mpmd_cmdfile
+ run_mpmd.sh[74]err=0
+ run_mpmd.sh[75]set_strict
+ preamble.sh[35][[ YES == \Y\E\S ]]
+ preamble.sh[37]set -eu
+ preamble.sh[39]set -o pipefail
+ run_mpmd.sh[101][[ 0 -eq 0 ]]
```

It appears that `run_mpmd.sh` is not correctly catching failures of individual jobs.

**Comment by DavidHuber-NOAA** [comment]
All tests passed on all platforms. Requesting final approvals to merge.

File: dev/workflow/rocoto/gfs_tasks.py [hunk 3]
```diff
@@ -2217,6 +2217,19 @@ def _arch_tars_deps(self):
...
                         deps.append(rocoto.add_dependency(dep_dict))
 
+        if self.options['do_awips'] and self.run in ['gfs']:
+
+            dep_dict = {'type': 'metatask', 'name': f'{self.run}_awips_20km_1p0deg'}
+            deps.append(rocoto.add_dependency(dep_dict))
+            dep_dict = {'type': 'task', 'name': f'{self.run}_fbwind'}
+            deps.append(rocoto.add_dependency(dep_dict))
+
+            if self.options['do_wave']:
```
Comment (JessicaMeixner-NOAA) [inline dev/workflow/rocoto/gfs_tasks.py:2227]: This is okay to add but we don't actually archive any of the awips files for waves to my knowledge, so I don't think this is actually needed.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

File: dev/workflow/rocoto/gfs_tasks.py (hunk 3 above)
Comment (DavidHuber-NOAA) [reply dev/workflow/rocoto/gfs_tasks.py:2227]: Good to know! I'll open an issue to remove this tarball/job.

Comment (DavidHuber-NOAA) [reply dev/workflow/rocoto/gfs_tasks.py:2227]: Opened issues #4454 to retire AWIPS waves archiving.
