### PR TITLE
Enforce rstprod on relevant tarballs

### LINKED ISSUE #1433: GSI archives need to be restricted
**Expected behavior**

Any archive that is created in the *arch steps that contains restricted (rstprod) data should itself be assigned to the rstprod group.

**Current behavior**

The archiving scripts do not assign groups.  In particular, the gdas.tar, gdas_restarta.tar, and enkfgdas.tar archives all contain restricted data and are not assigned to the rstprod group.

**Machines affected**

All

**To Reproduce**

Run a cycled experiment through one full cycle, archiving the files locally, then `ls -l` the gdas.tar file.

**Context**

Discovered during globus tests (#1357).

**Additional Information**

Owners of previous experiments that are archived to HPSS or locally on Orion may wish to/should change their group membership for all gdas.tar, gdas_restarta.tar, and enkfgdas.tar files.  This can be achieved with
`find [archive/location] -name "gdas.tar" -o -name "gdas_restarta.tar" -o -name "enkfgdas.tar" -exec chgroup rstprod {} +;`

**Possible Implementation**

The `htar`/`tar` commands could be wrapped within an `sg` when dealing with restricted data.  For example,
```
sg rstprod -c ${TARCMD} -P -cvf "${ATARDIR}"/"${CDATE}"/"${targrp}".tar $(cat "${ARCH_LIST}"/"${targrp}".txt)'
```

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
Ensures that tarballs that contain restricted data are properly restricted to the rstprod group.

Fixes #1433

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
- [x] Hera with HPSS archival
- [x]  Orion with local archival
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
```
[hpsscore1]/NCEPDEV.../HERA/scratch/restrict_arch->ls -l 2021122018/

2021122018/:
-rw-r-----    1 Walter.Kolczynski  rstprod     90592768 Mar 29 09:52 enkfgdas.tar
-rw-r--r--    1 Walter.Kolczynski  emc-global        3872 Mar 29 09:52 enkfgdas.tar.idx
-rw-r-----    1 Walter.Kolczynski  rstprod   2349566464 Mar 29 09:52 gdas.tar
-rw-r--r--    1 Walter.Kolczynski  emc-global       31520 Mar 29 09:52 gdas.tar.idx
-rw-r-----    1 Walter.Kolczynski  rstprod         1536 Mar 29 09:52 gdas_restarta.tar
-rw-r--r--    1 Walter.Kolczynski  emc-global         800 Mar 29 09:52 gdas_restarta.tar.idx
-rw-r--r--    1 Walter.Kolczynski  emc-global  1897113600 Mar 29 09:52 gdas_restartb.tar
-rw-r--r--    1 Walter.Kolczynski  emc-global       40224 Mar 29 09:52 gdas_restartb.tar.idx
```

```
Orion-login-4 2021122200/>ls -l
total 35G
-rw-r----- 1 wkolczyn rstprod 3.8G Mar 29 04:57 enkfgdas.tar
-rw-r----- 1 wkolczyn rstprod 2.6G Mar 29 04:57 gdas_restarta.tar
-rw-r--r-- 1 wkolczyn global  1.9G Mar 29 05:01 gdas_restartb.tar
-rw-r----- 1 wkolczyn rstprod 5.3G Mar 29 04:57 gdas.tar
-rw-r--r-- 1 wkolczyn global   15G Mar 29 04:58 gfsa.tar
-rw-r--r-- 1 wkolczyn global  6.2G Mar 29 05:00 gfsb.tar
-rw-r--r-- 1 wkolczyn global  111M Mar 29 05:01 gfs_restarta.tar
```

(I forced the Hera archive job to run before the rest of the cycle was complete, so tarballs are incomplete.)

File: scripts/exgdas_enkf_earc.sh [hunk 1]
```diff
@@ -103,14 +103,18 @@ if [ "${ENSGRP}" -eq 0 ]; then
...
         if [[ ${LOCALARCH} = "YES" ]]; then
             TARCMD="tar"
+            HSICMD=""
             [ ! -d "${ATARDIR}"/"${CDATE}" ] && mkdir -p "${ATARDIR}"/"${CDATE}"
         fi
 
         set +e
         ${TARCMD} -P -cvf "${ATARDIR}/${CDATE}/${RUN}.tar" $(cat "${ARCH_LIST}/${RUN}.txt")
         status=$?
+        ${HSICMD} chgrp rstprod "${ATARDIR}/${CDATE}/${RUN}.tar"
```
Comment (DavidHuber-NOAA) [inline scripts/exgdas_enkf_earc.sh:116]: This should be nested in an if block to check `CHGRP_RSTPROD` since S4 and, temporarily, Jet do not have the group.  `CHGRP_CMD` could also be used instead of `chgrp`, but that's perhaps nitpicky.

File: scripts/exglobal_archive.sh [hunk 2]
```diff
@@ -255,6 +257,13 @@ for targrp in ${targrp_list}; do
     set +e
     ${TARCMD} -P -cvf "${ATARDIR}"/"${CDATE}"/"${targrp}".tar $(cat "${ARCH_LIST}"/"${targrp}".txt)
     status=$?
+    case ${targrp} in
```
Comment (DavidHuber-NOAA) [inline scripts/exglobal_archive.sh:260]: As above, should be nested in a `CHGRP_RSTPROD` if block.

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround, @WalterKolczynski-NOAA.  Just one change requested per script to use `CHGRP_RSTPROD`.

**Comment by DavidHuber-NOAA** [comment]
Tested on S4 just now.  This does not cause a failure, but does produce an error message `chgrp: invalid group: 'rstprod'`.  So this could be ignored for now and tackled later if desired.

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good. Approving but agree with @DavidHuber-NOAA that an adjustment for non-rstprod platforms may be needed in a follow-up. Should get this in ASAP though. Thanks @WalterKolczynski-NOAA !

**Comment by WalterKolczynski-NOAA** [comment]
I considered this an emergency fix (even though it has likely been an issue for months). Any warnings on S4 because of lack of rstprod can be cleaned up later at a more normal pace.

**Comment by WalterKolczynski-NOAA** [comment]
Merging this for now. Will open issues later today to improve it to handle machines w/o rstprod and other improvements.
