### PR TITLE
Check that a PR driver is still running before trying to kill it

### LINKED ISSUE #2798: Bash CI attempts to kill non-existent driver instances
### What is wrong?

Occasionally, a PR fails for one reason or another and the Bash CI attempts to kill the driver via SSH on a different head node.  However, in some circumstances, the driver may have crashed.  In those cases, the script (ci/scripts/driver.sh) still attempts to look for and kill all child processes, but is unable to find the parent process, resulting in a failure.

Also, if a PR directory is manually deleted, the Bash CI will fail to write to a log file, causing a failure

### What should have happened?

The driver.sh script should first check if the PID is still running before attempting to kill it.  Also, the same script should check for the existence of the PR directory and create it if it does not exist.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Rather difficult to reproduce.

### Additional information

Found while testing https://github.com/NOAA-EMC/global-workflow/pull/2791

### Do you have a proposed solution?

Add a check to the ssh command that the driver.sh PID is still running.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
Adds a check to the SSH command used to kill child PIDs of a defunct driver instance on a different head node to prevent invalid kill commands, preventing CI failures.

Resolves #2798

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Successfully detected the driver was no longer running on WCOSS2 for PR https://github.com/NOAA-EMC/global-workflow/pull/2791.

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Review by WalterKolczynski-NOAA — DISMISSED** [review]
Looks good to me, but hold for @TerrenceMcGuinness-NOAA to get back and review it.

File: ci/scripts/check_ci.sh
Comment (TerrenceMcGuinness-NOAA) [inline ci/scripts/check_ci.sh:1]: It is my understanding that the "+x" is generally the best practice for checking if a variable is set in BASH.  Please let me know why we should remove these here.

File: ci/scripts/driver.sh [hunk 1]
```diff
@@ -107,7 +108,9 @@ for pr in ${pr_list}; do
            echo -e "${pstree_out}" | grep -Pow "(?<=\()[0-9]+(?=\))" | xargs kill
         fi
       else
-        ssh "${driver_HOST}" 'pstree -A -p "${driver_PID}" | grep -Eow "[0-9]+" | xargs kill'
+        # Check if the driver is still running on the head node; if so, kill it and all child processes
+        #shellcheck disable=SC2029
+        ssh "${driver_HOST}" "if ps -p ${driver_PID} 2>&1; then pstree -A -p \"${driver_PID}\" | grep -Eow \"[0-9]+\" | xargs kill; fi"
```
Comment (TerrenceMcGuinness-NOAA) [inline ci/scripts/driver.sh]:
```suggestion
        ssh "${driver_HOST}" 'pstree -A -p "${driver_PID}" | grep -Eow "[0-9]+" | xargs kill || echo "Failed to kill process with PID: ${driver_PID}, it may not be valid."'
```

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/driver.sh]: This might be better.

**Comment by WalterKolczynski-NOAA** [comment]
@TerrenceMcGuinness-NOAA Please review this so it can move forward.

**Review by TerrenceMcGuinness-NOAA — CHANGES_REQUESTED** [review]

File: ci/scripts/driver.sh (hunk 1 above)
Comment (DavidHuber-NOAA) [reply ci/scripts/driver.sh]: Single quotes prevent variables from being expanded, so this needs to be double quoted.  I do like the 'Failed to kill' message, though.
```suggestion
        ssh "${driver_HOST}" "pstree -A -p \"${driver_PID}\" | grep -Eow \"[0-9]+\" | xargs kill || echo \"Failed to kill process with PID: ${driver_PID}, it may not be valid.\""
```

File: ci/scripts/check_ci.sh
Comment (DavidHuber-NOAA) [reply ci/scripts/check_ci.sh:1]: When checking if a variable (say `${bogus_var}`) is defined, using the `-z` check with `+x` parameter expansion is the way to go, e.g.
```bash
unset bogus_var
[[ -z ${bogus_var+x} ]] && echo "Variable 'bogus_var' is undefined!" || echo "Variable 'bogus_var' is defined as ${bogus_var}"
#> Variable 'bogus_var' is undefined!
```

But if you want to check if the variable is defined but set to an empty string, then you should use `-z` without `+x`:
```bash
unset bogus_var
bogus_var=""
[[ -z ${bogus_var+x} ]] && echo "Variable 'bogus_var' is undefined!" || echo "Variable 'bogus_var' is defined as ${bogus_var}"
#> Variable 'bogus_var' is defined as 
[[ -z ${bogus_var} ]] && echo "Variable 'bogus_var' is an empty string!"
#> Variable 'bogus_var' is an empty string!
```

And lastly, if you want to check if a variable is defined to a non-empty string, use the `-n` test:
```bash
unset bogus_var
bogus_var="foo"
[[ -z ${bogus_var+x} ]] && echo "Variable 'bogus_var' is undefined!" || echo "Variable 'bogus_var' is defined as ${bogus_var}"
#> Variable 'bogus_var' is defined as foo
[[ -n ${bogus_var} ]] && echo "Variable 'bogus_var' is defined as ${bogus_var}!"
#> Variable 'bogus_var' is defined as foo
```

For the tests that are performed in driver.sh, the variables are all defined.  For instance, in
https://github.com/NOAA-EMC/global-workflow/blob/4ef3a00a447e3a78bb1db879f2c39be47b47a380/ci/scripts/check_ci.sh#L52-L53
`rocotostat` is either defined as the path to the `rocotostat` command if it is found or an empty string if it is not.  On line 53, we want to know if `rocotostat` was not found, so we should check for an empty string.

Comment (TerrenceMcGuinness-NOAA) [reply ci/scripts/check_ci.sh:1]: Yes yes I reviewed the update in driver on line 52 I saw that `-n` was defiantly the way to go on the first pass.  And yes thank you for taking the time to explicitly pointing out why we don't need `+x` here.

**Review by TerrenceMcGuinness-NOAA — APPROVED** [review]
Nice updates.
