### PR TITLE
Eliminate race conditions and remove DATAROOT last in cleanup

### LINKED ISSUE #2880: gdascleanup and enkfgdascleanup failures
### What is wrong?

**gdascleanup** and **enkfgdascleanup** jobs failed with recent build of the global workflow. Both gdas and enkfgdas directories are not being scrubbed correctly in every cycle. 

Here are the error messages:

**gdascleanup.log:**
exglobal_cleanup.sh[49]: find_exclude_string=' -name *prepbufr* -or -name *prepbufr* -or -name *cnvstat* -or -name *prepbufr* -or -name *prepbufr* -or -name *cnvstat* -or -name *[atmanl.nc](http://atmanl.nc/) '
+ exglobal_cleanup.sh[52]: find /scratch1/NCEPDEV/stmp2/Xuanli.Li/ROTDIRS/romex_noro_newv17/gdas.20220824/18 -type f -not '(' -name '*prepbufr*' -or -name '*prepbufr*' -or -name '*cnvstat*' -or -name '*prepbufr*' -or -name '*prepbufr*' -or -name '*cnvstat*' -or -name '*[atmanl.nc](http://atmanl.nc/)' ')' -delete
find: Failed to save initial working directory: No such file or directory
+ exglobal_cleanup.sh[1]: postamble exglobal_cleanup.sh 1724969492 1

**enkfgdascleanup.log:**
+ exglobal_cleanup.sh[52]: find /scratch1/NCEPDEV/stmp2/Xuanli.Li/ROTDIRS/romex_noro_newv17/enkfgdas.20220824/18 -type f -not '(' -name '*f006.ens*' ')' -delete
find: Failed to save initial working directory: No such file or directory
+ exglobal_cleanup.sh[1]: postamble exglobal_cleanup.sh 1724972736 1

### What should have happened?

The gdas and enkfgdas directories should be cleaned.

### What machines are impacted?

Hera

### Steps to reproduce

Run global workflow (Hash # ea22a737ee9a815f1f294141abf85e0d1515868f) on Hera. Resolution C384+C192.

### Additional information

N/A

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This changes the order of the cleanup job so that the working directory is deleted at the end.  It also adds the `-ignore_readdir_race` flag to `find` to prevent errors if a file was deleted after the list of files was collected.  This can happen if two consecutive cycles run the cleanup job at the same time.

Resolves #2880 
# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?
A 5-cycle test on WCOSS2

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes

### CODE REVIEW

**Review by WalterKolczynski-NOAA — DISMISSED** [review]

File: scripts/exglobal_cleanup.sh [hunk 1]
```diff
@@ -113,3 +105,13 @@ if (( GDATE < RDATE )); then
 fi
 deletion_target="${ROTDIR}/${RUN}.${RDATE:0:8}"
 if [[ -d ${deletion_target} ]]; then rm -rf "${deletion_target}"; fi
+
+# Finally, delete DATAROOT.
```
Comment (aerorahul) [inline scripts/exglobal_cleanup.sh:112]:
```suggestion
# sync and wait to avoid filesystem synchronization issues
sync && sleep 1

# Finally, delete DATAROOT.
```

**Review by aerorahul — DISMISSED** [review]
Looks good.  
I found a suggestion online to use `sync` that ensures all modifications are synchronized.
It should help at the least, but look it up and validate it.

**Review by XuanliLi-NOAA — APPROVED** [review]
Changes look good to me. I had removed the files in my directories due to the disk quota limit, but Sean Casey at QOSAP tested the changes (including those suggested by @aerorahul) on Hera and confirmed that they solved the problem.

File: scripts/exglobal_cleanup.sh (hunk 1 above)
Comment (DavidHuber-NOAA) [reply scripts/exglobal_cleanup.sh:112]: Reading up on `sync`, I think its use here is fine and safe.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
