### PR TITLE
Fix build on non-WCOSS2 machines

### LINKED ISSUE #476: Update checkout path for UFS_UTILS component post-move
The UFS_UTILS repository has moved from under the [NOAA-EMC organization](https://github.com/NOAA-EMC) to under the [ufs-community organization](https://github.com/ufs-community). New home: https://github.com/ufs-community/UFS_UTILS

Will update the clone path in the checkout script to reflect the new home for the UFS_UTILS repository.

Thankfully GitHub automatically handles the location change when you attempt to clone from the prior NOAA-EMC org location so this move did not break anything for users cloning the full global-workflow package. This is a non-emergency change because of that.

- [ ] update path in develop branch
- [x] update path in operations branch

### LINKED ISSUE #561: build of ufs_utils and gldas on hera failing from develop branch
When building on hera, both ufs_utils and gldas is failing using the develop branch.  

The error for ufs_utils is: 
```
Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):

    Module fullname   Module Filename
    ---------------   ---------------
    build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
```

which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera.  The gldas log was not as informative, but I suspect it might be a similar/same issue?

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**

The UFS_UTILS and GLDAS versions are updated to correct build problems on development machines. Each had been using a beta version of ESMF that was removed from the hpc-stack installation without warning. Additionally, GLDAS had introduced bugs into their build scripts during the WCOSS2 port. These issues are now all corrected in the new versions.

Also updates the UFS_UTILS repository to its new location under UFS instead of EMC.

Fixes #476, #561

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

- [x] Clone and build on Hera
- [x] Clone and build on Orion
- [x] Clone and build on WCOSS-Dell
- [x] 2½-cycle test on Hera
- [x] 1½-cycle test on WCOSS-Dell

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Orion GLDAS build still failing. Holding this until I get a new update from GLDAS.

**Comment by WalterKolczynski-NOAA** [comment]
Build now passes on all three primary machines.

**Review by KateFriedman-NOAA — APPROVED** [review]
GLDAS and UFS_UTILS version updates look good. Thanks!

File: sorc/checkout.sh [hunk 1]
```diff
@@ -55,7 +55,7 @@ if [[ ! -d gldas.fd ]] ; then
     rm -f ${topdir}/checkout-gldas.log
     git clone https://github.com/NOAA-EMC/GLDAS.git gldas.fd >> ${logdir}/checkout-gldas.fd.log 2>&1
     cd gldas.fd
-    git checkout gldas_gfsv16_release.v1.15.0
+    git checkout gldas_gfsv16_release.v.1.28.0
```
Comment (aerorahul) [inline sorc/checkout.sh:58]: I assume this tag works with current `develop` of the workflow.
I recall this is the same tag as in operations headed to WCOSS2.

**Review by aerorahul — APPROVED** [review]
Changes look good.
I assume this was tested beyond just building.  Especially utilities from UFS_utils.

File: sorc/checkout.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply sorc/checkout.sh:58]: > Changes look good. I assume this was tested beyond just building. Especially utilities from UFS_utils.

I hadn't because I was focused on the original problem, which was just a bad ESMF module load and module reset not working on other machines. But since these are version updates, you're probably right and I should run a test.

**Comment by WalterKolczynski-NOAA** [comment]
> Changes look good. I assume this was tested beyond just building. Especially utilities from UFS_utils.

I hadn't because I was focused on the original issue, which was a bad ESMF module version and module reset not working on other machines. But since these are version updates, you are correct and I should run a real test.

File: sorc/checkout.sh (hunk 1 above)
Comment (WalterKolczynski-NOAA) [reply sorc/checkout.sh:58]: It is. Kate got NCO to update the version for the handoff to include the tag that had the module fixes for other machines.
