### PR TITLE
Reorder post so all flux files are generated when running offline

### LINKED ISSUE #1157: gfspost job has missing input fluxfile error when running with WRITE_DOPOST=.false.
**Expected behavior**
When WRITE_DOPOST is set to .false. in config.base, gfspost job completes successfully.

**Current behavior**
gfspost job fails due to missing fluxfile when running the following command in inter_flux.sh

    if [ $INLINE_POST = ".false." ]; then
         $WGRIB2 $PGBOUT $option1 $option21 $option22 $option23 $option24 \
         $option25 $option26 $option27 $option28 \
         -new_grid $grid1p0  fluxfile_${fhr3}_1p00
    else
         $WGRIB2 $COMOUT/${FLUXFL} $option1 $option21 $option22 $option23 $option24 \
         $option25 $option26 $option27 $option28 \
         -new_grid $grid1p0  fluxfile_${fhr3}_1p00
    fi

*** FATAL ERROR: missing input file fluxfile ***

**Machines affected**
hera

**To Reproduce**
change WRITE_DOPOST to .false. in config.base
run gfsfcst task
run gfspost task

**Additional Information**
logfile:  /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/gslv17p8_dev/FV3GFSrun/test_emc/logs/2022111800/gfspost*log

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
Post would fail when running without inline post because it would attempt to create 1p00 flux files before the flux file had been generated. `inter_flux.sh` also had to be updated to point at the correct file for offline post, which is now the same as inline.

Fixes #1157 

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
Tested and output verified.
- [X] Forecast-only test on Hera
  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

File: scripts/exgfs_atmos_post.sh [hunk 1]
```diff
@@ -206,9 +206,9 @@ if [ "${stime}" = "anl" ]; then
           wafsgrid="latlon 0:1440:0.25 90:721:-0.25"
           ${WGRIB2} "${PGBOUT}" -set_grib_type same -new_grid_winds earth \
           -new_grid_interpolation bilinear -set_bitmap 1 \
-          -new_grid ${wafsgrid} "${PGBOUT}.tmp"
+          -new_grid "${wafsgrid}" "${PGBOUT}.tmp"
```
Comment (WalterKolczynski-NOAA) [inline scripts/exgfs_atmos_post.sh]: These quotes will break the command. `${wafsgrid}` intentionally contains multiple arguments. Please ignore the linter warning for this line.

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

**Review by WalterKolczynski-NOAA — APPROVED** [review]
