### PR TITLE
Correct errors with gdas and monitoring symlinks

### LINKED ISSUE #1100: rerunning link_workflow.sh generates gdas fix error
**Expected behavior**
Reruns `./link_workflow.sh` should complete without error.

**Current behavior**
Rerunning `./link_workflow.sh` returns an error as shown below
```
[Russ.Treadon@hfe11 sorc]$ ./link_workflow.sh
ln: failed to create symbolic link 'bump/20220805': Permission denied
./link_workflow.sh encounted an error at line 184 (rc=1)

```
**Machines affected**
Only tested on Hera but may occur on other machines.

**To Reproduce**

1. clone g-w develop
2. `cd sorc`
3. `./checkout.sh -u`
4. `./build_all.sh`
5. `./link_workflow.sh`
6. `./link_workflow.sh`

The second execution of `./link_workflow.sh` will generate an error.

**Context**
It is not uncommon for a developer change of a g-w component to necessitate relinking files.

**Additional Information**
If the gdas fix section of `./link_workflow.sh` is commented out, reruns of `./link_workflow.sh` complete without error.

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
**Description**

This PR resolves issues reported in issue #1100 by @RussTreadon-NOAA related to an error when rerunning `link_workflow.sh` (when in GDASApp mode) and a dead GSI monitoring symlink under `fix/gdas`.

Fix 1: When link_workflow.sh is rerun an error occurs:

```
-bash-4.2$ ./link_workflow.sh
./link_workflow.sh completed successfully
-bash-4.2$ ./link_workflow.sh
ln: failed to create symbolic link 'bump/20220805': Permission denied ./link_workflow.sh encounted an error at line 184 (rc=1)
```

Update link_workflow.sh gdas section to remove the subfolder symlinks if they already exist before trying to make them. Error goes away now.

Fix 2: Dead symlink for a GSI monitoring file under /fix/gdas

Two extra whitespaces in link_workflow.sh cause a dead link. Remove the whitespaces and link is created correctly.

Fixes #1100

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Tested by both @RussTreadon-NOAA and @KateFriedman-NOAA.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
The two changes to `link_workflow.sh` have been tested on Hera and found to yield the intended behavior.

Sorry, @KateFriedman-NOAA , that this PR triggered a shellcheck warning.

Approve.

**Comment by KateFriedman-NOAA** [comment]
> Sorry that this PR triggered a shellcheck warning.

No worries at all @RussTreadon-NOAA ! I'm taking this opportunity to resolve other SC2248 (double quote) fixes in `link_workflow.sh` as well, so it's all good. :)

**Comment by KateFriedman-NOAA** [comment]
Running build and then link again on Hera to make sure additional double quote linter updates are good.

**Comment by KateFriedman-NOAA** [comment]
Build and rerun of link was good. This is good-to-go once @WalterKolczynski-NOAA has a chance to review.

@RussTreadon-NOAA does the GDAS app usually take a long time (30-40 mins) to build? Took that long on Hera just now.

**Comment by RussTreadon-NOAA** [comment]
> Build and rerun of link was good. This is good-to-go once @WalterKolczynski-NOAA has a chance to review.
> 
> @RussTreadon-NOAA does the GDAS app usually take a long time (30-40 mins) to build? Took that long on Hera just now.

Yes, @KateFriedman-NOAA , 30-40 minutes is not unusual to build GDASApp.

**Comment by KateFriedman-NOAA** [comment]
> Yes, 30-40 minutes is not unusual to build GDASApp.

Ok, good to know, thanks for confirming @RussTreadon-NOAA ! I don't build it often so I was worried something was wrong. :)

File: sorc/link_workflow.sh [hunk 1]
```diff
@@ -395,7 +398,7 @@ cd "${script_dir}"   ||   exit 8
       webtitle.fd
       do
         if [[ -d "${prog}" ]]; then rm -rf "${prog}"; fi
-        ${LINK} gfs_utils.fd/src/${prog} .
+        ${LINK} gfs_utils.fd/src/"${prog}" .
```
Comment (WalterKolczynski-NOAA) [inline sorc/link_workflow.sh]: Quote whole path

**Review by WalterKolczynski-NOAA — CHANGES_REQUESTED** [review]

File: sorc/link_workflow.sh (hunk 1 above)
Comment (KateFriedman-NOAA) [reply sorc/link_workflow.sh]: Changed to: `${LINK} "gfs_utils.fd/src/${prog}" .`

**Review by WalterKolczynski-NOAA — APPROVED** [review]
